import { ProductGrid } from "../ProductGrid";

const kidsGirls6M5YShirtsProducts = [
  {
    id: "kg6m5y-sh-001",
    name: "Princess Blouse",
    price: "$24",
    image: "https://images.unsplash.com/photo-1557172955-5c0491a20970?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnaXJsJTIwdG9kZGxlciUyMHNoaXJ0fGVufDF8fHx8MTc1NTE5MDIwNXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Elegant princess-style blouse with delicate details",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "White", "Lavender", "Cream"],
    brand: "Little Princess",
    rating: 4.8,
    reviews: 234,
    features: ["Princess Style", "Delicate Details", "Elegant"],
    icon: "👚",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6m5y-sh-002",
    name: "Ruffle Collar Shirt",
    price: "$22",
    image: "https://images.unsplash.com/photo-1557172955-5c0491a20970?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sweet shirt with ruffled collar and button details",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["White", "Pink", "Yellow", "Light Blue"],
    brand: "Sweet Ruffles",
    rating: 4.7,
    reviews: 189,
    features: ["Ruffle Collar", "Button Details", "Sweet"],
    icon: "👚",
    itemCount: "Sweet",
  },
  {
    id: "kg6m5y-sh-003",
    name: "Floral Button-Up",
    price: "$26",
    image: "https://images.unsplash.com/photo-1557172955-5c0491a20970?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Pretty floral print button-up shirt for spring",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink Floral", "Blue Floral", "Yellow Floral"],
    brand: "Spring Bloom",
    rating: 4.6,
    reviews: 156,
    features: ["Floral Print", "Button-Up", "Spring Style"],
    icon: "👚",
    itemCount: "Floral",
  },
  {
    id: "kg6m5y-sh-004",
    name: "Denim Shirt Dress",
    price: "$28",
    image: "https://images.unsplash.com/photo-1557172955-5c0491a20970?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Versatile denim shirt that doubles as a dress",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Denim", "Medium Denim", "White Denim"],
    brand: "Denim Darling",
    rating: 4.5,
    reviews: 123,
    features: ["Denim Fabric", "Shirt Dress", "Versatile"],
    icon: "👚",
    itemCount: "Versatile",
  },
  {
    id: "kg6m5y-sh-005",
    name: "Polka Dot Blouse",
    price: "$21",
    image: "https://images.unsplash.com/photo-1557172955-5c0491a20970?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic polka dot blouse with vintage charm",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy/White", "Pink/White", "Red/White"],
    brand: "Vintage Baby",
    rating: 4.4,
    reviews: 145,
    features: ["Polka Dots", "Vintage Style", "Charming"],
    icon: "👚",
    itemCount: "Vintage",
  },
  {
    id: "kg6m5y-sh-006",
    name: "Lace Trim Shirt",
    price: "$27",
    image: "https://images.unsplash.com/photo-1557172955-5c0491a20970?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Delicate shirt with beautiful lace trim details",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["White", "Cream", "Pink", "Lavender"],
    brand: "Lace Dreams",
    rating: 4.7,
    reviews: 167,
    features: ["Lace Trim", "Delicate", "Beautiful"],
    icon: "👚",
    itemCount: "Delicate",
  },
  {
    id: "kg6m5y-sh-007",
    name: "Bow Tie Blouse",
    price: "$25",
    image: "https://images.unsplash.com/photo-1557172955-5c0491a20970?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Adorable blouse with removable bow tie accent",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["White", "Pink", "Navy", "Red"],
    brand: "Bow Beauty",
    rating: 4.6,
    reviews: 134,
    features: ["Bow Tie", "Removable", "Adorable"],
    icon: "👚",
    itemCount: "Adorable",
  },
  {
    id: "kg6m5y-sh-008",
    name: "Peasant Style Blouse",
    price: "$23",
    image: "https://images.unsplash.com/photo-1557172955-5c0491a20970?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Bohemian peasant-style blouse with embroidered details",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["White", "Cream", "Peach", "Mint"],
    brand: "Boho Baby",
    rating: 4.3,
    reviews: 112,
    features: ["Peasant Style", "Embroidered", "Bohemian"],
    icon: "👚",
    itemCount: "Boho",
  },
  {
    id: "kg6m5y-sh-009",
    name: "Striped Sailor Shirt",
    price: "$20",
    image: "https://images.unsplash.com/photo-1557172955-5c0491a20970?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic striped sailor-style shirt with nautical vibes",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy/White", "Red/White", "Blue/White"],
    brand: "Sailor Girl",
    rating: 4.5,
    reviews: 178,
    features: ["Striped", "Sailor Style", "Nautical"],
    icon: "👚",
    itemCount: "Nautical",
  },
  {
    id: "kg6m5y-sh-010",
    name: "Garden Party Shirt",
    price: "$26",
    image: "https://images.unsplash.com/photo-1557172955-5c0491a20970?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant shirt perfect for garden parties and tea time",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Floral Pink", "Garden Green", "Sky Blue"],
    brand: "Garden Party",
    rating: 4.4,
    reviews: 156,
    features: ["Garden Theme", "Elegant", "Party Ready"],
    icon: "👚",
    itemCount: "Elegant",
  }
];

export function KidsGirls6M5YShirtsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-pink-50 via-rose-50 to-purple-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6M-5Y Shirts Collection" 
          subtitle="Pretty & Elegant Shirts for Little Ladies"
          products={kidsGirls6M5YShirtsProducts} 
        />
      </main>
    </div>
  );
}