import { ProductGrid } from "../ProductGrid";

const kidsGirls6To14YTrousersProducts = [
  {
    id: "kg6-14y-tr-001",
    name: "School Uniform Trousers",
    price: "$34",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnaXJscyUyMGtpZHMlMjB0cm91c2VycyUyMHBhbnRzfGVufDF8fHx8MTc1NTE5MTI3Nnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Professional school uniform trousers for girls",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "Gray", "Black", "Charcoal"],
    brand: "School Professional",
    rating: 4.8,
    reviews: 267,
    features: ["School Uniform", "Professional", "Durable"],
    icon: "👖",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6-14y-tr-002",
    name: "Stretch Chino Pants",
    price: "$32",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Comfortable stretch chino pants for everyday wear",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Khaki", "Navy", "White", "Pink"],
    brand: "Comfort Chino",
    rating: 4.7,
    reviews: 234,
    features: ["Stretch Fabric", "Chino Style", "Comfortable"],
    icon: "👖",
    itemCount: "Comfort",
  },
  {
    id: "kg6-14y-tr-003",
    name: "Athletic Track Pants",
    price: "$28",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Performance track pants for active girls",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "Purple", "Pink"],
    brand: "Track Star",
    rating: 4.6,
    reviews: 189,
    features: ["Athletic Performance", "Track Style", "Active"],
    icon: "👖",
    itemCount: "Athletic",
  },
  {
    id: "kg6-14y-tr-004",
    name: "Wide Leg Palazzo Pants",
    price: "$36",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy wide leg palazzo pants for fashion-forward girls",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "Cream", "Dusty Pink"],
    brand: "Fashion Palazzo",
    rating: 4.5,
    reviews: 167,
    features: ["Wide Leg", "Palazzo Style", "Trendy"],
    icon: "👖",
    itemCount: "Trendy",
  },
  {
    id: "kg6-14y-tr-005",
    name: "Cargo Utility Pants",
    price: "$35",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Functional cargo pants with multiple pockets",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Olive Green", "Khaki", "Black", "Navy"],
    brand: "Utility Style",
    rating: 4.4,
    reviews: 145,
    features: ["Cargo Pockets", "Utility Style", "Functional"],
    icon: "👖",
    itemCount: "Utility",
  },
  {
    id: "kg6-14y-tr-006",
    name: "Cropped Ankle Pants",
    price: "$30",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Stylish cropped pants that hit at the ankle",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "White", "Camel"],
    brand: "Cropped Style",
    rating: 4.3,
    reviews: 198,
    features: ["Cropped Length", "Ankle Cut", "Stylish"],
    icon: "👖",
    itemCount: "Stylish",
  },
  {
    id: "kg6-14y-tr-007",
    name: "Velvet Dress Pants",
    price: "$38",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant velvet pants for special occasions",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Burgundy Velvet", "Navy Velvet", "Black Velvet"],
    brand: "Velvet Elegance",
    rating: 4.7,
    reviews: 156,
    features: ["Velvet Fabric", "Special Occasion", "Elegant"],
    icon: "👖",
    itemCount: "Elegant",
  },
  {
    id: "kg6-14y-tr-008",
    name: "Printed Jogger Pants",
    price: "$26",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Comfortable printed jogger pants for casual wear",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Floral Print", "Galaxy Print", "Heart Print"],
    brand: "Jogger Comfort",
    rating: 4.5,
    reviews: 123,
    features: ["Printed Design", "Jogger Style", "Casual"],
    icon: "👖",
    itemCount: "Casual",
  },
  {
    id: "kg6-14y-tr-009",
    name: "High-Waisted Tailored Pants",
    price: "$37",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sophisticated high-waisted tailored pants",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "Gray", "Cream"],
    brand: "Tailored Teen",
    rating: 4.6,
    reviews: 178,
    features: ["High-Waisted", "Tailored Fit", "Sophisticated"],
    icon: "👖",
    itemCount: "Sophisticated",
  },
  {
    id: "kg6-14y-tr-010",
    name: "Corduroy Casual Pants",
    price: "$33",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cozy corduroy pants perfect for autumn wear",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Camel Cord", "Brown Cord", "Navy Cord"],
    brand: "Corduroy Comfort",
    rating: 4.4,
    reviews: 134,
    features: ["Corduroy Fabric", "Autumn Ready", "Cozy"],
    icon: "👖",
    itemCount: "Cozy",
  }
];

export function KidsGirls6To14YTrousersPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-purple-50 via-blue-50 to-pink-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6-14Y Trousers Collection" 
          subtitle="Professional & Stylish Trousers for Growing Girls"
          products={kidsGirls6To14YTrousersProducts} 
        />
      </main>
    </div>
  );
}