import { ProductGrid } from "../ProductGrid";

const coOrdSets = [
  {
    id: "kb6m5y-cs-001",
    name: "Sailor Coord Set",
    price: "$32",
    image: "https://i.pinimg.com/1200x/a1/d1/03/a1d10397e21d043498ed52ba4fc6ba2f.jpg",
    description: "Adorable sailor-themed matching shirt and shorts set",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy/White", "Red/White", "Blue/White"],
    brand: "Little Sailor",
    rating: 4.8,
    reviews: 234,
    features: ["Matching Set", "Sailor Theme", "Button Details"],
    icon: "👔",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6m5y-cs-002",
    name: "Dinosaur Adventure Set",
    price: "$28",
    image: "https://i.pinimg.com/736x/33/f0/c7/33f0c736ed32f9bc04fe31c333048cd6.jpg",
    description: "Fun dinosaur print shirt with matching shorts",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Green", "Blue", "Orange"],
    brand: "Dino Explorer",
    rating: 4.7,
    reviews: 189,
    features: ["Dinosaur Print", "Comfortable Fit", "Play Ready"],
    icon: "👔",
    itemCount: "Adventure",
  },
  {
    id: "kb6m5y-cs-003",
    name: "Formal Mini Suit",
    price: "$45",
    image: "https://i.pinimg.com/1200x/80/8d/6d/808d6d1bd8c5c308942e587d8f007732.jpg",
    description: "Smart formal set with vest, shirt, and trousers",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy", "Gray", "Black"],
    brand: "Little Gentleman",
    rating: 4.9,
    reviews: 156,
    features: ["Formal Set", "Vest Included", "Special Occasion"],
    icon: "👔",
    itemCount: "Formal",
  },
  {
    id: "kb6m5y-cs-004",
    name: "Sports Team Set",
    price: "$26",
    image: "https://i.pinimg.com/736x/9d/57/00/9d5700e83e672d18b5e42c0bc85d8e9e.jpg",
    description: "Athletic jersey and shorts set for little athletes",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Red", "Blue", "Green", "Yellow"],
    brand: "Mini Athletes",
    rating: 4.6,
    reviews: 123,
    features: ["Athletic Style", "Number Print", "Breathable"],
    icon: "👔",
    itemCount: "Sports",
  },
  {
    id: "kb6m5y-cs-005",
    name: "Farm Animal Set",
    price: "$24",
    image: "https://i.pinimg.com/1200x/a9/9c/88/a99c880391c43865c80c0e3685ae4f11.jpg",
    description: "Cute farm animal themed shirt and overalls set",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Denim", "Green", "Brown"],
    brand: "Farm Friends",
    rating: 4.5,
    reviews: 98,
    features: ["Farm Theme", "Overalls", "Adorable"],
    icon: "👔",
    itemCount: "Farm",
  },
  {
    id: "kb6m5y-cs-006",
    name: "Space Explorer Set",
    price: "$30",
    image: "https://i.pinimg.com/736x/93/28/f8/9328f8356e613a3af0359c96c3fc68c0.jpg",
    description: "Galactic themed shirt and pants with space prints",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy", "Black", "Dark Blue"],
    brand: "Space Cadets",
    rating: 4.8,
    reviews: 167,
    features: ["Space Theme", "Glow Details", "Comfortable"],
    icon: "👔",
    itemCount: "Galaxy",
  },
  {
    id: "kb6m5y-cs-007",
    name: "Striped Summer Set",
    price: "$22",
    image: "https://i.pinimg.com/736x/a3/1c/f6/a31cf64f42bda4d259134a8026a83ceb.jpg",
    description: "Classic striped tank and shorts perfect for summer",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy/White", "Red/White", "Blue/Gray"],
    brand: "Summer Days",
    rating: 4.4,
    reviews: 134,
    features: ["Striped Pattern", "Summer Ready", "Lightweight"],
    icon: "👔",
    itemCount: "Summer",
  },
  {
    id: "kb6m5y-cs-008",
    name: "Superhero Training Set",
    price: "$29",
    image: "https://i.pinimg.com/736x/65/b8/c5/65b8c53f5a3c572445cc24f67ed6521c.jpg",
    description: "Hero-themed shirt and shorts for little superheroes",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Red", "Blue", "Black"],
    brand: "Hero Academy",
    rating: 4.7,
    reviews: 178,
    features: ["Superhero Theme", "Cape Included", "Action Ready"],
    icon: "👔",
    itemCount: "Hero",
  }
];


export function KidsBoys6M5YCoordSetsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-orange-50 via-yellow-50 to-green-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6M-5Y Co-Ord Sets Collection" 
          subtitle="Perfectly Matched Outfits for Little Gentlemen"
          products={kidsBoys6M5YCoordSetsProducts} 
        />
      </main>
    </div>
  );
}