import { ProductGrid } from "../ProductGrid";

const kidsBoys6To14YTShirtsPolosProducts = [
  {
    id: "kb6-14y-tp-001",
    name: "School Spirit Polo",
    price: "$26",
    image: "https://images.unsplash.com/photo-1609723868202-31f4d66ef810?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib3lzJTIwa2lkcyUyMHBvbG8lMjBzaGlydHxlbnwxfHx8fDE3NTUxOTAzMjF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Classic school polo shirt with embroidered logo",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "White", "Red", "Green"],
    brand: "School Pride",
    rating: 4.8,
    reviews: 267,
    features: ["School Ready", "Embroidered Logo", "Classic Fit"],
    icon: "👕",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6-14y-tp-002",
    name: "Sports Team T-Shirt",
    price: "$22",
    image: "https://images.unsplash.com/photo-1609723868202-31f4d66ef810?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Athletic team-style t-shirt with number graphics",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Red", "Blue", "Green", "Black"],
    brand: "Team Spirit",
    rating: 4.7,
    reviews: 234,
    features: ["Team Style", "Number Graphics", "Athletic Fit"],
    icon: "👕",
    itemCount: "Sports",
  },
  {
    id: "kb6-14y-tp-003",
    name: "Gaming Hero Tee",
    price: "$24",
    image: "https://images.unsplash.com/photo-1609723868202-31f4d66ef810?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cool gaming-themed t-shirt with pixel art designs",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "Gray", "Green"],
    brand: "Game On",
    rating: 4.6,
    reviews: 198,
    features: ["Gaming Theme", "Pixel Art", "Cool Design"],
    icon: "👕",
    itemCount: "Gaming",
  },
  {
    id: "kb6-14y-tp-004",
    name: "Skateboard Graphic Tee",
    price: "$23",
    image: "https://images.unsplash.com/photo-1609723868202-31f4d66ef810?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Street-style skateboard graphic t-shirt for cool kids",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "White", "Gray", "Navy"],
    brand: "Street Style",
    rating: 4.5,
    reviews: 156,
    features: ["Skateboard Graphics", "Street Style", "Cool"],
    icon: "👕",
    itemCount: "Street",
  },
  {
    id: "kb6-14y-tp-005",
    name: "Long Sleeve Polo",
    price: "$28",
    image: "https://images.unsplash.com/photo-1609723868202-31f4d66ef810?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic long sleeve polo perfect for cooler weather",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "Gray", "White", "Burgundy"],
    brand: "Classic Polo",
    rating: 4.4,
    reviews: 145,
    features: ["Long Sleeve", "Polo Style", "Cool Weather"],
    icon: "👕",
    itemCount: "Classic",
  },
  {
    id: "kb6-14y-tp-006",
    name: "Science Explorer Tee",
    price: "$21",
    image: "https://images.unsplash.com/photo-1609723868202-31f4d66ef810?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Educational science-themed t-shirt with fun facts",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Blue", "Green", "Purple", "Orange"],
    brand: "Science Fun",
    rating: 4.6,
    reviews: 167,
    features: ["Science Theme", "Educational", "Fun Facts"],
    icon: "👕",
    itemCount: "Educational",
  },
  {
    id: "kb6-14y-tp-007",
    name: "Vintage Band Tee",
    price: "$25",
    image: "https://images.unsplash.com/photo-1609723868202-31f4d66ef810?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Retro-style band t-shirt with vintage graphics",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Gray", "Navy", "Charcoal"],
    brand: "Vintage Vibes",
    rating: 4.7,
    reviews: 189,
    features: ["Vintage Style", "Band Graphics", "Retro"],
    icon: "👕",
    itemCount: "Vintage",
  },
  {
    id: "kb6-14y-tp-008",
    name: "Adventure Polo",
    price: "$27",
    image: "https://images.unsplash.com/photo-1609723868202-31f4d66ef810?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Outdoor adventure-themed polo with nature graphics",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Khaki", "Forest Green", "Brown", "Navy"],
    brand: "Adventure Kids",
    rating: 4.5,
    reviews: 123,
    features: ["Adventure Theme", "Nature Graphics", "Outdoor"],
    icon: "👕",
    itemCount: "Adventure",
  },
  {
    id: "kb6-14y-tp-009",
    name: "Striped Rugby Shirt",
    price: "$29",
    image: "https://images.unsplash.com/photo-1609723868202-31f4d66ef810?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic striped rugby shirt with collar and placket",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy/White", "Red/White", "Green/White"],
    brand: "Rugby Style",
    rating: 4.6,
    reviews: 134,
    features: ["Striped Pattern", "Rugby Style", "Collar"],
    icon: "👕",
    itemCount: "Rugby",
  },
  {
    id: "kb6-14y-tp-010",
    name: "Plain Essential Tee",
    price: "$18",
    image: "https://images.unsplash.com/photo-1609723868202-31f4d66ef810?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Basic essential t-shirt perfect for layering",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Black", "Gray", "Navy"],
    brand: "Basics",
    rating: 4.3,
    reviews: 178,
    features: ["Basic Style", "Essential", "Layering"],
    icon: "👕",
    itemCount: "Essential",
  }
];

export function KidsBoys6To14YTShirtsPolosPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-green-50 to-purple-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6-14Y T-Shirts & Polos Collection" 
          subtitle="Cool & Comfortable Styles for Growing Boys"
          products={kidsBoys6To14YTShirtsPolosProducts} 
        />
      </main>
    </div>
  );
}