import { ProductGrid } from "../ProductGrid";

const kidsBoys6M5YShirtsProducts = [
  {
    id: "kb6m5y-s-001",
    name: "Button-Down Mini Shirt",
    price: "$22",
    image: "https://i.pinimg.com/736x/29/52/e3/2952e338e738e21ff8690c2fab457d4a.jpg",
    description: "Adorable button-down shirt perfect for special occasions",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["White", "Light Blue", "Navy", "Cream"],
    brand: "Little Gentleman",
    rating: 4.8,
    reviews: 189,
    features: ["Button-Down", "Soft Cotton", "Easy Care"],
    icon: "👔",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6m5y-s-002",
    name: "Plaid Dress Shirt",
    price: "$24",
    image: "https://i.pinimg.com/1200x/ca/72/17/ca72173c40a604837485568194e01e1c.jpg",
    description: "Classic plaid pattern dress shirt for little boys",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Blue Plaid", "Red Plaid", "Green Plaid"],
    brand: "Tiny Formal",
    rating: 4.6,
    reviews: 134,
    features: ["Plaid Pattern", "Collar", "Machine Washable"],
    icon: "👔",
    itemCount: "Classic",
  },
  {
    id: "kb6m5y-s-003",
    name: "Safari Adventure Shirt",
    price: "$20",
    image: "https://i.pinimg.com/736x/b9/69/3b/b9693b6b76f1d1902ed4a131f59238ba.jpg",
    description: "Fun safari-themed shirt with animal prints",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Khaki", "Safari Green", "Tan"],
    brand: "Adventure Kids",
    rating: 4.7,
    reviews: 156,
    features: ["Safari Theme", "Pocket Detail", "Comfortable"],
    icon: "👔",
    itemCount: "Adventure",
  },
  {
    id: "kb6m5y-s-004",
    name: "Striped Oxford Shirt",
    price: "$26",
    image: "https://i.pinimg.com/736x/1b/fc/fe/1bfcfe89eafa0f7ea75711a2eb0c2416.jpg",
    description: "Preppy striped oxford shirt for smart casual looks",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Blue Stripe", "Navy Stripe", "Pink Stripe"],
    brand: "Preppy Tot",
    rating: 4.5,
    reviews: 112,
    features: ["Oxford Fabric", "Striped", "Preppy Style"],
    icon: "👔",
    itemCount: "Preppy",
  },
  {
    id: "kb6m5y-s-005",
    name: "Denim Shirt",
    price: "$28",
    image: "https://i.pinimg.com/736x/e8/7d/d7/e87dd7f8e51bc86becf0c89848415fb0.jpg",
    description: "Trendy denim shirt for casual everyday wear",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Denim Baby",
    rating: 4.4,
    reviews: 98,
    features: ["Denim Fabric", "Snap Buttons", "Casual"],
    icon: "👔",
    itemCount: "Casual",
  },
  {
    id: "kb6m5y-s-006",
    name: "Bow Tie Shirt Set",
    price: "$32",
    image: "https://i.pinimg.com/736x/e6/d8/bc/e6d8bc0187c6b6efe84341a061a43212.jpg",
    description: "Formal shirt with detachable bow tie for special events",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["White", "Light Blue", "Cream"],
    brand: "Little Formal",
    rating: 4.9,
    reviews: 87,
    features: ["Bow Tie Included", "Formal", "Special Occasion"],
    icon: "👔",
    itemCount: "Formal",
  },
  {
    id: "kb6m5y-s-007",
    name: "Checked Flannel Shirt",
    price: "$25",
    image: "https://i.pinimg.com/1200x/b8/a4/24/b8a42488b2c58813745e6f027b5c481c.jpg",
    description: "Cozy flannel shirt perfect for cooler weather",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Red Check", "Blue Check", "Green Check"],
    brand: "Cozy Kids",
    rating: 4.6,
    reviews: 123,
    features: ["Flannel Fabric", "Checked Pattern", "Warm"],
    icon: "👔",
    itemCount: "Cozy",
  },
  {
    id: "kb6m5y-s-008",
    name: "Linen Blend Shirt",
    price: "$30",
    image: "https://i.pinimg.com/736x/fd/1e/4c/fd1e4c88e8f47ec12cab741ce05807bd.jpg",
    description: "Breathable linen blend shirt for summer comfort",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Natural", "White", "Light Blue"],
    brand: "Summer Breeze",
    rating: 4.3,
    reviews: 76,
    features: ["Linen Blend", "Breathable", "Summer"],
    icon: "👔",
    itemCount: "Summer",
  },
  
];

export function KidsBoys6M5YShirtsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-green-50 to-yellow-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6M-5Y Shirts Collection" 
          subtitle="Smart & Adorable Shirts for Little Gentlemen"
          products={kidsBoys6M5YShirtsProducts} 
        />
      </main>
    </div>
  );
}