import { ProductGrid } from "../ProductGrid";

const kidsBoys6To14YShirtsProducts = [
  {
    id: "kb6-14y-s-001",
    name: "Oxford School Shirt",
    price: "$32",
    image: "https://images.unsplash.com/photo-1725860631633-17ac01dcf80b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib3lzJTIwa2lkcyUyMHNoaXJ0fGVufDF8fHx8MTc1NTE5MDE1NHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Classic oxford shirt perfect for school and formal occasions",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Light Blue", "Navy", "Gray"],
    brand: "School Essential",
    rating: 4.8,
    reviews: 245,
    features: ["Oxford Fabric", "Button-Down", "School Ready"],
    icon: "👔",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6-14y-s-002",
    name: "Plaid Flannel Shirt",
    price: "$28",
    image: "https://images.unsplash.com/photo-1725860631633-17ac01dcf80b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cozy plaid flannel shirt for casual cool weather",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Red Plaid", "Blue Plaid", "Green Plaid", "Gray Plaid"],
    brand: "Flannel Kids",
    rating: 4.7,
    reviews: 189,
    features: ["Flannel Fabric", "Plaid Pattern", "Cozy"],
    icon: "👔",
    itemCount: "Cozy",
  },
  {
    id: "kb6-14y-s-003",
    name: "Denim Button-Up",
    price: "$34",
    image: "https://images.unsplash.com/photo-1725860631633-17ac01dcf80b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic denim shirt for casual everyday style",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Denim Co",
    rating: 4.6,
    reviews: 156,
    features: ["Denim Fabric", "Button-Up", "Casual Style"],
    icon: "👔",
    itemCount: "Casual",
  },
  {
    id: "kb6-14y-s-004",
    name: "Polo Collar Shirt",
    price: "$26",
    image: "https://images.unsplash.com/photo-1725860631633-17ac01dcf80b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Smart polo-style shirt with button placket",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "White", "Red", "Green"],
    brand: "Polo Kids",
    rating: 4.5,
    reviews: 123,
    features: ["Polo Collar", "Button Placket", "Smart Casual"],
    icon: "👔",
    itemCount: "Smart",
  },
  {
    id: "kb6-14y-s-005",
    name: "Striped Dress Shirt",
    price: "$30",
    image: "https://images.unsplash.com/photo-1725860631633-17ac01dcf80b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant striped dress shirt for special occasions",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Blue Stripe", "Gray Stripe", "Pink Stripe"],
    brand: "Dress Up",
    rating: 4.4,
    reviews: 145,
    features: ["Striped Pattern", "Dress Shirt", "Elegant"],
    icon: "👔",
    itemCount: "Elegant",
  },
  {
    id: "kb6-14y-s-006",
    name: "Adventure Print Shirt",
    price: "$25",
    image: "https://images.unsplash.com/photo-1725860631633-17ac01dcf80b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Fun adventure-themed print shirt for outdoor activities",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Khaki", "Olive", "Navy", "Brown"],
    brand: "Adventure Boys",
    rating: 4.6,
    reviews: 167,
    features: ["Adventure Print", "Outdoor Theme", "Fun"],
    icon: "👔",
    itemCount: "Adventure",
  },
  {
    id: "kb6-14y-s-007",
    name: "Formal White Shirt",
    price: "$35",
    image: "https://images.unsplash.com/photo-1725860631633-17ac01dcf80b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Crisp white dress shirt for formal events and ceremonies",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Off-White", "Cream"],
    brand: "Formal Wear",
    rating: 4.9,
    reviews: 134,
    features: ["Formal Style", "Crisp White", "Premium"],
    icon: "👔",
    itemCount: "Formal",
  },
  {
    id: "kb6-14y-s-008",
    name: "Hawaiian Print Shirt",
    price: "$27",
    image: "https://images.unsplash.com/photo-1725860631633-17ac01dcf80b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Tropical Hawaiian print shirt for vacation vibes",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Tropical Blue", "Palm Green", "Sunset Orange"],
    brand: "Island Style",
    rating: 4.3,
    reviews: 112,
    features: ["Hawaiian Print", "Tropical", "Vacation Style"],
    icon: "👔",
    itemCount: "Tropical",
  },
  {
    id: "kb6-14y-s-009",
    name: "Linen Blend Shirt",
    price: "$33",
    image: "https://images.unsplash.com/photo-1725860631633-17ac01dcf80b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Breathable linen blend shirt perfect for summer",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Natural", "White", "Light Blue", "Sage"],
    brand: "Summer Linen",
    rating: 4.5,
    reviews: 178,
    features: ["Linen Blend", "Breathable", "Summer Ready"],
    icon: "👔",
    itemCount: "Summer",
  },
  {
    id: "kb6-14y-s-010",
    name: "Checkered Sport Shirt",
    price: "$29",
    image: "https://images.unsplash.com/photo-1725860631633-17ac01dcf80b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic checkered sport shirt for active boys",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Red Check", "Blue Check", "Green Check"],
    brand: "Sport Check",
    rating: 4.4,
    reviews: 156,
    features: ["Checkered Pattern", "Sport Style", "Active"],
    icon: "👔",
    itemCount: "Sport",
  }
];

export function KidsBoys6To14YShirtsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6-14Y Shirts Collection" 
          subtitle="Smart & Stylish Shirts for Growing Boys"
          products={kidsBoys6To14YShirtsProducts} 
        />
      </main>
    </div>
  );
}