import { ProductGrid } from "../ProductGrid";

const kidsBoys6To14YTrousersProducts = [
  {
    id: "kb6-14y-tr-001",
    name: "School Uniform Trousers",
    price: "$32",
    image: "https://i.pinimg.com/1200x/77/1c/e8/771ce8fc55eec389ae5463c3f9277f0a.jpg",
    description: "Classic school uniform trousers for boys",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "Gray", "Black", "Charcoal"],
    brand: "School Standard",
    rating: 4.8,
    reviews: 289,
    features: ["School Uniform", "Classic", "Durable"],
    icon: "👖",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6-14y-tr-002",
    name: "Cargo Adventure Pants",
    price: "$35",
    image: "https://i.pinimg.com/1200x/3c/a5/fa/3ca5fa15ecd781055e050d6cb88b2657.jpg",
    description: "Functional cargo pants with multiple pockets",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Khaki", "Olive Green", "Navy", "Black"],
    brand: "Adventure Gear",
    rating: 4.7,
    reviews: 234,
    features: ["Cargo Pockets", "Adventure Ready", "Functional"],
    icon: "👖",
    itemCount: "Adventure",
  },
  {
    id: "kb6-14y-tr-003",
    name: "Athletic Track Pants",
    price: "$28",
    image: "https://i.pinimg.com/736x/f0/2c/4b/f02c4b7671601e93ce6a0221876b27a0.jpg",
    description: "Performance track pants for athletic boys",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "Gray", "Red"],
    brand: "Track Star",
    rating: 4.6,
    reviews: 198,
    features: ["Athletic Performance", "Track Style", "Sports"],
    icon: "👖",
    itemCount: "Athletic",
  },
  {
    id: "kb6-14y-tr-004",
    name: "Chino Casual Pants",
    price: "$30",
    image: "https://i.pinimg.com/736x/4d/19/d0/4d19d01545e4d9fc102ed7b24f497726.jpg",
    description: "Smart casual chino pants for everyday wear",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Khaki", "Navy", "Gray", "Olive"],
    brand: "Casual Chino",
    rating: 4.5,
    reviews: 167,
    features: ["Chino Style", "Casual", "Smart"],
    icon: "👖",
    itemCount: "Casual",
  },
  {
    id: "kb6-14y-tr-005",
    name: "Tech Jogger Pants",
    price: "$33",
    image: "https://i.pinimg.com/736x/a6/9b/f8/a69bf81e3dfafa3229eb5011ddd99436.jpg",
    description: "High-tech jogger pants with moisture-wicking",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Tech Black", "Sport Gray", "Performance Navy"],
    brand: "Tech Sport",
    rating: 4.4,
    reviews: 145,
    features: ["Tech Fabric", "Moisture Wicking", "Jogger"],
    icon: "👖",
    itemCount: "Tech",
  },
  {
    id: "kb6-14y-tr-006",
    name: "Sweatpants Comfort",
    price: "$26",
    image: "https://i.pinimg.com/736x/5d/b6/c8/5db6c831af8dbf44a42a876e84496f09.jpg",
    description: "Cozy sweatpants for ultimate comfort",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Gray", "Black", "Navy", "Heather"],
    brand: "Comfort Zone",
    rating: 4.7,
    reviews: 189,
    features: ["Sweatpants", "Ultimate Comfort", "Cozy"],
    icon: "👖",
    itemCount: "Comfort",
  },
  {
    id: "kb6-14y-tr-007",
    name: "Dress Pants Formal",
    price: "$36",
    image: "https://i.pinimg.com/736x/d2/9c/bb/d29cbbc9330aec933eca4d75268b2c7a.jpg",
    description: "Formal dress pants for special occasions",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "Charcoal", "Dark Gray"],
    brand: "Formal Wear",
    rating: 4.3,
    reviews: 156,
    features: ["Formal Style", "Special Occasion", "Dress"],
    icon: "👖",
    itemCount: "Formal",
  },
  {
    id: "kb6-14y-tr-008",
    name: "Tactical Style Pants",
    price: "$34",
    image: "https://img.fantaskycdn.com/dba13655116bb1f7a353400ce41b8d1c_2056x.jpeg",
    description: "Tactical-inspired pants for outdoor adventures",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Tactical Green", "Combat Black", "Field Gray"],
    brand: "Tactical Gear",
    rating: 4.5,
    reviews: 123,
    features: ["Tactical Style", "Outdoor", "Adventure"],
    icon: "👖",
    itemCount: "Tactical",
  },
  
];

export function KidsBoys6To14YTrousersPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-green-50 via-blue-50 to-gray-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6-14Y Trousers Collection" 
          subtitle="Versatile & Comfortable Trousers for Growing Boys"
          products={kidsBoys6To14YTrousersProducts} 
        />
      </main>
    </div>
  );
}