import { ProductGrid } from "../ProductGrid";

const kidsBoys6M5YTrousersProducts = [
  {
    id: "kb6m5y-tr-001",
    name: "Smart Casual Chinos",
    price: "$28",
    image: "https://i.pinimg.com/736x/6e/7c/ed/6e7cedda3add477b301ce23fa0967126.jpg",
    description: "Elegant chino trousers perfect for special occasions",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy", "Beige", "Gray", "Olive"],
    brand: "Little Gentleman",
    rating: 4.8,
    reviews: 234,
    features: ["Smart Casual", "Adjustable Waist", "Premium Cotton"],
    icon: "👖",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6m5y-tr-002",
    name: "Corduroy Play Pants",
    price: "$25",
    image: "https://i.pinimg.com/736x/be/ed/62/beed621fca105d02af47a6a300450ab1.jpg",
    description: "Soft corduroy trousers for cozy autumn days",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Brown", "Navy", "Forest Green", "Burgundy"],
    brand: "Cozy Kids",
    rating: 4.7,
    reviews: 189,
    features: ["Corduroy Fabric", "Soft Texture", "Autumn Ready"],
    icon: "👖",
    itemCount: "Cozy",
  },
  {
    id: "kb6m5y-tr-003",
    name: "Adventure Cargo Pants",
    price: "$26",
    image: "https://i.pinimg.com/1200x/22/24/ad/2224ad6a31f158503dedf87d8865fa61.jpg",
    description: "Durable cargo pants with plenty of pocket space",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Khaki", "Olive Green", "Navy", "Gray"],
    brand: "Adventure Kids",
    rating: 4.6,
    reviews: 156,
    features: ["Cargo Pockets", "Durable", "Explorer Style"],
    icon: "👖",
    itemCount: "Adventure",
  },
  {
    id: "kb6m5y-tr-004",
    name: "Formal Dress Pants",
    price: "$32",
    image: "https://i.pinimg.com/736x/d1/5e/2e/d15e2e5a9ac8c28f4e8dc502e29653ef.jpg",
    description: "Elegant dress pants for weddings and special events",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Black", "Navy", "Charcoal", "Dark Brown"],
    brand: "Formal Tots",
    rating: 4.9,
    reviews: 123,
    features: ["Formal Style", "Premium Fabric", "Special Occasion"],
    icon: "👖",
    itemCount: "Formal",
  },
  {
    id: "kb6m5y-tr-005",
    name: "Elastic Waist Joggers",
    price: "$22",
    image: "https://i.pinimg.com/736x/79/c4/46/79c446a7b28b0287dd73d1473479c7f0.jpg",
    description: "Comfortable jogger-style pants for active play",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Gray", "Navy", "Black", "Green"],
    brand: "Active Kids",
    rating: 4.5,
    reviews: 198,
    features: ["Elastic Waist", "Jogger Style", "Active Wear"],
    icon: "👖",
    itemCount: "Active",
  },
  {
    id: "kb6m5y-tr-006",
    name: "Plaid School Pants",
    price: "$27",
    image: "https://i.pinimg.com/736x/cb/e5/85/cbe585a83b754a956237cc50f8c5edaf.jpg",
    description: "Classic plaid pattern trousers for school wear",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy Plaid", "Gray Plaid", "Green Plaid"],
    brand: "School Days",
    rating: 4.4,
    reviews: 145,
    features: ["Plaid Pattern", "School Ready", "Classic Style"],
    icon: "👖",
    itemCount: "School",
  },
  {
    id: "kb6m5y-tr-007",
    name: "Twill Adventure Pants",
    price: "$24",
    image: "https://i.pinimg.com/1200x/17/9c/4a/179c4a41147ae33de3c18b0f66e4c479.jpg",
    description: "Sturdy twill pants built for outdoor adventures",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Khaki", "Olive", "Brown", "Navy"],
    brand: "Outdoor Tots",
    rating: 4.6,
    reviews: 167,
    features: ["Twill Fabric", "Sturdy", "Outdoor Ready"],
    icon: "👖",
    itemCount: "Outdoor",
  },
  {
    id: "kb6m5y-tr-008",
    name: "Stretch Comfort Pants",
    price: "$23",
    image: "https://i.pinimg.com/1200x/c2/f7/d7/c2f7d70e13db1fc1f1489a5b59d04f87.jpg",
    description: "Super stretchy pants for maximum comfort and movement",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Black", "Navy", "Gray", "Brown"],
    brand: "Stretch Zone",
    rating: 4.3,
    reviews: 134,
    features: ["Stretch Fabric", "Comfortable", "Flexible"],
    icon: "👖",
    itemCount: "Comfort",
  },
 
];

export function KidsBoys6M5YTrousersPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-green-50 via-blue-50 to-purple-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6M-5Y Trousers Collection" 
          subtitle="Smart & Comfortable Trousers for Growing Boys"
          products={kidsBoys6M5YTrousersProducts} 
        />
      </main>
    </div>
  );
}