import { ProductGrid } from "../ProductGrid";

const kidsBoys6M5YShortsProducts = [
  {
    id: "kb6m5y-sh-001",
    name: "Adventure Explorer Shorts",
    price: "$18",
    image: "https://i.pinimg.com/1200x/24/1a/cc/241acc0eb40db4f995dc6c728d7a9989.jpg",
    description: "Comfortable cargo shorts perfect for playground adventures",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Khaki", "Navy", "Green", "Gray"],
    brand: "Little Explorer",
    rating: 4.8,
    reviews: 245,
    features: ["Cargo Pockets", "Adjustable Waist", "Durable"],
    icon: "🩳",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6m5y-sh-002",
    name: "Denim Play Shorts",
    price: "$22",
    image: "https://i.pinimg.com/1200x/f5/06/19/f50619b8d9b0884439ee591f8f1b100e.jpg",
    description: "Classic denim shorts with toddler-friendly features",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Denim Kids",
    rating: 4.7,
    reviews: 189,
    features: ["Soft Denim", "Easy Snap", "Play Ready"],
    icon: "🩳",
    itemCount: "Classic",
  },
  {
    id: "kb6m5y-sh-003",
    name: "Summer Breeze Shorts",
    price: "$16",
    image: "https://i.pinimg.com/1200x/7a/61/31/7a613186e3b1b8275dd12afd1d6670b4.jpg",
    description: "Lightweight cotton shorts for hot summer days",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Sky Blue", "Sunshine Yellow", "Coral", "White"],
    brand: "Summer Days",
    rating: 4.6,
    reviews: 156,
    features: ["Lightweight", "Breathable", "Colorful"],
    icon: "🩳",
    itemCount: "Summer",
  },
  {
    id: "kb6m5y-sh-004",
    name: "Sports Team Shorts",
    price: "$20",
    image: "https://i.pinimg.com/736x/d3/07/9c/d3079c1c5e45d5df893399579d6e94d5.jpg",
    description: "Athletic mesh shorts for active little boys",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Red", "Blue", "Green", "Black"],
    brand: "Mini Athletes",
    rating: 4.5,
    reviews: 123,
    features: ["Mesh Material", "Athletic Fit", "Team Colors"],
    icon: "🩳",
    itemCount: "Sports",
  },
  {
    id: "kb6m5y-sh-005",
    name: "Dinosaur Print Shorts",
    price: "$17",
    image: "https://i.pinimg.com/1200x/52/7a/4e/527a4e5c40c243eb345bb40ed3b98aec.jpg",
    description: "Fun dinosaur-themed shorts for dino enthusiasts",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Green", "Blue", "Brown", "Orange"],
    brand: "Dino Adventures",
    rating: 4.7,
    reviews: 198,
    features: ["Dinosaur Print", "Soft Cotton", "Fun Design"],
    icon: "🩳",
    itemCount: "Adventure",
  },
  {
    id: "kb6m5y-sh-006",
    name: "Chino Style Shorts",
    price: "$24",
    image: "https://i.pinimg.com/1200x/19/83/8e/19838e3d1106403f0f24f8b011f07c96.jpg",
    description: "Smart casual chino shorts for special occasions",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Beige", "Navy", "Olive", "White"],
    brand: "Little Gentleman",
    rating: 4.4,
    reviews: 134,
    features: ["Chino Style", "Belt Loops", "Smart Casual"],
    icon: "🩳",
    itemCount: "Smart",
  },
  {
    id: "kb6m5y-sh-007",
    name: "Striped Beach Shorts",
    price: "$19",
    image: "https://i.pinimg.com/1200x/07/dd/63/07dd63d8e5cc07abd8dbfdeebeb4ae05.jpg",
    description: "Quick-dry striped shorts perfect for beach days",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy/White", "Red/White", "Blue/Gray"],
    brand: "Beach Babies",
    rating: 4.3,
    reviews: 167,
    features: ["Quick Dry", "Striped", "Beach Ready"],
    icon: "🩳",
    itemCount: "Beach",
  },
  {
    id: "kb6m5y-sh-008",
    name: "Safari Adventure Shorts",
    price: "$21",
    image: "https://i.pinimg.com/736x/8b/4e/91/8b4e9182606e0f693dbab44a4e9996db.jpg",
    description: "Explorer-style shorts with multiple pockets",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Safari Tan", "Olive Green", "Khaki"],
    brand: "Safari Kids",
    rating: 4.6,
    reviews: 145,
    features: ["Multiple Pockets", "Safari Style", "Durable"],
    icon: "🩳",
    itemCount: "Explorer",
  },
  
];

export function KidsBoys6M5YShortsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-cyan-50 to-green-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6M-5Y Shorts Collection" 
          subtitle="Comfortable & Fun Shorts for Active Little Boys"
          products={kidsBoys6M5YShortsProducts} 
        />
      </main>
    </div>
  );
}