import { ProductGrid } from "../ProductGrid";

const kidsBoys6M5YCoordSetsProducts = [
  {
    id: "kb6m5y-cs-001",
    name: "Sailor Coord Set",
    price: "$32",
    image: "https://images.unsplash.com/photo-1672862621192-850af71d9aa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWJ5JTIwYm95JTIwY29vcmQlMjBzZXQlMjBvdXRmaXR8ZW58MXx8fHwxNzU1MTg5NzMyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Adorable sailor-themed matching shirt and shorts set",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy/White", "Red/White", "Blue/White"],
    brand: "Little Sailor",
    rating: 4.8,
    reviews: 234,
    features: ["Matching Set", "Sailor Theme", "Button Details"],
    icon: "👔",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6m5y-cs-002",
    name: "Dinosaur Adventure Set",
    price: "$28",
    image: "https://images.unsplash.com/photo-1672862621192-850af71d9aa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Fun dinosaur print shirt with matching shorts",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Green", "Blue", "Orange"],
    brand: "Dino Explorer",
    rating: 4.7,
    reviews: 189,
    features: ["Dinosaur Print", "Comfortable Fit", "Play Ready"],
    icon: "👔",
    itemCount: "Adventure",
  },
  {
    id: "kb6m5y-cs-003",
    name: "Formal Mini Suit",
    price: "$45",
    image: "https://images.unsplash.com/photo-1672862621192-850af71d9aa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Smart formal set with vest, shirt, and trousers",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy", "Gray", "Black"],
    brand: "Little Gentleman",
    rating: 4.9,
    reviews: 156,
    features: ["Formal Set", "Vest Included", "Special Occasion"],
    icon: "👔",
    itemCount: "Formal",
  },
  {
    id: "kb6m5y-cs-004",
    name: "Sports Team Set",
    price: "$26",
    image: "https://images.unsplash.com/photo-1672862621192-850af71d9aa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Athletic jersey and shorts set for little athletes",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Red", "Blue", "Green", "Yellow"],
    brand: "Mini Athletes",
    rating: 4.6,
    reviews: 123,
    features: ["Athletic Style", "Number Print", "Breathable"],
    icon: "👔",
    itemCount: "Sports",
  },
  {
    id: "kb6m5y-cs-005",
    name: "Farm Animal Set",
    price: "$24",
    image: "https://images.unsplash.com/photo-1672862621192-850af71d9aa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cute farm animal themed shirt and overalls set",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Denim", "Green", "Brown"],
    brand: "Farm Friends",
    rating: 4.5,
    reviews: 98,
    features: ["Farm Theme", "Overalls", "Adorable"],
    icon: "👔",
    itemCount: "Farm",
  },
  {
    id: "kb6m5y-cs-006",
    name: "Space Explorer Set",
    price: "$30",
    image: "https://images.unsplash.com/photo-1672862621192-850af71d9aa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Galactic themed shirt and pants with space prints",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy", "Black", "Dark Blue"],
    brand: "Space Cadets",
    rating: 4.8,
    reviews: 167,
    features: ["Space Theme", "Glow Details", "Comfortable"],
    icon: "👔",
    itemCount: "Galaxy",
  },
  {
    id: "kb6m5y-cs-007",
    name: "Striped Summer Set",
    price: "$22",
    image: "https://images.unsplash.com/photo-1672862621192-850af71d9aa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic striped tank and shorts perfect for summer",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy/White", "Red/White", "Blue/Gray"],
    brand: "Summer Days",
    rating: 4.4,
    reviews: 134,
    features: ["Striped Pattern", "Summer Ready", "Lightweight"],
    icon: "👔",
    itemCount: "Summer",
  },
  {
    id: "kb6m5y-cs-008",
    name: "Superhero Training Set",
    price: "$29",
    image: "https://images.unsplash.com/photo-1672862621192-850af71d9aa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Hero-themed shirt and shorts for little superheroes",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Red", "Blue", "Black"],
    brand: "Hero Academy",
    rating: 4.7,
    reviews: 178,
    features: ["Superhero Theme", "Cape Included", "Action Ready"],
    icon: "👔",
    itemCount: "Hero",
  },
  {
    id: "kb6m5y-cs-009",
    name: "Beach Vacation Set",
    price: "$25",
    image: "https://images.unsplash.com/photo-1672862621192-850af71d9aa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Tropical shirt and swim shorts for beach days",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Tropical", "Blue", "Green"],
    brand: "Beach Babies",
    rating: 4.3,
    reviews: 89,
    features: ["Beach Ready", "Quick Dry", "Tropical Print"],
    icon: "👔",
    itemCount: "Beach",
  },
  {
    id: "kb6m5y-cs-010",
    name: "Gentleman's Brunch Set",
    price: "$38",
    image: "https://images.unsplash.com/photo-1672862621192-850af71d9aa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sophisticated button-up and chino set for special events",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Cream", "Light Blue", "White"],
    brand: "Little Lord",
    rating: 4.6,
    reviews: 145,
    features: ["Sophisticated", "Button-Up", "Chino Pants"],
    icon: "👔",
    itemCount: "Sophisticated",
  }
];

export function KidsBoys6M5YCoordSetsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-orange-50 via-yellow-50 to-green-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6M-5Y Co-Ord Sets Collection" 
          subtitle="Perfectly Matched Outfits for Little Gentlemen"
          products={kidsBoys6M5YCoordSetsProducts} 
        />
      </main>
    </div>
  );
}