import { ProductGrid } from "../ProductGrid";

const kidsBoys6To14YTrousersProducts = [
  {
    id: "kb6-14y-tr-001",
    name: "School Uniform Trousers",
    price: "$32",
    image: "https://images.unsplash.com/photo-1668689517052-3ef175d8c8ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib3lzJTIwa2lkcyUyMHRyb3VzZXJzJTIwcGFudHN8ZW58MXx8fHwxNzU1MTkxMzc4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Classic school uniform trousers for boys",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "Gray", "Black", "Charcoal"],
    brand: "School Standard",
    rating: 4.8,
    reviews: 289,
    features: ["School Uniform", "Classic", "Durable"],
    icon: "👖",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6-14y-tr-002",
    name: "Cargo Adventure Pants",
    price: "$35",
    image: "https://images.unsplash.com/photo-1668689517052-3ef175d8c8ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Functional cargo pants with multiple pockets",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Khaki", "Olive Green", "Navy", "Black"],
    brand: "Adventure Gear",
    rating: 4.7,
    reviews: 234,
    features: ["Cargo Pockets", "Adventure Ready", "Functional"],
    icon: "👖",
    itemCount: "Adventure",
  },
  {
    id: "kb6-14y-tr-003",
    name: "Athletic Track Pants",
    price: "$28",
    image: "https://images.unsplash.com/photo-1668689517052-3ef175d8c8ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Performance track pants for athletic boys",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "Gray", "Red"],
    brand: "Track Star",
    rating: 4.6,
    reviews: 198,
    features: ["Athletic Performance", "Track Style", "Sports"],
    icon: "👖",
    itemCount: "Athletic",
  },
  {
    id: "kb6-14y-tr-004",
    name: "Chino Casual Pants",
    price: "$30",
    image: "https://images.unsplash.com/photo-1668689517052-3ef175d8c8ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Smart casual chino pants for everyday wear",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Khaki", "Navy", "Gray", "Olive"],
    brand: "Casual Chino",
    rating: 4.5,
    reviews: 167,
    features: ["Chino Style", "Casual", "Smart"],
    icon: "👖",
    itemCount: "Casual",
  },
  {
    id: "kb6-14y-tr-005",
    name: "Tech Jogger Pants",
    price: "$33",
    image: "https://images.unsplash.com/photo-1668689517052-3ef175d8c8ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "High-tech jogger pants with moisture-wicking",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Tech Black", "Sport Gray", "Performance Navy"],
    brand: "Tech Sport",
    rating: 4.4,
    reviews: 145,
    features: ["Tech Fabric", "Moisture Wicking", "Jogger"],
    icon: "👖",
    itemCount: "Tech",
  },
  {
    id: "kb6-14y-tr-006",
    name: "Sweatpants Comfort",
    price: "$26",
    image: "https://images.unsplash.com/photo-1668689517052-3ef175d8c8ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cozy sweatpants for ultimate comfort",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Gray", "Black", "Navy", "Heather"],
    brand: "Comfort Zone",
    rating: 4.7,
    reviews: 189,
    features: ["Sweatpants", "Ultimate Comfort", "Cozy"],
    icon: "👖",
    itemCount: "Comfort",
  },
  {
    id: "kb6-14y-tr-007",
    name: "Dress Pants Formal",
    price: "$36",
    image: "https://images.unsplash.com/photo-1668689517052-3ef175d8c8ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Formal dress pants for special occasions",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "Charcoal", "Dark Gray"],
    brand: "Formal Wear",
    rating: 4.3,
    reviews: 156,
    features: ["Formal Style", "Special Occasion", "Dress"],
    icon: "👖",
    itemCount: "Formal",
  },
  {
    id: "kb6-14y-tr-008",
    name: "Tactical Style Pants",
    price: "$34",
    image: "https://images.unsplash.com/photo-1668689517052-3ef175d8c8ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Tactical-inspired pants for outdoor adventures",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Tactical Green", "Combat Black", "Field Gray"],
    brand: "Tactical Gear",
    rating: 4.5,
    reviews: 123,
    features: ["Tactical Style", "Outdoor", "Adventure"],
    icon: "👖",
    itemCount: "Tactical",
  },
  {
    id: "kb6-14y-tr-009",
    name: "Elastic Waist Pants",
    price: "$29",
    image: "https://images.unsplash.com/photo-1668689517052-3ef175d8c8ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Comfortable pants with elastic waistband",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "Black", "Gray", "Khaki"],
    brand: "Easy Wear",
    rating: 4.6,
    reviews: 178,
    features: ["Elastic Waist", "Easy Wear", "Comfortable"],
    icon: "👖",
    itemCount: "Easy",
  },
  {
    id: "kb6-14y-tr-010",
    name: "Corduroy Classic Pants",
    price: "$31",
    image: "https://images.unsplash.com/photo-1668689517052-3ef175d8c8ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic corduroy pants for vintage style",
    category: "Trousers",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Brown Cord", "Navy Cord", "Gray Cord"],
    brand: "Vintage Style",
    rating: 4.4,
    reviews: 134,
    features: ["Corduroy Fabric", "Classic", "Vintage"],
    icon: "👖",
    itemCount: "Vintage",
  }
];

export function KidsBoys6To14YTrousersPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-green-50 via-blue-50 to-gray-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6-14Y Trousers Collection" 
          subtitle="Versatile & Comfortable Trousers for Growing Boys"
          products={kidsBoys6To14YTrousersProducts} 
        />
      </main>
    </div>
  );
}