import { ProductGrid } from "../ProductGrid";

const kidsGirls6To14YTShirtsProducts = [
  {
    id: "kg6-14y-t-001",
    name: "Unicorn Galaxy Tee",
    price: "$22",
    image: "https://images.unsplash.com/photo-1611428813653-aa606c998586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnaXJscyUyMGtpZHMlMjB0LXNoaXJ0fGVufDF8fHx8MTc1NTE5MDgxMnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Magical unicorn galaxy print t-shirt with glitter details",
    category: "T-Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Galaxy Purple", "Starry Pink", "Cosmic Blue"],
    brand: "Galaxy Dreams",
    rating: 4.9,
    reviews: 312,
    features: ["Unicorn Galaxy", "Glitter Details", "Magical"],
    icon: "👕",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6-14y-t-002",
    name: "Inspirational Quote Tee",
    price: "$20",
    image: "https://images.unsplash.com/photo-1611428813653-aa606c998586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Motivational t-shirt with inspiring quotes for girls",
    category: "T-Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Pink", "Purple", "Mint Green", "Coral"],
    brand: "Girl Power",
    rating: 4.7,
    reviews: 245,
    features: ["Inspirational Quotes", "Girl Power", "Motivational"],
    icon: "👕",
    itemCount: "Inspiring",
  },
  {
    id: "kg6-14y-t-003",
    name: "Tie-Dye Peace Tee",
    price: "$24",
    image: "https://images.unsplash.com/photo-1611428813653-aa606c998586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cool tie-dye t-shirt with peace symbol design",
    category: "T-Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Rainbow Tie-Dye", "Pink Tie-Dye", "Blue Tie-Dye"],
    brand: "Peace & Love",
    rating: 4.6,
    reviews: 189,
    features: ["Tie-Dye Pattern", "Peace Symbol", "Cool"],
    icon: "👕",
    itemCount: "Cool",
  },
  {
    id: "kg6-14y-t-004",
    name: "Cat Lover Graphic Tee",
    price: "$19",
    image: "https://images.unsplash.com/photo-1611428813653-aa606c998586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Adorable cat-themed graphic t-shirt for animal lovers",
    category: "T-Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Pink Cat", "Gray Cat", "White Cat", "Black Cat"],
    brand: "Animal Love",
    rating: 4.8,
    reviews: 234,
    features: ["Cat Graphics", "Animal Love", "Adorable"],
    icon: "👕",
    itemCount: "Cute",
  },
  {
    id: "kg6-14y-t-005",
    name: "Music Note Tee",
    price: "$21",
    image: "https://images.unsplash.com/photo-1611428813653-aa606c998586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Musical note design t-shirt for aspiring musicians",
    category: "T-Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Music Pink", "Note Purple", "Melody Blue"],
    brand: "Music Maker",
    rating: 4.5,
    reviews: 167,
    features: ["Musical Notes", "Music Theme", "Creative"],
    icon: "👕",
    itemCount: "Musical",
  },
  {
    id: "kg6-14y-t-006",
    name: "Butterfly Dreams Tee",
    price: "$23",
    image: "https://images.unsplash.com/photo-1611428813653-aa606c998586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Beautiful butterfly print t-shirt with sparkle accents",
    category: "T-Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Butterfly Pink", "Garden Blue", "Nature Green"],
    brand: "Flutter Dreams",
    rating: 4.7,
    reviews: 198,
    features: ["Butterfly Print", "Sparkle Accents", "Beautiful"],
    icon: "👕",
    itemCount: "Nature",
  },
  {
    id: "kg6-14y-t-007",
    name: "Mermaid Scales Tee",
    price: "$25",
    image: "https://images.unsplash.com/photo-1611428813653-aa606c998586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Shimmery mermaid scale print t-shirt",
    category: "T-Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Mermaid Teal", "Ocean Blue", "Seafoam Green"],
    brand: "Ocean Dreams",
    rating: 4.6,
    reviews: 156,
    features: ["Mermaid Scales", "Shimmery", "Ocean Theme"],
    icon: "👕",
    itemCount: "Ocean",
  },
  {
    id: "kg6-14y-t-008",
    name: "Space Explorer Tee",
    price: "$22",
    image: "https://images.unsplash.com/photo-1611428813653-aa606c998586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cosmic space-themed t-shirt with planet graphics",
    category: "T-Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Space Navy", "Cosmic Purple", "Galaxy Black"],
    brand: "Space Girls",
    rating: 4.4,
    reviews: 145,
    features: ["Space Theme", "Planet Graphics", "Cosmic"],
    icon: "👕",
    itemCount: "Space",
  },
  {
    id: "kg6-14y-t-009",
    name: "Rainbow Heart Tee",
    price: "$20",
    image: "https://images.unsplash.com/photo-1611428813653-aa606c998586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Colorful rainbow heart design t-shirt",
    category: "T-Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Rainbow Heart", "Pink Heart", "Purple Heart"],
    brand: "Rainbow Love",
    rating: 4.5,
    reviews: 178,
    features: ["Rainbow Hearts", "Colorful", "Love Theme"],
    icon: "👕",
    itemCount: "Colorful",
  },
  {
    id: "kg6-14y-t-010",
    name: "Future Scientist Tee",
    price: "$21",
    image: "https://images.unsplash.com/photo-1611428813653-aa606c998586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Empowering science-themed t-shirt for future scientists",
    category: "T-Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Science Blue", "Lab Pink", "Chemistry Purple"],
    brand: "Future Leaders",
    rating: 4.8,
    reviews: 123,
    features: ["Science Theme", "Empowering", "Educational"],
    icon: "👕",
    itemCount: "Science",
  }
];

export function KidsGirls6To14YTShirtsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-purple-50 via-pink-50 to-blue-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6-14Y T-Shirts Collection" 
          subtitle="Fun & Empowering Tees for Creative Girls"
          products={kidsGirls6To14YTShirtsProducts} 
        />
      </main>
    </div>
  );
}