import { ProductGrid } from "../ProductGrid";

const kidsGirls6M5YTShirtsProducts = [
  {
    id: "kg6m5y-t-001",
    name: "Princess Sparkle Tee",
    price: "$18",
    image: "https://images.unsplash.com/photo-1662916269397-3c1a71515735?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b2RkbGVyJTIwZ2lybCUyMGRyZXNzfGVufDF8fHx8MTc1NTE4OTczN3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Magical princess t-shirt with glitter details",
    category: "T-Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Purple", "White", "Lavender"],
    brand: "Little Princess",
    rating: 4.9,
    reviews: 298,
    features: ["Glitter Details", "Princess Theme", "Soft Cotton"],
    icon: "👕",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6m5y-t-002",
    name: "Unicorn Rainbow Tee",
    price: "$16",
    image: "https://images.unsplash.com/photo-1662916269397-3c1a71515735?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Magical unicorn design with rainbow colors",
    category: "T-Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Rainbow", "Pink", "Purple", "White"],
    brand: "Unicorn Magic",
    rating: 4.8,
    reviews: 234,
    features: ["Unicorn Design", "Rainbow Colors", "Magical"],
    icon: "👕",
    itemCount: "Magical",
  },
  {
    id: "kg6m5y-t-003",
    name: "Butterfly Garden Tee",
    price: "$15",
    image: "https://images.unsplash.com/photo-1662916269397-3c1a71515735?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Beautiful butterfly print with garden flowers",
    category: "T-Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Yellow", "Green", "Purple"],
    brand: "Garden Party",
    rating: 4.7,
    reviews: 189,
    features: ["Butterfly Print", "Garden Theme", "Colorful"],
    icon: "👕",
    itemCount: "Nature",
  },
  {
    id: "kg6m5y-t-004",
    name: "Mermaid Tail Tee",
    price: "$17",
    image: "https://images.unsplash.com/photo-1662916269397-3c1a71515735?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Shimmery mermaid design for ocean lovers",
    category: "T-Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Turquoise", "Purple", "Pink", "Green"],
    brand: "Ocean Dreams",
    rating: 4.6,
    reviews: 167,
    features: ["Mermaid Theme", "Shimmer Details", "Ocean Inspired"],
    icon: "👕",
    itemCount: "Ocean",
  },
  {
    id: "kg6m5y-t-005",
    name: "Flower Power Tee",
    price: "$14",
    image: "https://images.unsplash.com/photo-1662916269397-3c1a71515735?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cute flower patterns in bright spring colors",
    category: "T-Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Yellow", "Orange", "Red"],
    brand: "Spring Bloom",
    rating: 4.5,
    reviews: 145,
    features: ["Flower Print", "Spring Colors", "Cheerful"],
    icon: "👕",
    itemCount: "Spring",
  },
  {
    id: "kg6m5y-t-006",
    name: "Cat & Kitten Tee",
    price: "$16",
    image: "https://images.unsplash.com/photo-1662916269397-3c1a71515735?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Adorable kitten graphics with paw prints",
    category: "T-Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Gray", "White", "Purple"],
    brand: "Kitty Club",
    rating: 4.7,
    reviews: 178,
    features: ["Kitten Graphics", "Paw Prints", "Adorable"],
    icon: "👕",
    itemCount: "Pets",
  },
  {
    id: "kg6m5y-t-007",
    name: "Ice Cream Party Tee",
    price: "$15",
    image: "https://images.unsplash.com/photo-1662916269397-3c1a71515735?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sweet ice cream cone design with rainbow sprinkles",
    category: "T-Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Mint", "Yellow", "White"],
    brand: "Sweet Treats",
    rating: 4.4,
    reviews: 123,
    features: ["Ice Cream Design", "Sweet Theme", "Fun Colors"],
    icon: "👕",
    itemCount: "Sweet",
  },
  {
    id: "kg6m5y-t-008",
    name: "Rainbow Hearts Tee",
    price: "$13",
    image: "https://images.unsplash.com/photo-1662916269397-3c1a71515735?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Colorful heart pattern spreading love and joy",
    category: "T-Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Multi", "Pink", "Purple", "Red"],
    brand: "Love & Joy",
    rating: 4.3,
    reviews: 98,
    features: ["Heart Pattern", "Rainbow Colors", "Loving"],
    icon: "👕",
    itemCount: "Love",
  },
  {
    id: "kg6m5y-t-009",
    name: "Ballerina Dreams Tee",
    price: "$19",
    image: "https://images.unsplash.com/photo-1662916269397-3c1a71515735?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant ballerina silhouette with tutu details",
    category: "T-Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Lavender", "White", "Rose"],
    brand: "Dance Dreams",
    rating: 4.8,
    reviews: 156,
    features: ["Ballerina Theme", "Tutu Details", "Elegant"],
    icon: "👕",
    itemCount: "Dance",
  },
  {
    id: "kg6m5y-t-010",
    name: "Sunshine Smile Tee",
    price: "$14",
    image: "https://images.unsplash.com/photo-1662916269397-3c1a71515735?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Happy sunshine design with smiley face details",
    category: "T-Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Yellow", "Orange", "Pink", "White"],
    brand: "Happy Days",
    rating: 4.5,
    reviews: 134,
    features: ["Sunshine Theme", "Smiley Face", "Happy"],
    icon: "👕",
    itemCount: "Happy",
  }
];

export function KidsGirls6M5YTShirtsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-pink-50 via-purple-50 to-yellow-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6M-5Y T-Shirts Collection" 
          subtitle="Adorable & Colorful Tees for Little Princesses"
          products={kidsGirls6M5YTShirtsProducts} 
        />
      </main>
    </div>
  );
}