import { ProductGrid } from "../ProductGrid";

const kidsBoys6To14YCoordSetsProducts = [
  {
    id: "kb6-14y-cs-001",
    name: "Athletic Sport Set",
    price: "$45",
    image: "https://i.pinimg.com/736x/41/a0/49/41a0494f2388911559d5ff728be9cc09.jpg",
    description: "Performance athletic set for active boys",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Athletic Black", "Sport Navy", "Team Red", "Blue"],
    brand: "Athletic Pro",
    rating: 4.8,
    reviews: 234,
    features: ["Athletic Performance", "Sport Set", "Active"],
    icon: "👕",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6-14y-cs-002",
    name: "Gaming Champion Set",
    price: "$38",
    image: "https://i.pinimg.com/1200x/60/eb/70/60eb703760ace953d75ff44438ca7500.jpg",
    description: "Cool gaming-themed coordinate set",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Gaming Black", "Controller Gray", "Pixel Blue"],
    brand: "Game Master",
    rating: 4.7,
    reviews: 189,
    features: ["Gaming Theme", "Cool Graphics", "Champion"],
    icon: "👕",
    itemCount: "Gaming",
  },
  {
    id: "kb6-14y-cs-003",
    name: "Urban Street Set",
    price: "$42",
    image: "https://i.pinimg.com/736x/7d/b9/fa/7db9faa4ca25f871c35cae1db5bb649c.jpg",
    description: "Trendy urban street style coordinate set",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Street Black", "Urban Gray", "City Navy"],
    brand: "Street Style",
    rating: 4.6,
    reviews: 167,
    features: ["Urban Style", "Street Fashion", "Trendy"],
    icon: "👕",
    itemCount: "Urban",
  },
  {
    id: "kb6-14y-cs-004",
    name: "Skateboard Cool Set",
    price: "$40",
    image: "https://i.pinimg.com/736x/1f/68/93/1f6893b83dc2d8f8eef44c1d9d2015f3.jpg",
    description: "Skateboard-inspired coordinate set for cool kids",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Skate Black", "Board Gray", "Wheel Navy"],
    brand: "Skate Cool",
    rating: 4.5,
    reviews: 145,
    features: ["Skateboard Style", "Cool Design", "Street"],
    icon: "👕",
    itemCount: "Skate",
  },
  {
    id: "kb6-14y-cs-005",
    name: "Space Explorer Set",
    price: "$41",
    image: "https://i.pinimg.com/1200x/c9/63/01/c96301f17ae43b5873c9716bc59f0307.jpg",
    description: "Cosmic space-themed coordinate set",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Space Navy", "Galaxy Black", "Cosmic Blue"],
    brand: "Space Explorer",
    rating: 4.7,
    reviews: 198,
    features: ["Space Theme", "Explorer Style", "Cosmic"],
    icon: "👕",
    itemCount: "Space",
  },
  {
    id: "kb6-14y-cs-006",
    name: "Soccer Champion Set",
    price: "$43",
    image: "https://i.pinimg.com/736x/9a/40/aa/9a40aab4643d6b60db80a23eb2ca857b.jpg",
    description: "Professional soccer coordinate set for young athletes",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Soccer Blue", "Team Red", "Goal Green"],
    brand: "Soccer Pro",
    rating: 4.6,
    reviews: 156,
    features: ["Soccer Theme", "Athletic", "Champion"],
    icon: "👕",
    itemCount: "Soccer",
  },
  {
    id: "kb6-14y-cs-007",
    name: "Denim Casual Set",
    price: "$46",
    image: "https://i.pinimg.com/736x/98/c4/01/98c401493f2c9454acaae42676c755ee.jpg",
    description: "Classic denim coordinate set for casual style",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Denim Style",
    rating: 4.4,
    reviews: 123,
    features: ["Denim Style", "Casual", "Classic"],
    icon: "👕",
    itemCount: "Denim",
  },
  {
    id: "kb6-14y-cs-008",
    name: "Tech Warrior Set",
    price: "$44",
    image: "https://i.pinimg.com/736x/ca/a3/af/caa3afceda5f23796261efa6c9aa01aa.jpg",
    description: "High-tech warrior-themed coordinate set",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Tech Black", "Warrior Gray", "Digital Blue"],
    brand: "Tech Warrior",
    rating: 4.5,
    reviews: 178,
    features: ["Tech Theme", "Warrior Style", "Digital"],
    icon: "👕",
    itemCount: "Tech",
  },
];

export function KidsBoys6To14YCoordSetsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-green-50 to-gray-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6-14Y Co-Ord Sets Collection" 
          subtitle="Cool & Coordinated Outfits for Active Boys"
          products={kidsBoys6To14YCoordSetsProducts} 
        />
      </main>
    </div>
  );
}