import { ProductGrid } from "../ProductGrid";

const kidsGirls6M5YTrousersProducts = [
  {
    id: "kg6m5y-tr-001",
    name: "Princess Leggings",
    price: "$18",
    image: "https://images.unsplash.com/photo-1748107098323-a0419f973a91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b2RkbGVyJTIwZ2lybCUyMHRyb3VzZXJzfGVufDF8fHx8MTc1NTE5MDc0M3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Soft and stretchy princess-themed leggings",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Purple", "White", "Lavender"],
    brand: "Princess Collection",
    rating: 4.8,
    reviews: 267,
    features: ["Princess Theme", "Stretchy", "Soft Fabric"],
    icon: "👖",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6m5y-tr-002",
    name: "Floral Print Pants",
    price: "$22",
    image: "https://images.unsplash.com/photo-1748107098323-a0419f973a91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Beautiful floral print pants perfect for spring",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink Floral", "Blue Floral", "Yellow Floral"],
    brand: "Spring Bloom",
    rating: 4.7,
    reviews: 198,
    features: ["Floral Print", "Spring Ready", "Beautiful"],
    icon: "👖",
    itemCount: "Floral",
  },
  {
    id: "kg6m5y-tr-003",
    name: "Velvet Dress Pants",
    price: "$26",
    image: "https://images.unsplash.com/photo-1748107098323-a0419f973a91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant velvet pants for special occasions",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy Velvet", "Burgundy", "Black", "Pink"],
    brand: "Velvet Dreams",
    rating: 4.6,
    reviews: 156,
    features: ["Velvet Fabric", "Special Occasion", "Elegant"],
    icon: "👖",
    itemCount: "Elegant",
  },
  {
    id: "kg6m5y-tr-004",
    name: "Cotton Comfort Pants",
    price: "$20",
    image: "https://images.unsplash.com/photo-1748107098323-a0419f973a91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Breathable cotton pants for everyday comfort",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["White", "Cream", "Light Pink", "Sky Blue"],
    brand: "Cotton Cloud",
    rating: 4.5,
    reviews: 234,
    features: ["Cotton Fabric", "Breathable", "Everyday Wear"],
    icon: "👖",
    itemCount: "Comfort",
  },
  {
    id: "kg6m5y-tr-005",
    name: "Rainbow Stripe Leggings",
    price: "$17",
    image: "https://images.unsplash.com/photo-1748107098323-a0419f973a91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Fun rainbow striped leggings for playful days",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Rainbow Stripe", "Pastel Rainbow", "Bright Rainbow"],
    brand: "Rainbow Kids",
    rating: 4.4,
    reviews: 145,
    features: ["Rainbow Stripes", "Playful", "Fun Colors"],
    icon: "👖",
    itemCount: "Rainbow",
  },
  {
    id: "kg6m5y-tr-006",
    name: "Lace Trim Pants",
    price: "$24",
    image: "https://images.unsplash.com/photo-1748107098323-a0419f973a91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Adorable pants with delicate lace trim details",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["White", "Pink", "Cream", "Lavender"],
    brand: "Lace & Grace",
    rating: 4.7,
    reviews: 167,
    features: ["Lace Trim", "Delicate Details", "Adorable"],
    icon: "👖",
    itemCount: "Lace",
  },
  {
    id: "kg6m5y-tr-007",
    name: "Polka Dot Leggings",
    price: "$19",
    image: "https://images.unsplash.com/photo-1748107098323-a0419f973a91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic polka dot leggings with vintage charm",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink Dots", "Navy Dots", "Red Dots"],
    brand: "Polka Vintage",
    rating: 4.3,
    reviews: 123,
    features: ["Polka Dots", "Vintage Style", "Classic"],
    icon: "👖",
    itemCount: "Vintage",
  },
  {
    id: "kg6m5y-tr-008",
    name: "Unicorn Magic Pants",
    price: "$25",
    image: "https://images.unsplash.com/photo-1748107098323-a0419f973a91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Magical unicorn-themed pants with sparkly details",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Unicorn Pink", "Rainbow", "White", "Purple"],
    brand: "Unicorn Magic",
    rating: 4.8,
    reviews: 189,
    features: ["Unicorn Theme", "Sparkly Details", "Magical"],
    icon: "👖",
    itemCount: "Magical",
  },
  {
    id: "kg6m5y-tr-009",
    name: "Corduroy Play Pants",
    price: "$23",
    image: "https://images.unsplash.com/photo-1748107098323-a0419f973a91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cozy corduroy pants perfect for autumn play",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink Cord", "Brown Cord", "Navy Cord"],
    brand: "Corduroy Kids",
    rating: 4.5,
    reviews: 134,
    features: ["Corduroy Fabric", "Cozy", "Autumn Ready"],
    icon: "👖",
    itemCount: "Cozy",
  },
  {
    id: "kg6m5y-tr-010",
    name: "Tulle Bottom Pants",
    price: "$27",
    image: "https://images.unsplash.com/photo-1748107098323-a0419f973a91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Unique pants with tulle hem for ballerina vibes",
    category: "Trousers",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink Tulle", "White Tulle", "Lavender Tulle"],
    brand: "Ballerina Dreams",
    rating: 4.6,
    reviews: 178,
    features: ["Tulle Hem", "Ballerina Style", "Unique"],
    icon: "👖",
    itemCount: "Ballerina",
  }
];

export function KidsGirls6M5YTrousersPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-purple-50 via-pink-50 to-yellow-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6M-5Y Trousers Collection" 
          subtitle="Comfortable & Pretty Trousers for Little Princesses"
          products={kidsGirls6M5YTrousersProducts} 
        />
      </main>
    </div>
  );
}