import { ProductGrid } from "../ProductGrid";

const kidsBoys6M5YShortsProducts = [
  {
    id: "kb6m5y-sh-001",
    name: "Adventure Explorer Shorts",
    price: "$18",
    image: "https://images.unsplash.com/photo-1627639678232-1d3bcbcc1042?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b2RkbGVyJTIwYm95JTIwc2hvcnRzfGVufDF8fHx8MTc1NTE5MDA2N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Comfortable cargo shorts perfect for playground adventures",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Khaki", "Navy", "Green", "Gray"],
    brand: "Little Explorer",
    rating: 4.8,
    reviews: 245,
    features: ["Cargo Pockets", "Adjustable Waist", "Durable"],
    icon: "🩳",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6m5y-sh-002",
    name: "Denim Play Shorts",
    price: "$22",
    image: "https://images.unsplash.com/photo-1627639678232-1d3bcbcc1042?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic denim shorts with toddler-friendly features",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Denim Kids",
    rating: 4.7,
    reviews: 189,
    features: ["Soft Denim", "Easy Snap", "Play Ready"],
    icon: "🩳",
    itemCount: "Classic",
  },
  {
    id: "kb6m5y-sh-003",
    name: "Summer Breeze Shorts",
    price: "$16",
    image: "https://images.unsplash.com/photo-1627639678232-1d3bcbcc1042?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Lightweight cotton shorts for hot summer days",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Sky Blue", "Sunshine Yellow", "Coral", "White"],
    brand: "Summer Days",
    rating: 4.6,
    reviews: 156,
    features: ["Lightweight", "Breathable", "Colorful"],
    icon: "🩳",
    itemCount: "Summer",
  },
  {
    id: "kb6m5y-sh-004",
    name: "Sports Team Shorts",
    price: "$20",
    image: "https://images.unsplash.com/photo-1627639678232-1d3bcbcc1042?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Athletic mesh shorts for active little boys",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Red", "Blue", "Green", "Black"],
    brand: "Mini Athletes",
    rating: 4.5,
    reviews: 123,
    features: ["Mesh Material", "Athletic Fit", "Team Colors"],
    icon: "🩳",
    itemCount: "Sports",
  },
  {
    id: "kb6m5y-sh-005",
    name: "Dinosaur Print Shorts",
    price: "$17",
    image: "https://images.unsplash.com/photo-1627639678232-1d3bcbcc1042?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Fun dinosaur-themed shorts for dino enthusiasts",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Green", "Blue", "Brown", "Orange"],
    brand: "Dino Adventures",
    rating: 4.7,
    reviews: 198,
    features: ["Dinosaur Print", "Soft Cotton", "Fun Design"],
    icon: "🩳",
    itemCount: "Adventure",
  },
  {
    id: "kb6m5y-sh-006",
    name: "Chino Style Shorts",
    price: "$24",
    image: "https://images.unsplash.com/photo-1627639678232-1d3bcbcc1042?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Smart casual chino shorts for special occasions",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Beige", "Navy", "Olive", "White"],
    brand: "Little Gentleman",
    rating: 4.4,
    reviews: 134,
    features: ["Chino Style", "Belt Loops", "Smart Casual"],
    icon: "🩳",
    itemCount: "Smart",
  },
  {
    id: "kb6m5y-sh-007",
    name: "Striped Beach Shorts",
    price: "$19",
    image: "https://images.unsplash.com/photo-1627639678232-1d3bcbcc1042?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Quick-dry striped shorts perfect for beach days",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy/White", "Red/White", "Blue/Gray"],
    brand: "Beach Babies",
    rating: 4.3,
    reviews: 167,
    features: ["Quick Dry", "Striped", "Beach Ready"],
    icon: "🩳",
    itemCount: "Beach",
  },
  {
    id: "kb6m5y-sh-008",
    name: "Safari Adventure Shorts",
    price: "$21",
    image: "https://images.unsplash.com/photo-1627639678232-1d3bcbcc1042?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Explorer-style shorts with multiple pockets",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Safari Tan", "Olive Green", "Khaki"],
    brand: "Safari Kids",
    rating: 4.6,
    reviews: 145,
    features: ["Multiple Pockets", "Safari Style", "Durable"],
    icon: "🩳",
    itemCount: "Explorer",
  },
  {
    id: "kb6m5y-sh-009",
    name: "Rainbow Stripe Shorts",
    price: "$15",
    image: "https://images.unsplash.com/photo-1627639678232-1d3bcbcc1042?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Colorful rainbow striped shorts for playful days",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Rainbow", "Bright Stripes", "Pastel Rainbow"],
    brand: "Rainbow Kids",
    rating: 4.5,
    reviews: 112,
    features: ["Rainbow Stripes", "Bright Colors", "Playful"],
    icon: "🩳",
    itemCount: "Colorful",
  },
  {
    id: "kb6m5y-sh-010",
    name: "Comfy Knit Shorts",
    price: "$14",
    image: "https://images.unsplash.com/photo-1627639678232-1d3bcbcc1042?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Super soft knit shorts for all-day comfort",
    category: "Shorts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Gray", "Navy", "Cream", "Light Blue"],
    brand: "Comfort Zone",
    rating: 4.4,
    reviews: 178,
    features: ["Knit Fabric", "Super Soft", "Comfortable"],
    icon: "🩳",
    itemCount: "Comfort",
  }
];

export function KidsBoys6M5YShortsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-cyan-50 to-green-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6M-5Y Shorts Collection" 
          subtitle="Comfortable & Fun Shorts for Active Little Boys"
          products={kidsBoys6M5YShortsProducts} 
        />
      </main>
    </div>
  );
}