import { ProductGrid } from "../ProductGrid";

const kidsGirls6To14YShirtsProducts = [
  {
    id: "kg6-14y-s-001",
    name: "School Button-Down Shirt",
    price: "$28",
    image: "https://images.unsplash.com/photo-1625517527341-1e57d526612d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnaXJscyUyMGtpZHMlMjBzaGlydCUyMGJsb3VzZXxlbnwxfHx8fDE3NTUxOTA4MDl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Classic school uniform button-down shirt",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Light Blue", "Pink", "Navy"],
    brand: "School Essential",
    rating: 4.8,
    reviews: 289,
    features: ["School Uniform", "Button-Down", "Professional"],
    icon: "👚",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6-14y-s-002",
    name: "Floral Print Blouse",
    price: "$32",
    image: "https://images.unsplash.com/photo-1625517527341-1e57d526612d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Pretty floral print blouse for special occasions",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Pink Floral", "Blue Floral", "Purple Floral"],
    brand: "Flower Garden",
    rating: 4.7,
    reviews: 234,
    features: ["Floral Print", "Special Occasion", "Pretty"],
    icon: "👚",
    itemCount: "Floral",
  },
  {
    id: "kg6-14y-s-003",
    name: "Denim Shirt Jacket",
    price: "$36",
    image: "https://images.unsplash.com/photo-1625517527341-1e57d526612d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy denim shirt that doubles as a light jacket",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Denim Style",
    rating: 4.6,
    reviews: 198,
    features: ["Denim Fabric", "Versatile", "Trendy"],
    icon: "👚",
    itemCount: "Denim",
  },
  {
    id: "kg6-14y-s-004",
    name: "Ruffle Sleeve Blouse",
    price: "$30",
    image: "https://images.unsplash.com/photo-1625517527341-1e57d526612d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant blouse with beautiful ruffle sleeve details",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Pink", "Lavender", "Cream"],
    brand: "Ruffle Romance",
    rating: 4.5,
    reviews: 167,
    features: ["Ruffle Sleeves", "Elegant", "Beautiful"],
    icon: "👚",
    itemCount: "Elegant",
  },
  {
    id: "kg6-14y-s-005",
    name: "Striped Casual Shirt",
    price: "$26",
    image: "https://images.unsplash.com/photo-1625517527341-1e57d526612d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic striped shirt perfect for casual wear",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy Stripe", "Pink Stripe", "Blue Stripe"],
    brand: "Stripe Style",
    rating: 4.4,
    reviews: 145,
    features: ["Striped Pattern", "Casual", "Classic"],
    icon: "👚",
    itemCount: "Casual",
  },
  {
    id: "kg6-14y-s-006",
    name: "Lace Collar Shirt",
    price: "$34",
    image: "https://images.unsplash.com/photo-1625517527341-1e57d526612d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sophisticated shirt with delicate lace collar",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Cream", "Light Pink"],
    brand: "Lace Elegance",
    rating: 4.7,
    reviews: 189,
    features: ["Lace Collar", "Sophisticated", "Delicate"],
    icon: "👚",
    itemCount: "Sophisticated",
  },
  {
    id: "kg6-14y-s-007",
    name: "Tie-Front Blouse",
    price: "$29",
    image: "https://images.unsplash.com/photo-1625517527341-1e57d526612d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy tie-front blouse for fashionable girls",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Pink", "Navy", "Coral"],
    brand: "Fashion Forward",
    rating: 4.3,
    reviews: 156,
    features: ["Tie-Front", "Trendy", "Fashionable"],
    icon: "👚",
    itemCount: "Trendy",
  },
  {
    id: "kg6-14y-s-008",
    name: "Peasant Style Blouse",
    price: "$31",
    image: "https://images.unsplash.com/photo-1625517527341-1e57d526612d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Bohemian peasant-style blouse with embroidered details",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Cream", "Sage Green", "Dusty Pink"],
    brand: "Boho Chic",
    rating: 4.6,
    reviews: 123,
    features: ["Peasant Style", "Embroidered", "Bohemian"],
    icon: "👚",
    itemCount: "Boho",
  },
  {
    id: "kg6-14y-s-009",
    name: "Peter Pan Collar Shirt",
    price: "$27",
    image: "https://images.unsplash.com/photo-1625517527341-1e57d526612d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sweet shirt with classic Peter Pan collar",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Pink", "Light Blue", "Yellow"],
    brand: "Sweet Collar",
    rating: 4.5,
    reviews: 178,
    features: ["Peter Pan Collar", "Sweet", "Classic"],
    icon: "👚",
    itemCount: "Sweet",
  },
  {
    id: "kg6-14y-s-010",
    name: "Checkered School Shirt",
    price: "$25",
    image: "https://images.unsplash.com/photo-1625517527341-1e57d526612d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic checkered pattern perfect for school",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Red Check", "Blue Check", "Green Check"],
    brand: "School Check",
    rating: 4.4,
    reviews: 134,
    features: ["Checkered Pattern", "School Ready", "Classic"],
    icon: "👚",
    itemCount: "School",
  }
];

export function KidsGirls6To14YShirtsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-pink-50 via-purple-50 to-blue-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6-14Y Shirts Collection" 
          subtitle="Stylish & Smart Shirts for Growing Girls"
          products={kidsGirls6To14YShirtsProducts} 
        />
      </main>
    </div>
  );
}