import { ProductGrid } from "../ProductGrid";

const kidsGirls6To14YJeansProducts = [
  {
    id: "kg6-14y-j-001",
    name: "Skinny Fit Teen Jeans",
    price: "$36",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnaXJscyUyMGtpZHMlMjBqZWFucyUyMGRlbmltfGVufDF8fHx8MTc1NTE5MTMxMHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Trendy skinny fit jeans perfect for teen style",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Dark Blue", "Medium Blue", "Black", "Light Blue"],
    brand: "Teen Denim",
    rating: 4.8,
    reviews: 289,
    features: ["Skinny Fit", "Teen Style", "Trendy"],
    icon: "👖",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6-14y-j-002",
    name: "High-Waisted Mom Jeans",
    price: "$38",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Vintage-inspired high-waisted mom jeans",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Vintage Blue", "Light Wash", "Medium Wash"],
    brand: "Vintage Mom",
    rating: 4.7,
    reviews: 234,
    features: ["High-Waisted", "Mom Jeans", "Vintage"],
    icon: "👖",
    itemCount: "Vintage",
  },
  {
    id: "kg6-14y-j-003",
    name: "Distressed Ripped Jeans",
    price: "$34",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Edgy distressed jeans with stylish rips",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Light Distressed", "Medium Distressed", "Dark Distressed"],
    brand: "Edgy Denim",
    rating: 4.6,
    reviews: 198,
    features: ["Distressed Style", "Ripped Details", "Edgy"],
    icon: "👖",
    itemCount: "Edgy",
  },
  {
    id: "kg6-14y-j-004",
    name: "Straight Leg Classic Jeans",
    price: "$32",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic straight leg jeans for versatile wear",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Classic Blue", "Dark Navy", "Medium Blue"],
    brand: "Classic Straight",
    rating: 4.5,
    reviews: 167,
    features: ["Straight Leg", "Classic Fit", "Versatile"],
    icon: "👖",
    itemCount: "Classic",
  },
  {
    id: "kg6-14y-j-005",
    name: "Embroidered Boho Jeans",
    price: "$40",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Bohemian jeans with beautiful embroidered details",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Boho Blue", "Embroidered Light", "Floral Denim"],
    brand: "Boho Chic",
    rating: 4.7,
    reviews: 156,
    features: ["Embroidered Details", "Boho Style", "Beautiful"],
    icon: "👖",
    itemCount: "Boho",
  },
  {
    id: "kg6-14y-j-006",
    name: "Cropped Ankle Jeans",
    price: "$35",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Stylish cropped jeans that hit at the ankle",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Light Crop", "Medium Crop", "Dark Crop"],
    brand: "Cropped Style",
    rating: 4.4,
    reviews: 145,
    features: ["Cropped Length", "Ankle Cut", "Stylish"],
    icon: "👖",
    itemCount: "Stylish",
  },
  {
    id: "kg6-14y-j-007",
    name: "Wide Leg Flare Jeans",
    price: "$37",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Retro-inspired wide leg flare jeans",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Retro Blue", "Flare Light", "Wide Dark"],
    brand: "Retro Flare",
    rating: 4.6,
    reviews: 123,
    features: ["Wide Leg", "Flare Style", "Retro"],
    icon: "👖",
    itemCount: "Retro",
  },
  {
    id: "kg6-14y-j-008",
    name: "Stretch Comfort Jeans",
    price: "$33",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Super comfortable stretch jeans for all-day wear",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Stretch Blue", "Comfort Dark", "Soft Medium"],
    brand: "Comfort Stretch",
    rating: 4.8,
    reviews: 178,
    features: ["Stretch Fabric", "All-Day Comfort", "Flexible"],
    icon: "👖",
    itemCount: "Comfort",
  },
  {
    id: "kg6-14y-j-009",
    name: "Color-Washed Jeans",
    price: "$39",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy color-washed jeans in fun hues",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Pink Wash", "Purple Wash", "Green Wash"],
    brand: "Color Wash",
    rating: 4.5,
    reviews: 134,
    features: ["Color Wash", "Fun Colors", "Trendy"],
    icon: "👖",
    itemCount: "Colorful",
  },
  {
    id: "kg6-14y-j-010",
    name: "Patchwork Designer Jeans",
    price: "$42",
    image: "https://images.unsplash.com/photo-1621783014861-dc6ef309bd05?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Unique patchwork jeans with designer details",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Patchwork Blue", "Designer Mixed", "Artistic Denim"],
    brand: "Designer Patch",
    rating: 4.7,
    reviews: 189,
    features: ["Patchwork Design", "Designer Details", "Unique"],
    icon: "👖",
    itemCount: "Designer",
  }
];

export function KidsGirls6To14YJeansPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6-14Y Jeans Collection" 
          subtitle="Trendy & Cool Jeans for Fashion-Forward Girls"
          products={kidsGirls6To14YJeansProducts} 
        />
      </main>
    </div>
  );
}