import { ProductGrid } from "../ProductGrid";

const kidsGirls6M5YShortsAndSkirtsProducts = [
  {
    id: "kg6m5y-ss-001",
    name: "Tutu Skirt Set",
    price: "$26",
    image: "https://images.unsplash.com/photo-1630472440989-173583fd9790?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxraWRzJTIwZ2lybCUyMHNob3J0c3xlbnwxfHx8fDE3NTUxOTAyMTB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Magical tutu skirt perfect for twirling and dancing",
    category: "Shorts & Skirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Purple", "White", "Rainbow"],
    brand: "Ballerina Dreams",
    rating: 4.9,
    reviews: 287,
    features: ["Tutu Style", "Dancing", "Magical"],
    icon: "🩳",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6m5y-ss-002",
    name: "Denim Shorts",
    price: "$20",
    image: "https://images.unsplash.com/photo-1630472440989-173583fd9790?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic denim shorts with cute pocket details",
    category: "Shorts & Skirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Denim", "Medium Denim", "White Denim"],
    brand: "Denim Darling",
    rating: 4.7,
    reviews: 234,
    features: ["Denim Fabric", "Pocket Details", "Classic"],
    icon: "🩳",
    itemCount: "Classic",
  },
  {
    id: "kg6m5y-ss-003",
    name: "Pleated Mini Skirt",
    price: "$22",
    image: "https://images.unsplash.com/photo-1630472440989-173583fd9790?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Adorable pleated skirt perfect for school or play",
    category: "Shorts & Skirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy", "Gray", "Pink", "White"],
    brand: "School Girl",
    rating: 4.6,
    reviews: 189,
    features: ["Pleated Style", "School Ready", "Adorable"],
    icon: "🩳",
    itemCount: "School",
  },
  {
    id: "kg6m5y-ss-004",
    name: "Floral Bloom Shorts",
    price: "$18",
    image: "https://images.unsplash.com/photo-1630472440989-173583fd9790?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Pretty floral shorts perfect for summer adventures",
    category: "Shorts & Skirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink Floral", "Blue Floral", "Yellow Floral"],
    brand: "Flower Power",
    rating: 4.5,
    reviews: 156,
    features: ["Floral Print", "Summer Ready", "Pretty"],
    icon: "🩳",
    itemCount: "Floral",
  },
  {
    id: "kg6m5y-ss-005",
    name: "Polka Dot Skirt",
    price: "$21",
    image: "https://images.unsplash.com/photo-1630472440989-173583fd9790?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic polka dot skirt with vintage appeal",
    category: "Shorts & Skirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Red/White", "Navy/White", "Pink/White"],
    brand: "Vintage Dots",
    rating: 4.4,
    reviews: 123,
    features: ["Polka Dots", "Vintage Style", "Classic"],
    icon: "🩳",
    itemCount: "Vintage",
  },
  {
    id: "kg6m5y-ss-006",
    name: "Athletic Play Shorts",
    price: "$16",
    image: "https://images.unsplash.com/photo-1630472440989-173583fd9790?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Comfortable athletic shorts for active little girls",
    category: "Shorts & Skirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Purple", "Mint", "Coral"],
    brand: "Active Girls",
    rating: 4.3,
    reviews: 167,
    features: ["Athletic Style", "Comfortable", "Active"],
    icon: "🩳",
    itemCount: "Active",
  },
  {
    id: "kg6m5y-ss-007",
    name: "Unicorn Skirt",
    price: "$28",
    image: "https://images.unsplash.com/photo-1630472440989-173583fd9790?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Magical unicorn-themed skirt with sparkle details",
    category: "Shorts & Skirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Unicorn Rainbow", "Pink", "Purple", "White"],
    brand: "Unicorn Magic",
    rating: 4.8,
    reviews: 198,
    features: ["Unicorn Theme", "Sparkle Details", "Magical"],
    icon: "🩳",
    itemCount: "Magical",
  },
  {
    id: "kg6m5y-ss-008",
    name: "Ruffled Tier Skirt",
    price: "$24",
    image: "https://images.unsplash.com/photo-1630472440989-173583fd9790?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sweet tiered skirt with ruffled layers",
    category: "Shorts & Skirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Lavender", "Yellow", "White"],
    brand: "Sweet Ruffles",
    rating: 4.6,
    reviews: 145,
    features: ["Tiered Style", "Ruffled", "Sweet"],
    icon: "🩳",
    itemCount: "Sweet",
  },
  {
    id: "kg6m5y-ss-009",
    name: "Beach Shorts Set",
    price: "$19",
    image: "https://images.unsplash.com/photo-1630472440989-173583fd9790?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Quick-dry beach shorts with tropical prints",
    category: "Shorts & Skirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Tropical Pink", "Ocean Blue", "Sunset Orange"],
    brand: "Beach Babies",
    rating: 4.4,
    reviews: 134,
    features: ["Quick Dry", "Tropical Print", "Beach Ready"],
    icon: "🩳",
    itemCount: "Beach",
  },
  {
    id: "kg6m5y-ss-010",
    name: "Striped Circle Skirt",
    price: "$23",
    image: "https://images.unsplash.com/photo-1630472440989-173583fd9790?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Fun striped circle skirt perfect for spinning",
    category: "Shorts & Skirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink Stripe", "Blue Stripe", "Rainbow Stripe"],
    brand: "Spin & Twirl",
    rating: 4.5,
    reviews: 178,
    features: ["Circle Skirt", "Striped", "Spinning Fun"],
    icon: "🩳",
    itemCount: "Fun",
  }
];

export function KidsGirls6M5YShortsAndSkirtsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-pink-50 via-purple-50 to-yellow-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6M-5Y Shorts & Skirts Collection" 
          subtitle="Fun & Fashionable Bottoms for Little Princesses"
          products={kidsGirls6M5YShortsAndSkirtsProducts} 
        />
      </main>
    </div>
  );
}