import { ProductGrid } from "../ProductGrid";

const kidsBoys6M5YJeansProducts = [
  {
    id: "kb6m5y-j-001",
    name: "Classic Blue Jeans",
    price: "$26",
    image: "https://i.pinimg.com/564x/0a/2e/ae/0a2eae4b2a0d3b7b0b0b0b0b0b0b0b0b.jpg",
    description: "Timeless classic blue jeans that never go out of style",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Blue", "Medium Blue", "Dark Blue"],
    brand: "Classic Denim",
    rating: 4.8,
    reviews: 267,
    features: ["Classic Cut", "Soft Denim", "Adjustable Waist"],
    icon: "👖",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6m5y-j-002",
    name: "Distressed Play Jeans",
    price: "$28",
    image: "https://i.pinimg.com/564x/1b/2e/ae/1b2eae4b2a0d3b7b0b0b0b0b0b0b0b0b.jpg",
    description: "Trendy distressed jeans for fashionable little boys",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Wash", "Medium Wash", "Dark Wash"],
    brand: "Trendy Tots",
    rating: 4.7,
    reviews: 198,
    features: ["Distressed Style", "Trendy Look", "Comfortable"],
    icon: "👖",
    itemCount: "Trendy",
  },
  {
    id: "kb6m5y-j-003",
    name: "Stretch Comfort Jeans",
    price: "$30",
    image: "https://i.pinimg.com/564x/2c/2e/ae/2c2eae4b2a0d3b7b0b0b0b0b0b0b0b0b.jpg",
    description: "Super stretchy jeans for active toddlers",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Medium Blue", "Dark Blue", "Black"],
    brand: "Flex Denim",
    rating: 4.6,
    reviews: 156,
    features: ["Stretch Fabric", "Active Fit", "Flexible"],
    icon: "👖",
    itemCount: "Stretch",
  },
  {
    id: "kb6m5y-j-004",
    name: "Straight Leg Jeans",
    price: "$25",
    image: "https://i.pinimg.com/564x/3d/2e/ae/3d2eae4b2a0d3b7b0b0b0b0b0b0b0b0b.jpg",
    description: "Classic straight leg cut perfect for everyday wear",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Blue", "Medium Blue", "Dark Blue"],
    brand: "Straight Style",
    rating: 4.5,
    reviews: 123,
    features: ["Straight Leg", "Classic Fit", "Versatile"],
    icon: "👖",
    itemCount: "Classic",
  },
  {
    id: "kb6m5y-j-005",
    name: "Relaxed Fit Jeans",
    price: "$27",
    image: "https://i.pinimg.com/564x/4e/2e/ae/4e2eae4b2a0d3b7b0b0b0b0b0b0b0b0b.jpg",
    description: "Roomy relaxed fit jeans for maximum comfort",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Medium Wash", "Dark Wash", "Stone Wash"],
    brand: "Relaxed Kids",
    rating: 4.4,
    reviews: 145,
    features: ["Relaxed Fit", "Roomy", "Comfortable"],
    icon: "👖",
    itemCount: "Relaxed",
  },
  {
    id: "kb6m5y-j-006",
    name: "Slim Fit Jeans",
    price: "$29",
    image: "https://i.pinimg.com/564x/5f/2e/ae/5f2eae4b2a0d3b7b0b0b0b0b0b0b0b0b.jpg",
    description: "Modern slim fit jeans for a contemporary look",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Dark Blue", "Black", "Gray"],
    brand: "Modern Kids",
    rating: 4.3,
    reviews: 167,
    features: ["Slim Fit", "Modern Style", "Contemporary"],
    icon: "👖",
    itemCount: "Modern",
  },
  {
    id: "kb6m5y-j-007",
    name: "Pull-On Jeggings",
    price: "$24",
    image: "https://i.pinimg.com/564x/6a/2e/ae/6a2eae4b2a0d3b7b0b0b0b0b0b0b0b0b.jpg",
    description: "Easy pull-on jeggings that look like jeans",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Medium Blue", "Dark Blue", "Black"],
    brand: "Easy Denim",
    rating: 4.6,
    reviews: 189,
    features: ["Pull-On Style", "Jeggings", "Easy Dressing"],
    icon: "👖",
    itemCount: "Easy",
  },
  {
    id: "kb6m5y-j-008",
    name: "Carpenter Jeans",
    price: "$31",
    image: "https://i.pinimg.com/564x/7b/2e/ae/7b2eae4b2a0d3b7b0b0b0b0b0b0b0b0b.jpg",
    description: "Utility-style carpenter jeans with tool loop details",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Medium Blue", "Dark Blue", "Stone Wash"],
    brand: "Builder Kids",
    rating: 4.5,
    reviews: 134,
    features: ["Carpenter Style", "Tool Loops", "Utility Look"],
    icon: "👖",
    itemCount: "Utility",
  },
  {
    id: "kb6m5y-j-009",
    name: "Bootcut Jeans",
    price: "$26",
    image: "https://i.pinimg.com/564x/8c/2e/ae/8c2eae4b2a0d3b7b0b0b0b0b0b0b0b0b.jpg",
    description: "Classic bootcut style jeans with slight flare",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Blue", "Medium Blue", "Dark Blue"],
    brand: "Boot Style",
    rating: 4.4,
    reviews: 112,
    features: ["Bootcut Style", "Slight Flare", "Classic Look"],
    icon: "👖",
    itemCount: "Bootcut",
  },
  {
    id: "kb6m5y-j-010",
    name: "Vintage Wash Jeans",
    price: "$28",
    image: "https://i.pinimg.com/564x/9d/2e/ae/9d2eae4b2a0d3b7b0b0b0b0b0b0b0b0b.jpg",
    description: "Vintage-inspired wash jeans with authentic look",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Vintage Blue", "Stone Wash", "Faded Blue"],
    brand: "Vintage Kids",
    rating: 4.7,
    reviews: 178,
    features: ["Vintage Wash", "Authentic Look", "Retro Style"],
    icon: "👖",
    itemCount: "Vintage",
  }
];

export function KidsBoys6M5YJeansPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-indigo-50 via-blue-50 to-cyan-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6M-5Y Jeans Collection" 
          subtitle="Stylish & Durable Jeans for Little Adventurers"
          products={kidsBoys6M5YJeansProducts} 
        />
      </main>
    </div>
  );
}