import { ProductGrid } from "../ProductGrid";

const kidsGirls6To14YShortsAndSkirtsProducts = [
  {
    id: "kg6-14y-ss-001",
    name: "Pleated School Skirt",
    price: "$32",
    image: "https://images.unsplash.com/photo-1532881453498-e88d79c0e020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnaXJscyUyMGtpZHMlMjBzaG9ydHMlMjBza2lydHN8ZW58MXx8fHwxNzU1MTkxMjQwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Classic pleated school skirt for uniform wear",
    category: "Shorts & Skirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "Gray", "Black", "Burgundy"],
    brand: "School Elite",
    rating: 4.8,
    reviews: 234,
    features: ["Pleated Design", "School Uniform", "Classic"],
    icon: "👗",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6-14y-ss-002",
    name: "Denim Mini Skirt",
    price: "$28",
    image: "https://images.unsplash.com/photo-1532881453498-e88d79c0e020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy denim mini skirt for casual style",
    category: "Shorts & Skirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Denim Style",
    rating: 4.6,
    reviews: 189,
    features: ["Denim Fabric", "Mini Length", "Trendy"],
    icon: "👗",
    itemCount: "Trendy",
  },
  {
    id: "kg6-14y-ss-003",
    name: "Athletic Bike Shorts",
    price: "$24",
    image: "https://images.unsplash.com/photo-1532881453498-e88d79c0e020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Performance bike shorts perfect for sports",
    category: "Shorts & Skirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "Pink", "Purple"],
    brand: "Sports Active",
    rating: 4.7,
    reviews: 167,
    features: ["Athletic Performance", "Bike Shorts", "Sports"],
    icon: "🩳",
    itemCount: "Athletic",
  },
  {
    id: "kg6-14y-ss-004",
    name: "Tulle Party Skirt",
    price: "$35",
    image: "https://images.unsplash.com/photo-1532881453498-e88d79c0e020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant tulle skirt perfect for special occasions",
    category: "Shorts & Skirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Party Pink", "Princess Purple", "Elegant White"],
    brand: "Party Princess",
    rating: 4.5,
    reviews: 145,
    features: ["Tulle Fabric", "Party Ready", "Elegant"],
    icon: "👗",
    itemCount: "Party",
  },
  {
    id: "kg6-14y-ss-005",
    name: "High-Waisted Shorts",
    price: "$26",
    image: "https://images.unsplash.com/photo-1532881453498-e88d79c0e020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy high-waisted shorts for fashion-forward girls",
    category: "Shorts & Skirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Khaki", "Navy", "Black"],
    brand: "Fashion Forward",
    rating: 4.4,
    reviews: 198,
    features: ["High-Waisted", "Fashion Forward", "Trendy"],
    icon: "🩳",
    itemCount: "Fashion",
  },
  {
    id: "kg6-14y-ss-006",
    name: "Circle Skater Skirt",
    price: "$30",
    image: "https://images.unsplash.com/photo-1532881453498-e88d79c0e020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Fun circle skater skirt that twirls beautifully",
    category: "Shorts & Skirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Skater Pink", "Circle Blue", "Twirl Purple"],
    brand: "Skater Girl",
    rating: 4.6,
    reviews: 156,
    features: ["Circle Skirt", "Skater Style", "Twirls"],
    icon: "👗",
    itemCount: "Fun",
  },
  {
    id: "kg6-14y-ss-007",
    name: "Cargo Adventure Shorts",
    price: "$29",
    image: "https://images.unsplash.com/photo-1532881453498-e88d79c0e020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Practical cargo shorts with multiple pockets",
    category: "Shorts & Skirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Khaki", "Olive Green", "Navy"],
    brand: "Adventure Girl",
    rating: 4.3,
    reviews: 123,
    features: ["Cargo Pockets", "Adventure Ready", "Practical"],
    icon: "🩳",
    itemCount: "Adventure",
  },
  {
    id: "kg6-14y-ss-008",
    name: "Floral Maxi Skirt",
    price: "$34",
    image: "https://images.unsplash.com/photo-1532881453498-e88d79c0e020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Beautiful floral maxi skirt for bohemian style",
    category: "Shorts & Skirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Pink Floral", "Blue Garden", "Purple Bloom"],
    brand: "Boho Dreams",
    rating: 4.7,
    reviews: 178,
    features: ["Floral Print", "Maxi Length", "Bohemian"],
    icon: "👗",
    itemCount: "Boho",
  },
  {
    id: "kg6-14y-ss-009",
    name: "Tennis Sports Skirt",
    price: "$27",
    image: "https://images.unsplash.com/photo-1532881453498-e88d79c0e020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Athletic tennis skirt with built-in shorts",
    category: "Shorts & Skirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Tennis White", "Sport Navy", "Active Pink"],
    brand: "Tennis Pro",
    rating: 4.5,
    reviews: 134,
    features: ["Tennis Style", "Built-in Shorts", "Athletic"],
    icon: "👗",
    itemCount: "Sports",
  },
  {
    id: "kg6-14y-ss-010",
    name: "Sequin Party Shorts",
    price: "$31",
    image: "https://images.unsplash.com/photo-1532881453498-e88d79c0e020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sparkly sequin shorts perfect for celebrations",
    category: "Shorts & Skirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Gold Sequin", "Silver Sequin", "Pink Sequin"],
    brand: "Sparkle Queen",
    rating: 4.8,
    reviews: 167,
    features: ["Sequin Details", "Party Ready", "Sparkly"],
    icon: "🩳",
    itemCount: "Sparkly",
  }
];

export function KidsGirls6To14YShortsAndSkirtsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-pink-50 via-purple-50 to-yellow-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6-14Y Shorts & Skirts Collection" 
          subtitle="Stylish & Versatile Bottoms for Active Girls"
          products={kidsGirls6To14YShortsAndSkirtsProducts} 
        />
      </main>
    </div>
  );
}