import { ProductGrid } from "../ProductGrid";

const kidsGirls6To14YDressesJumpsuitsProducts = [
  {
    id: "kg6-14y-d-001",
    name: "Party Princess Dress",
    price: "$45",
    image: "https://images.unsplash.com/photo-1597294151491-1d22b38698d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnaXJscyUyMGRyZXNzJTIwa2lkc3xlbnwxfHx8fDE3NTUxOTA4NzZ8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Elegant princess-style dress perfect for special parties",
    category: "Dresses & Jumpsuits",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Princess Pink", "Royal Purple", "Elegant Blue", "Pure White"],
    brand: "Princess Collection",
    rating: 4.9,
    reviews: 278,
    features: ["Princess Style", "Party Ready", "Elegant"],
    icon: "👗",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6-14y-d-002",
    name: "Floral Summer Dress",
    price: "$32",
    image: "https://images.unsplash.com/photo-1597294151491-1d22b38698d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Light and breezy floral dress for summer adventures",
    category: "Dresses & Jumpsuits",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Pink Floral", "Blue Floral", "Yellow Floral", "Purple Floral"],
    brand: "Summer Garden",
    rating: 4.7,
    reviews: 234,
    features: ["Floral Print", "Summer Ready", "Breezy"],
    icon: "👗",
    itemCount: "Summer",
  },
  {
    id: "kg6-14y-d-003",
    name: "Denim Jumper Dress",
    price: "$38",
    image: "https://images.unsplash.com/photo-1597294151491-1d22b38698d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy denim jumper dress for casual cool style",
    category: "Dresses & Jumpsuits",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Denim Cool",
    rating: 4.6,
    reviews: 189,
    features: ["Denim Fabric", "Jumper Style", "Casual Cool"],
    icon: "👗",
    itemCount: "Denim",
  },
  {
    id: "kg6-14y-d-004",
    name: "Unicorn Rainbow Dress",
    price: "$40",
    image: "https://images.unsplash.com/photo-1597294151491-1d22b38698d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Magical unicorn dress with rainbow tulle layers",
    category: "Dresses & Jumpsuits",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Unicorn Rainbow", "Pink Unicorn", "Purple Magic"],
    brand: "Unicorn Dreams",
    rating: 4.8,
    reviews: 256,
    features: ["Unicorn Theme", "Rainbow Tulle", "Magical"],
    icon: "👗",
    itemCount: "Magical",
  },
  {
    id: "kg6-14y-d-005",
    name: "Striped Casual Dress",
    price: "$28",
    image: "https://images.unsplash.com/photo-1597294151491-1d22b38698d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic striped dress perfect for everyday wear",
    category: "Dresses & Jumpsuits",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy Stripe", "Pink Stripe", "Red Stripe"],
    brand: "Stripe Style",
    rating: 4.5,
    reviews: 167,
    features: ["Striped Pattern", "Casual", "Everyday"],
    icon: "👗",
    itemCount: "Casual",
  },
  {
    id: "kg6-14y-d-006",
    name: "Ballerina Tutu Dress",
    price: "$42",
    image: "https://images.unsplash.com/photo-1597294151491-1d22b38698d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Graceful ballerina-inspired tutu dress for dance",
    category: "Dresses & Jumpsuits",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Ballet Pink", "Swan White", "Lavender Dream"],
    brand: "Dance Dreams",
    rating: 4.7,
    reviews: 198,
    features: ["Ballerina Style", "Tutu Skirt", "Dance Ready"],
    icon: "👗",
    itemCount: "Dance",
  },
  {
    id: "kg6-14y-d-007",
    name: "Mermaid Scale Jumpsuit",
    price: "$36",
    image: "https://images.unsplash.com/photo-1597294151491-1d22b38698d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Shimmery mermaid scale print jumpsuit",
    category: "Dresses & Jumpsuits",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Mermaid Teal", "Ocean Blue", "Sea Green"],
    brand: "Ocean Magic",
    rating: 4.6,
    reviews: 145,
    features: ["Mermaid Scales", "Jumpsuit Style", "Shimmery"],
    icon: "👗",
    itemCount: "Ocean",
  },
  {
    id: "kg6-14y-d-008",
    name: "Boho Maxi Dress",
    price: "$35",
    image: "https://images.unsplash.com/photo-1597294151491-1d22b38698d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Flowing bohemian maxi dress with embroidered details",
    category: "Dresses & Jumpsuits",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Boho White", "Earth Cream", "Sage Green"],
    brand: "Boho Chic",
    rating: 4.4,
    reviews: 123,
    features: ["Boho Style", "Maxi Length", "Embroidered"],
    icon: "👗",
    itemCount: "Boho",
  },
  {
    id: "kg6-14y-d-009",
    name: "Polka Dot Swing Dress",
    price: "$30",
    image: "https://images.unsplash.com/photo-1597294151491-1d22b38698d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Vintage-inspired polka dot swing dress",
    category: "Dresses & Jumpsuits",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy Dots", "Red Dots", "Pink Dots"],
    brand: "Vintage Kids",
    rating: 4.5,
    reviews: 178,
    features: ["Polka Dots", "Swing Style", "Vintage"],
    icon: "👗",
    itemCount: "Vintage",
  },
  {
    id: "kg6-14y-d-010",
    name: "Space Galaxy Dress",
    price: "$34",
    image: "https://images.unsplash.com/photo-1597294151491-1d22b38698d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cosmic galaxy print dress for space enthusiasts",
    category: "Dresses & Jumpsuits",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Galaxy Purple", "Space Navy", "Cosmic Pink"],
    brand: "Galaxy Girls",
    rating: 4.7,
    reviews: 156,
    features: ["Galaxy Print", "Space Theme", "Cosmic"],
    icon: "👗",
    itemCount: "Space",
  }
];

export function KidsGirls6To14YDressesJumpsuitsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-pink-50 via-purple-50 to-yellow-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6-14Y Dresses & Jumpsuits Collection" 
          subtitle="Beautiful & Stylish Dresses for Special Occasions"
          products={kidsGirls6To14YDressesJumpsuitsProducts} 
        />
      </main>
    </div>
  );
}