import { ProductGrid } from "../ProductGrid";

const kidsGirls6To14YCoordSetsProducts = [
  {
    id: "kg6-14y-cs-001",
    name: "Trendy Teen Coord Set",
    price: "$48",
    image: "https://images.unsplash.com/photo-1607454317633-a30150d568a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnaXJscyUyMGtpZHMlMjBvdXRmaXQlMjBzZXR8ZW58MXx8fHwxNzU1MTkwOTY3fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Stylish coordinated set perfect for trendy teens",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Trendy Pink", "Cool Purple", "Classic Navy", "Modern Black"],
    brand: "Teen Style",
    rating: 4.8,
    reviews: 267,
    features: ["Trendy Design", "Teen Fashion", "Coordinated"],
    icon: "👗",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6-14y-cs-002",
    name: "Sports Chic Set",
    price: "$42",
    image: "https://images.unsplash.com/photo-1607454317633-a30150d568a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Athletic-inspired coord set for active girls",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Sport Pink", "Athletic Gray", "Active Navy"],
    brand: "Sports Chic",
    rating: 4.7,
    reviews: 234,
    features: ["Athletic Style", "Sports Chic", "Active Wear"],
    icon: "👗",
    itemCount: "Athletic",
  },
  {
    id: "kg6-14y-cs-003",
    name: "Boho Summer Set",
    price: "$45",
    image: "https://images.unsplash.com/photo-1607454317633-a30150d568a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Bohemian-style summer coordinate set",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Boho Cream", "Earth Tone", "Desert Sand"],
    brand: "Boho Dreams",
    rating: 4.6,
    reviews: 189,
    features: ["Boho Style", "Summer Ready", "Relaxed"],
    icon: "👗",
    itemCount: "Boho",
  },
  {
    id: "kg6-14y-cs-004",
    name: "School Smart Set",
    price: "$40",
    image: "https://images.unsplash.com/photo-1607454317633-a30150d568a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Smart casual set perfect for school and events",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["School Navy", "Classic Gray", "Smart Black"],
    brand: "School Style",
    rating: 4.5,
    reviews: 198,
    features: ["School Ready", "Smart Casual", "Classic"],
    icon: "👗",
    itemCount: "School",
  },
  {
    id: "kg6-14y-cs-005",
    name: "Floral Garden Set",
    price: "$44",
    image: "https://images.unsplash.com/photo-1607454317633-a30150d568a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Beautiful floral coordinate set for spring",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Pink Floral", "Blue Garden", "Purple Bloom"],
    brand: "Garden Party",
    rating: 4.7,
    reviews: 156,
    features: ["Floral Print", "Spring Style", "Garden Theme"],
    icon: "👗",
    itemCount: "Floral",
  },
  {
    id: "kg6-14y-cs-006",
    name: "Denim Cool Set",
    price: "$46",
    image: "https://images.unsplash.com/photo-1607454317633-a30150d568a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cool denim coordinate set with modern styling",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Cool Denim", "Light Wash", "Dark Denim"],
    brand: "Denim Cool",
    rating: 4.4,
    reviews: 167,
    features: ["Denim Style", "Modern", "Cool"],
    icon: "👗",
    itemCount: "Denim",
  },
  {
    id: "kg6-14y-cs-007",
    name: "Party Princess Set",
    price: "$52",
    image: "https://images.unsplash.com/photo-1607454317633-a30150d568a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant party coordinate set for special occasions",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Party Pink", "Royal Purple", "Elegant Gold"],
    brand: "Party Princess",
    rating: 4.8,
    reviews: 145,
    features: ["Party Ready", "Elegant", "Special Occasion"],
    icon: "👗",
    itemCount: "Party",
  },
  {
    id: "kg6-14y-cs-008",
    name: "Casual Weekend Set",
    price: "$38",
    image: "https://images.unsplash.com/photo-1607454317633-a30150d568a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Comfortable casual set perfect for weekends",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Casual Gray", "Weekend Pink", "Relaxed Navy"],
    brand: "Weekend Wear",
    rating: 4.3,
    reviews: 123,
    features: ["Casual Style", "Weekend Ready", "Comfortable"],
    icon: "👗",
    itemCount: "Casual",
  },
  {
    id: "kg6-14y-cs-009",
    name: "Tie-Dye Fun Set",
    price: "$41",
    image: "https://images.unsplash.com/photo-1607454317633-a30150d568a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Fun tie-dye coordinate set for creative girls",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Rainbow Tie-Dye", "Pink Tie-Dye", "Purple Tie-Dye"],
    brand: "Tie-Dye Dreams",
    rating: 4.6,
    reviews: 178,
    features: ["Tie-Dye Pattern", "Fun", "Creative"],
    icon: "👗",
    itemCount: "Fun",
  },
  {
    id: "kg6-14y-cs-010",
    name: "Vintage Vibes Set",
    price: "$43",
    image: "https://images.unsplash.com/photo-1607454317633-a30150d568a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Retro-inspired vintage coordinate set",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Vintage Pink", "Retro Blue", "Classic Cream"],
    brand: "Vintage Kids",
    rating: 4.5,
    reviews: 134,
    features: ["Vintage Style", "Retro Inspired", "Classic"],
    icon: "👗",
    itemCount: "Vintage",
  }
];

export function KidsGirls6To14YCoordSetsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-purple-50 via-pink-50 to-blue-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6-14Y Co-Ord Sets Collection" 
          subtitle="Trendy & Coordinated Outfits for Fashion-Forward Girls"
          products={kidsGirls6To14YCoordSetsProducts} 
        />
      </main>
    </div>
  );
}