import { ProductGrid } from "../ProductGrid";

const kidsBoys6To14YShortsProducts = [
  {
    id: "kb6-14y-sh-001",
    name: "Athletic Basketball Shorts",
    price: "$25",
    image: "https://images.unsplash.com/photo-1576252951301-3b7b1e4278d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib3lzJTIwa2lkcyUyMHNob3J0c3xlbnwxfHx8fDE3NTUxOTA5MzF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Performance basketball shorts for active boys",
    category: "Shorts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "Red", "Royal Blue"],
    brand: "Athletic Pro",
    rating: 4.8,
    reviews: 234,
    features: ["Athletic Performance", "Basketball Style", "Active Wear"],
    icon: "🩳",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6-14y-sh-002",
    name: "Cargo Adventure Shorts",
    price: "$28",
    image: "https://images.unsplash.com/photo-1576252951301-3b7b1e4278d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Durable cargo shorts with multiple pockets",
    category: "Shorts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Khaki", "Olive Green", "Navy", "Gray"],
    brand: "Adventure Gear",
    rating: 4.7,
    reviews: 189,
    features: ["Cargo Pockets", "Durable", "Adventure Ready"],
    icon: "🩳",
    itemCount: "Adventure",
  },
  {
    id: "kb6-14y-sh-003",
    name: "Swim Board Shorts",
    price: "$26",
    image: "https://images.unsplash.com/photo-1576252951301-3b7b1e4278d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Quick-dry board shorts perfect for swimming",
    category: "Shorts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Ocean Blue", "Surf Green", "Wave Navy"],
    brand: "Beach Boys",
    rating: 4.6,
    reviews: 167,
    features: ["Quick Dry", "Board Shorts", "Swimming"],
    icon: "🩳",
    itemCount: "Beach",
  },
  {
    id: "kb6-14y-sh-004",
    name: "Chino School Shorts",
    price: "$24",
    image: "https://images.unsplash.com/photo-1576252951301-3b7b1e4278d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Smart chino shorts perfect for school uniform",
    category: "Shorts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "Khaki", "Gray", "Black"],
    brand: "School Smart",
    rating: 4.5,
    reviews: 198,
    features: ["Chino Style", "School Uniform", "Smart"],
    icon: "🩳",
    itemCount: "School",
  },
  {
    id: "kb6-14y-sh-005",
    name: "Gaming Controller Shorts",
    price: "$22",
    image: "https://images.unsplash.com/photo-1576252951301-3b7b1e4278d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cool gaming-themed shorts with controller graphics",
    category: "Shorts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Gaming Black", "Controller Gray", "Pixel Blue"],
    brand: "Game On",
    rating: 4.4,
    reviews: 145,
    features: ["Gaming Graphics", "Controller Design", "Cool"],
    icon: "🩳",
    itemCount: "Gaming",
  },
  {
    id: "kb6-14y-sh-006",
    name: "Skateboard Style Shorts",
    price: "$27",
    image: "https://images.unsplash.com/photo-1576252951301-3b7b1e4278d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Street-style skateboard shorts for cool kids",
    category: "Shorts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Skate Black", "Street Gray", "Urban Navy"],
    brand: "Street Style",
    rating: 4.6,
    reviews: 156,
    features: ["Skateboard Style", "Street Wear", "Cool"],
    icon: "🩳",
    itemCount: "Street",
  },
  {
    id: "kb6-14y-sh-007",
    name: "Camouflage Tactical Shorts",
    price: "$29",
    image: "https://images.unsplash.com/photo-1576252951301-3b7b1e4278d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Tactical-style camouflage shorts for outdoor adventures",
    category: "Shorts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Forest Camo", "Desert Camo", "Urban Camo"],
    brand: "Tactical Kids",
    rating: 4.5,
    reviews: 123,
    features: ["Camouflage", "Tactical Style", "Outdoor"],
    icon: "🩳",
    itemCount: "Tactical",
  },
  {
    id: "kb6-14y-sh-008",
    name: "Soccer Training Shorts",
    price: "$23",
    image: "https://images.unsplash.com/photo-1576252951301-3b7b1e4278d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Professional soccer training shorts for young athletes",
    category: "Shorts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Soccer Blue", "Team Red", "Goal Green"],
    brand: "Soccer Stars",
    rating: 4.7,
    reviews: 178,
    features: ["Soccer Training", "Athletic", "Team Sports"],
    icon: "🩳",
    itemCount: "Soccer",
  },
  {
    id: "kb6-14y-sh-009",
    name: "Tech Mesh Shorts",
    price: "$26",
    image: "https://images.unsplash.com/photo-1576252951301-3b7b1e4278d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "High-tech mesh shorts with moisture-wicking technology",
    category: "Shorts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Tech Black", "Mesh Gray", "Sport Navy"],
    brand: "Tech Sport",
    rating: 4.4,
    reviews: 134,
    features: ["Tech Mesh", "Moisture Wicking", "High Performance"],
    icon: "🩳",
    itemCount: "Tech",
  },
  {
    id: "kb6-14y-sh-010",
    name: "Classic Jean Shorts",
    price: "$25",
    image: "https://images.unsplash.com/photo-1576252951301-3b7b1e4278d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Timeless denim shorts perfect for casual wear",
    category: "Shorts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Classic Blue", "Light Wash", "Dark Denim"],
    brand: "Classic Denim",
    rating: 4.6,
    reviews: 167,
    features: ["Denim Fabric", "Classic Style", "Casual"],
    icon: "🩳",
    itemCount: "Classic",
  }
];

export function KidsBoys6To14YShortsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-green-50 to-gray-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6-14Y Shorts Collection" 
          subtitle="Active & Stylish Shorts for Growing Boys"
          products={kidsBoys6To14YShortsProducts} 
        />
      </main>
    </div>
  );
}