import { ProductGrid } from "../ProductGrid";

const kidsBoys6To14YTShirtsPolosProducts = [
  {
    id: "kb6-14y-tp-001",
    name: "School Spirit Polo",
    price: "$26",
    image: "https://i.pinimg.com/1200x/5a/d4/65/5ad46531ddaaa804e10c13fa67573649.jpg",
    description: "Classic school polo shirt with embroidered logo",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "White", "Red", "Green"],
    brand: "School Pride",
    rating: 4.8,
    reviews: 267,
    features: ["School Ready", "Embroidered Logo", "Classic Fit"],
    icon: "👕",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6-14y-tp-002",
    name: "Sports Team T-Shirt",
    price: "$22",
    image: "https://i.pinimg.com/736x/d2/d9/fd/d2d9fd98f058f1eda46d479485d53346.jpg",
    description: "Athletic team-style t-shirt with number graphics",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Red", "Blue", "Green", "Black"],
    brand: "Team Spirit",
    rating: 4.7,
    reviews: 234,
    features: ["Team Style", "Number Graphics", "Athletic Fit"],
    icon: "👕",
    itemCount: "Sports",
  },
  {
    id: "kb6-14y-tp-003",
    name: "Gaming Hero Tee",
    price: "$24",
    image: "https://i.pinimg.com/736x/84/25/1e/84251ed253a3c743e562ec97238f4fbb.jpg",
    description: "Cool gaming-themed t-shirt with pixel art designs",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Navy", "Gray", "Green"],
    brand: "Game On",
    rating: 4.6,
    reviews: 198,
    features: ["Gaming Theme", "Pixel Art", "Cool Design"],
    icon: "👕",
    itemCount: "Gaming",
  },
  {
    id: "kb6-14y-tp-004",
    name: "Skateboard Graphic Tee",
    price: "$23",
    image: "https://i.pinimg.com/736x/73/88/9e/73889ea3a64a0aa44033781820000f49.jpg",
    description: "Street-style skateboard graphic t-shirt for cool kids",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "White", "Gray", "Navy"],
    brand: "Street Style",
    rating: 4.5,
    reviews: 156,
    features: ["Skateboard Graphics", "Street Style", "Cool"],
    icon: "👕",
    itemCount: "Street",
  },
  {
    id: "kb6-14y-tp-005",
    name: "Long Sleeve Polo",
    price: "$28",
    image: "https://i.pinimg.com/1200x/5c/f6/d2/5cf6d2666ced534b118e06fb01016427.jpg",
    description: "Classic long sleeve polo perfect for cooler weather",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "Gray", "White", "Burgundy"],
    brand: "Classic Polo",
    rating: 4.4,
    reviews: 145,
    features: ["Long Sleeve", "Polo Style", "Cool Weather"],
    icon: "👕",
    itemCount: "Classic",
  },
  {
    id: "kb6-14y-tp-006",
    name: "Science Explorer Tee",
    price: "$21",
    image: "https://i.pinimg.com/736x/dc/3f/7b/dc3f7b38692d0fa770d2f291c5cf7542.jpg",
    description: "Educational science-themed t-shirt with fun facts",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Blue", "Green", "Purple", "Orange"],
    brand: "Science Fun",
    rating: 4.6,
    reviews: 167,
    features: ["Science Theme", "Educational", "Fun Facts"],
    icon: "👕",
    itemCount: "Educational",
  },
  {
    id: "kb6-14y-tp-007",
    name: "Vintage Band Tee",
    price: "$25",
    image: "https://i.pinimg.com/1200x/7e/87/e4/7e87e4d3ee66a1c983f77da52605707a.jpg",
    description: "Retro-style band t-shirt with vintage graphics",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Black", "Gray", "Navy", "Charcoal"],
    brand: "Vintage Vibes",
    rating: 4.7,
    reviews: 189,
    features: ["Vintage Style", "Band Graphics", "Retro"],
    icon: "👕",
    itemCount: "Vintage",
  },
  {
    id: "kb6-14y-tp-008",
    name: "Adventure Polo",
    price: "$27",
    image: "https://i.pinimg.com/736x/65/57/e2/6557e2be47fb6ba2a4308165faa612ec.jpg",
    description: "Outdoor adventure-themed polo with nature graphics",
    category: "T-Shirts & Polos",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Khaki", "Forest Green", "Brown", "Navy"],
    brand: "Adventure Kids",
    rating: 4.5,
    reviews: 123,
    features: ["Adventure Theme", "Nature Graphics", "Outdoor"],
    icon: "👕",
    itemCount: "Adventure",
  }
];

export function KidsBoys6To14YTShirtsPolosPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-green-50 to-purple-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6-14Y T-Shirts & Polos Collection" 
          subtitle="Cool & Comfortable Styles for Growing Boys"
          products={kidsBoys6To14YTShirtsPolosProducts} 
        />
      </main>
    </div>
  );
}
