import { ProductGrid } from "../ProductGrid";

const kidsBoys6M5YShirtsProducts = [
  {
    id: "kb6m5y-s-001",
    name: "Button-Down Mini Shirt",
    price: "$22",
    image: "https://images.unsplash.com/photo-1508882956913-62da95326c47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWJ5JTIwYm95JTIwc2hpcnR8ZW58MXx8fHwxNzU1MTg5NDgyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Adorable button-down shirt perfect for special occasions",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["White", "Light Blue", "Navy", "Cream"],
    brand: "Little Gentleman",
    rating: 4.8,
    reviews: 189,
    features: ["Button-Down", "Soft Cotton", "Easy Care"],
    icon: "👔",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6m5y-s-002",
    name: "Plaid Dress Shirt",
    price: "$24",
    image: "https://images.unsplash.com/photo-1508882956913-62da95326c47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic plaid pattern dress shirt for little boys",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Blue Plaid", "Red Plaid", "Green Plaid"],
    brand: "Tiny Formal",
    rating: 4.6,
    reviews: 134,
    features: ["Plaid Pattern", "Collar", "Machine Washable"],
    icon: "👔",
    itemCount: "Classic",
  },
  {
    id: "kb6m5y-s-003",
    name: "Safari Adventure Shirt",
    price: "$20",
    image: "https://images.unsplash.com/photo-1508882956913-62da95326c47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Fun safari-themed shirt with animal prints",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Khaki", "Safari Green", "Tan"],
    brand: "Adventure Kids",
    rating: 4.7,
    reviews: 156,
    features: ["Safari Theme", "Pocket Detail", "Comfortable"],
    icon: "👔",
    itemCount: "Adventure",
  },
  {
    id: "kb6m5y-s-004",
    name: "Striped Oxford Shirt",
    price: "$26",
    image: "https://images.unsplash.com/photo-1508882956913-62da95326c47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Preppy striped oxford shirt for smart casual looks",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Blue Stripe", "Navy Stripe", "Pink Stripe"],
    brand: "Preppy Tot",
    rating: 4.5,
    reviews: 112,
    features: ["Oxford Fabric", "Striped", "Preppy Style"],
    icon: "👔",
    itemCount: "Preppy",
  },
  {
    id: "kb6m5y-s-005",
    name: "Denim Shirt",
    price: "$28",
    image: "https://images.unsplash.com/photo-1508882956913-62da95326c47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy denim shirt for casual everyday wear",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Denim Baby",
    rating: 4.4,
    reviews: 98,
    features: ["Denim Fabric", "Snap Buttons", "Casual"],
    icon: "👔",
    itemCount: "Casual",
  },
  {
    id: "kb6m5y-s-006",
    name: "Bow Tie Shirt Set",
    price: "$32",
    image: "https://images.unsplash.com/photo-1508882956913-62da95326c47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Formal shirt with detachable bow tie for special events",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["White", "Light Blue", "Cream"],
    brand: "Little Formal",
    rating: 4.9,
    reviews: 87,
    features: ["Bow Tie Included", "Formal", "Special Occasion"],
    icon: "👔",
    itemCount: "Formal",
  },
  {
    id: "kb6m5y-s-007",
    name: "Checked Flannel Shirt",
    price: "$25",
    image: "https://images.unsplash.com/photo-1508882956913-62da95326c47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cozy flannel shirt perfect for cooler weather",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Red Check", "Blue Check", "Green Check"],
    brand: "Cozy Kids",
    rating: 4.6,
    reviews: 123,
    features: ["Flannel Fabric", "Checked Pattern", "Warm"],
    icon: "👔",
    itemCount: "Cozy",
  },
  {
    id: "kb6m5y-s-008",
    name: "Linen Blend Shirt",
    price: "$30",
    image: "https://images.unsplash.com/photo-1508882956913-62da95326c47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Breathable linen blend shirt for summer comfort",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Natural", "White", "Light Blue"],
    brand: "Summer Breeze",
    rating: 4.3,
    reviews: 76,
    features: ["Linen Blend", "Breathable", "Summer"],
    icon: "👔",
    itemCount: "Summer",
  },
  {
    id: "kb6m5y-s-009",
    name: "Pocket Detail Shirt",
    price: "$23",
    image: "https://images.unsplash.com/photo-1508882956913-62da95326c47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic shirt with functional chest pocket",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["White", "Navy", "Gray", "Khaki"],
    brand: "Classic Kids",
    rating: 4.5,
    reviews: 145,
    features: ["Chest Pocket", "Classic Cut", "Versatile"],
    icon: "👔",
    itemCount: "Classic",
  },
  {
    id: "kb6m5y-s-010",
    name: "Print Button Shirt",
    price: "$21",
    image: "https://images.unsplash.com/photo-1508882956913-62da95326c47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Fun printed shirt with playful designs",
    category: "Shirts",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Animal Print", "Car Print", "Space Print"],
    brand: "Playful Prints",
    rating: 4.4,
    reviews: 167,
    features: ["Fun Prints", "Colorful", "Playful"],
    icon: "👔",
    itemCount: "Fun",
  }
];

export function KidsBoys6M5YShirtsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-green-50 to-yellow-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6M-5Y Shirts Collection" 
          subtitle="Smart & Adorable Shirts for Little Gentlemen"
          products={kidsBoys6M5YShirtsProducts} 
        />
      </main>
    </div>
  );
}