import { ProductGrid } from "../ProductGrid";

const kidsBoys6To14YCoordSetsProducts = [
  {
    id: "kb6-14y-cs-001",
    name: "Athletic Sport Set",
    price: "$45",
    image: "https://images.unsplash.com/photo-1604303768345-038b79a8c47a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib3lzJTIwa2lkcyUyMG91dGZpdCUyMHNldCUyMGNvb3JkaW5hdGVkfGVufDF8fHx8MTc1NTE5MTM0NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Performance athletic set for active boys",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Athletic Black", "Sport Navy", "Team Red", "Blue"],
    brand: "Athletic Pro",
    rating: 4.8,
    reviews: 234,
    features: ["Athletic Performance", "Sport Set", "Active"],
    icon: "👕",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6-14y-cs-002",
    name: "Gaming Champion Set",
    price: "$38",
    image: "https://images.unsplash.com/photo-1604303768345-038b79a8c47a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cool gaming-themed coordinate set",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Gaming Black", "Controller Gray", "Pixel Blue"],
    brand: "Game Master",
    rating: 4.7,
    reviews: 189,
    features: ["Gaming Theme", "Cool Graphics", "Champion"],
    icon: "👕",
    itemCount: "Gaming",
  },
  {
    id: "kb6-14y-cs-003",
    name: "Urban Street Set",
    price: "$42",
    image: "https://images.unsplash.com/photo-1604303768345-038b79a8c47a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy urban street style coordinate set",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Street Black", "Urban Gray", "City Navy"],
    brand: "Street Style",
    rating: 4.6,
    reviews: 167,
    features: ["Urban Style", "Street Fashion", "Trendy"],
    icon: "👕",
    itemCount: "Urban",
  },
  {
    id: "kb6-14y-cs-004",
    name: "Skateboard Cool Set",
    price: "$40",
    image: "https://images.unsplash.com/photo-1604303768345-038b79a8c47a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Skateboard-inspired coordinate set for cool kids",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Skate Black", "Board Gray", "Wheel Navy"],
    brand: "Skate Cool",
    rating: 4.5,
    reviews: 145,
    features: ["Skateboard Style", "Cool Design", "Street"],
    icon: "👕",
    itemCount: "Skate",
  },
  {
    id: "kb6-14y-cs-005",
    name: "Space Explorer Set",
    price: "$41",
    image: "https://images.unsplash.com/photo-1604303768345-038b79a8c47a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cosmic space-themed coordinate set",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Space Navy", "Galaxy Black", "Cosmic Blue"],
    brand: "Space Explorer",
    rating: 4.7,
    reviews: 198,
    features: ["Space Theme", "Explorer Style", "Cosmic"],
    icon: "👕",
    itemCount: "Space",
  },
  {
    id: "kb6-14y-cs-006",
    name: "Soccer Champion Set",
    price: "$43",
    image: "https://images.unsplash.com/photo-1604303768345-038b79a8c47a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Professional soccer coordinate set for young athletes",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Soccer Blue", "Team Red", "Goal Green"],
    brand: "Soccer Pro",
    rating: 4.6,
    reviews: 156,
    features: ["Soccer Theme", "Athletic", "Champion"],
    icon: "👕",
    itemCount: "Soccer",
  },
  {
    id: "kb6-14y-cs-007",
    name: "Denim Casual Set",
    price: "$46",
    image: "https://images.unsplash.com/photo-1604303768345-038b79a8c47a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic denim coordinate set for casual style",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Denim Style",
    rating: 4.4,
    reviews: 123,
    features: ["Denim Style", "Casual", "Classic"],
    icon: "👕",
    itemCount: "Denim",
  },
  {
    id: "kb6-14y-cs-008",
    name: "Tech Warrior Set",
    price: "$44",
    image: "https://images.unsplash.com/photo-1604303768345-038b79a8c47a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "High-tech warrior-themed coordinate set",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Tech Black", "Warrior Gray", "Digital Blue"],
    brand: "Tech Warrior",
    rating: 4.5,
    reviews: 178,
    features: ["Tech Theme", "Warrior Style", "Digital"],
    icon: "👕",
    itemCount: "Tech",
  },
  {
    id: "kb6-14y-cs-009",
    name: "Adventure Scout Set",
    price: "$39",
    image: "https://images.unsplash.com/photo-1604303768345-038b79a8c47a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Outdoor adventure coordinate set for explorers",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Forest Green", "Scout Khaki", "Adventure Brown"],
    brand: "Adventure Scout",
    rating: 4.3,
    reviews: 134,
    features: ["Adventure Theme", "Scout Style", "Outdoor"],
    icon: "👕",
    itemCount: "Adventure",
  },
  {
    id: "kb6-14y-cs-010",
    name: "Music Rock Set",
    price: "$41",
    image: "https://images.unsplash.com/photo-1604303768345-038b79a8c47a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Rock music-themed coordinate set for future stars",
    category: "Co-Ord Sets",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Rock Black", "Guitar Gray", "Music Navy"],
    brand: "Rock Star",
    rating: 4.6,
    reviews: 167,
    features: ["Music Theme", "Rock Style", "Star"],
    icon: "👕",
    itemCount: "Music",
  }
];

export function KidsBoys6To14YCoordSetsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-green-50 to-gray-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6-14Y Co-Ord Sets Collection" 
          subtitle="Cool & Coordinated Outfits for Active Boys"
          products={kidsBoys6To14YCoordSetsProducts} 
        />
      </main>
    </div>
  );
}