import { ProductGrid } from "../ProductGrid";

const kidsGirls6M5YCoordSetsProducts = [
  {
    id: "kg6m5y-cs-001",
    name: "Princess Tea Party Set",
    price: "$35",
    image: "https://images.unsplash.com/photo-1712718228658-225eeb2bb7e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b2RkbGVyJTIwZ2lybCUyMGNvb3JkaW5hdGVkJTIwb3V0Zml0JTIwc2V0fGVufDF8fHx8MTc1NTE5MDI4MXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Elegant princess-themed matching top and skirt set",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Purple", "White", "Lavender"],
    brand: "Princess Collection",
    rating: 4.9,
    reviews: 298,
    features: ["Princess Theme", "Matching Set", "Tea Party Ready"],
    icon: "👗",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6m5y-cs-002",
    name: "Floral Garden Set",
    price: "$28",
    image: "https://images.unsplash.com/photo-1712718228658-225eeb2bb7e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sweet floral print blouse and shorts coordination",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink Floral", "Blue Floral", "Yellow Floral"],
    brand: "Garden Party",
    rating: 4.7,
    reviews: 234,
    features: ["Floral Print", "Garden Theme", "Sweet"],
    icon: "👗",
    itemCount: "Garden",
  },
  {
    id: "kg6m5y-cs-003",
    name: "Ballerina Dream Set",
    price: "$32",
    image: "https://images.unsplash.com/photo-1712718228658-225eeb2bb7e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Dance-inspired leotard and tutu skirt combo",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Lavender", "White", "Rose"],
    brand: "Dance Dreams",
    rating: 4.8,
    reviews: 189,
    features: ["Ballerina Style", "Tutu Skirt", "Dance Ready"],
    icon: "👗",
    itemCount: "Dance",
  },
  {
    id: "kg6m5y-cs-004",
    name: "Summer Sunshine Set",
    price: "$26",
    image: "https://images.unsplash.com/photo-1712718228658-225eeb2bb7e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Bright and cheerful summer top and shorts set",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Sunshine Yellow", "Coral Pink", "Sky Blue"],
    brand: "Summer Rays",
    rating: 4.6,
    reviews: 156,
    features: ["Summer Theme", "Bright Colors", "Cheerful"],
    icon: "👗",
    itemCount: "Summer",
  },
  {
    id: "kg6m5y-cs-005",
    name: "Unicorn Magic Set",
    price: "$34",
    image: "https://images.unsplash.com/photo-1712718228658-225eeb2bb7e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Magical unicorn-themed shirt and leggings set",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Unicorn Rainbow", "Pink", "Purple", "White"],
    brand: "Unicorn Dreams",
    rating: 4.9,
    reviews: 267,
    features: ["Unicorn Theme", "Magical", "Rainbow Colors"],
    icon: "👗",
    itemCount: "Magical",
  },
  {
    id: "kg6m5y-cs-006",
    name: "Polka Dot Playdate Set",
    price: "$24",
    image: "https://images.unsplash.com/photo-1712718228658-225eeb2bb7e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic polka dot dress and cardigan combination",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy/White", "Red/White", "Pink/White"],
    brand: "Polka Dots",
    rating: 4.5,
    reviews: 123,
    features: ["Polka Dots", "Classic Style", "Playdate Ready"],
    icon: "👗",
    itemCount: "Classic",
  },
  {
    id: "kg6m5y-cs-007",
    name: "Mermaid Adventure Set",
    price: "$30",
    image: "https://images.unsplash.com/photo-1712718228658-225eeb2bb7e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Ocean-themed mermaid top and scale-print leggings",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Turquoise", "Ocean Blue", "Seafoam Green"],
    brand: "Ocean Dreams",
    rating: 4.7,
    reviews: 198,
    features: ["Mermaid Theme", "Ocean Inspired", "Scale Print"],
    icon: "👗",
    itemCount: "Ocean",
  },
  {
    id: "kg6m5y-cs-008",
    name: "Butterfly Garden Set",
    price: "$29",
    image: "https://images.unsplash.com/photo-1712718228658-225eeb2bb7e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Delicate butterfly print blouse and bloomers set",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Butterfly Pink", "Garden Green", "Sky Blue"],
    brand: "Flutter Dreams",
    rating: 4.6,
    reviews: 145,
    features: ["Butterfly Print", "Garden Theme", "Delicate"],
    icon: "👗",
    itemCount: "Nature",
  },
  {
    id: "kg6m5y-cs-009",
    name: "Rainbow Stripe Set",
    price: "$27",
    image: "https://images.unsplash.com/photo-1712718228658-225eeb2bb7e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Vibrant rainbow striped top and solid color bottom set",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Rainbow Stripe", "Bright Multi", "Pastel Rainbow"],
    brand: "Rainbow Kids",
    rating: 4.4,
    reviews: 167,
    features: ["Rainbow Stripes", "Vibrant", "Colorful"],
    icon: "👗",
    itemCount: "Colorful",
  },
  {
    id: "kg6m5y-cs-010",
    name: "Little Lady Formal Set",
    price: "$38",
    image: "https://images.unsplash.com/photo-1712718228658-225eeb2bb7e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sophisticated formal dress and jacket ensemble",
    category: "Co-Ord Sets",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy", "Black", "Burgundy", "Cream"],
    brand: "Little Lady",
    rating: 4.8,
    reviews: 134,
    features: ["Formal Style", "Sophisticated", "Special Occasion"],
    icon: "👗",
    itemCount: "Formal",
  }
];

export function KidsGirls6M5YCoordSetsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-pink-50 via-purple-50 to-rose-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6M-5Y Co-Ord Sets Collection" 
          subtitle="Perfectly Coordinated Outfits for Little Princesses"
          products={kidsGirls6M5YCoordSetsProducts} 
        />
      </main>
    </div>
  );
}