import { ProductGrid } from "../ProductGrid";

const kidsBoys6To14YShirtsProducts = [
  {
    id: "kb6-14y-s-001",
    name: "Oxford School Shirt",
    price: "$32",
    image: "https://i.pinimg.com/736x/1b/fc/fe/1bfcfe89eafa0f7ea75711a2eb0c2416.jpg",
    description: "Classic oxford shirt perfect for school and formal occasions",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Light Blue", "Navy", "Gray"],
    brand: "School Essential",
    rating: 4.8,
    reviews: 245,
    features: ["Oxford Fabric", "Button-Down", "School Ready"],
    icon: "👔",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6-14y-s-002",
    name: "Plaid Flannel Shirt",
    price: "$28",
    image: "https://i.pinimg.com/736x/b8/a4/24/b8a42488b2c58813745e6f027b5c481c.jpg",
    description: "Cozy plaid flannel shirt for casual cool weather",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Red Plaid", "Blue Plaid", "Green Plaid", "Gray Plaid"],
    brand: "Flannel Kids",
    rating: 4.7,
    reviews: 189,
    features: ["Flannel Fabric", "Plaid Pattern", "Cozy"],
    icon: "👔",
    itemCount: "Cozy",
  },
  {
    id: "kb6-14y-s-003",
    name: "Denim Button-Up",
    price: "$34",
    image: "https://i.pinimg.com/736x/d8/6e/01/d86e01276eae88b0cb2253d9405a87ab.jpg",
    description: "Classic denim shirt for casual everyday style",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Denim Co",
    rating: 4.6,
    reviews: 156,
    features: ["Denim Fabric", "Button-Up", "Casual Style"],
    icon: "👔",
    itemCount: "Casual",
  },
  {
    id: "kb6-14y-s-004",
    name: "Polo Collar Shirt",
    price: "$26",
    image: "https://i.pinimg.com/736x/7e/c5/65/7ec565f277680df4b1960db687486679.jpg",
    description: "Smart polo-style shirt with button placket",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Navy", "White", "Red", "Green"],
    brand: "Polo Kids",
    rating: 4.5,
    reviews: 123,
    features: ["Polo Collar", "Button Placket", "Smart Casual"],
    icon: "👔",
    itemCount: "Smart",
  },
  {
    id: "kb6-14y-s-005",
    name: "Striped Dress Shirt",
    price: "$30",
    image: "https://i.pinimg.com/736x/cf/a8/d8/cfa8d8c6023f4b33894e5f20fd88071c.jpg",
    description: "Elegant striped dress shirt for special occasions",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Blue Stripe", "Gray Stripe", "Pink Stripe"],
    brand: "Dress Up",
    rating: 4.4,
    reviews: 145,
    features: ["Striped Pattern", "Dress Shirt", "Elegant"],
    icon: "👔",
    itemCount: "Elegant",
  },
  {
    id: "kb6-14y-s-006",
    name: "Adventure Print Shirt",
    price: "$25",
    image: "https://i.pinimg.com/736x/1f/81/c8/1f81c8def14f43eae422e3d34f41ae13.jpg",
    description: "Fun adventure-themed print shirt for outdoor activities",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Khaki", "Olive", "Navy", "Brown"],
    brand: "Adventure Boys",
    rating: 4.6,
    reviews: 167,
    features: ["Adventure Print", "Outdoor Theme", "Fun"],
    icon: "👔",
    itemCount: "Adventure",
  },
  {
    id: "kb6-14y-s-007",
    name: "Formal White Shirt",
    price: "$35",
    image: "https://i.pinimg.com/736x/62/35/25/623525addd7852a604dfa6bb7a59d648.jpg",
    description: "Crisp white dress shirt for formal events and ceremonies",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["White", "Off-White", "Cream"],
    brand: "Formal Wear",
    rating: 4.9,
    reviews: 134,
    features: ["Formal Style", "Crisp White", "Premium"],
    icon: "👔",
    itemCount: "Formal",
  },
  {
    id: "kb6-14y-s-008",
    name: "Hawaiian Print Shirt",
    price: "$27",
    image: "https://i.pinimg.com/1200x/41/4b/39/414b390acb97e0a7a167a585220bbd3b.jpg",
    description: "Tropical Hawaiian print shirt for vacation vibes",
    category: "Shirts",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Tropical Blue", "Palm Green", "Sunset Orange"],
    brand: "Island Style",
    rating: 4.3,
    reviews: 112,
    features: ["Hawaiian Print", "Tropical", "Vacation Style"],
    icon: "👔",
    itemCount: "Tropical",
  }
];

export function KidsBoys6To14YShirtsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6-14Y Shirts Collection" 
          subtitle="Smart & Stylish Shirts for Growing Boys"
          products={kidsBoys6To14YShirtsProducts} 
        />
      </main>
    </div>
  );
}
