import { ProductGrid } from "../ProductGrid";

const kidsBoys6To14YJeansProducts = [
  {
    id: "kb6-14y-j-001",
    name: "Classic Straight Jeans",
    price: "$34",
    image: "https://i.pinimg.com/1200x/cc/03/30/cc0330dc32a3d0244ee60e4221c08328.jpg",
    description: "Timeless straight leg jeans for everyday wear",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Classic Blue", "Dark Wash", "Medium Blue", "Light Blue"],
    brand: "Classic Denim",
    rating: 4.8,
    reviews: 312,
    features: ["Straight Leg", "Classic Fit", "Timeless"],
    icon: "👖",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kb6-14y-j-002",
    name: "Slim Fit Modern Jeans",
    price: "$36",
    image: "https://i.pinimg.com/736x/32/3c/59/323c5913c0dfdfa59b8c52560a269f83.jpg",
    description: "Modern slim fit jeans for trendy boys",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Modern Blue", "Slim Dark", "Trendy Medium"],
    brand: "Modern Fit",
    rating: 4.7,
    reviews: 234,
    features: ["Slim Fit", "Modern Style", "Trendy"],
    icon: "👖",
    itemCount: "Modern",
  },
  {
    id: "kb6-14y-j-003",
    name: "Distressed Cool Jeans",
    price: "$32",
    image: "https://i.pinimg.com/736x/83/c0/94/83c0947a20e57d3065d53f81d399e261.jpg",
    description: "Cool distressed jeans with edgy style",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Light Distressed", "Medium Distressed", "Cool Worn"],
    brand: "Edgy Style",
    rating: 4.6,
    reviews: 189,
    features: ["Distressed Style", "Cool", "Edgy"],
    icon: "👖",
    itemCount: "Cool",
  },
  {
    id: "kb6-14y-j-004",
    name: "Stretch Comfort Jeans",
    price: "$35",
    image: "https://amyfashionshop.com/cdn/shop/files/amy-fashion-wide-y2k-vintage-baggy-distressed-streetwear-denim-jean-blue-xs-648.webp?v=1735139126&width=600",
    description: "Super comfortable stretch jeans for active boys",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Stretch Blue", "Comfort Dark", "Active Medium"],
    brand: "Stretch Comfort",
    rating: 4.8,
    reviews: 198,
    features: ["Stretch Fabric", "Comfort", "Active"],
    icon: "👖",
    itemCount: "Comfort",
  },
  {
    id: "kb6-14y-j-005",
    name: "Raw Denim Classic",
    price: "$38",
    image: "https://i.pinimg.com/736x/7a/06/51/7a0651a0820ecf3a57e958f29b537cae.jpg",
    description: "Premium raw denim jeans for style enthusiasts",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Raw Indigo", "Deep Blue", "Classic Raw"],
    brand: "Raw Denim Co",
    rating: 4.5,
    reviews: 167,
    features: ["Raw Denim", "Premium", "Classic"],
    icon: "👖",
    itemCount: "Premium",
  },
  {
    id: "kb6-14y-j-006",
    name: "Cargo Denim Jeans",
    price: "$37",
    image: "https://i.pinimg.com/736x/3d/39/9c/3d399c3e8fd8218bdc3a90d16ea62ddb.jpg",
    description: "Functional cargo-style jeans with extra pockets",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Cargo Blue", "Utility Dark", "Pocket Medium"],
    brand: "Cargo Denim",
    rating: 4.4,
    reviews: 145,
    features: ["Cargo Style", "Extra Pockets", "Functional"],
    icon: "👖",
    itemCount: "Cargo",
  },
  {
    id: "kb6-14y-j-007",
    name: "Vintage Wash Jeans",
    price: "$33",
    image: "https://i.pinimg.com/736x/a7/54/26/a7542697534918968c4398f9da2dc10e.jpg",
    description: "Retro vintage wash jeans with classic appeal",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Vintage Blue", "Retro Wash", "Classic Fade"],
    brand: "Vintage Vibes",
    rating: 4.3,
    reviews: 156,
    features: ["Vintage Wash", "Retro Style", "Classic"],
    icon: "👖",
    itemCount: "Vintage",
  },
  {
    id: "kb6-14y-j-008",
    name: "Athletic Denim Jeans",
    price: "$39",
    image: "https://i.pinimg.com/736x/68/95/06/6895069dde7bfdaad03709ee877b6819.jpg",
    description: "Performance denim jeans for athletic boys",
    category: "Jeans",
    sizes: ["6Y", "7Y", "8Y", "9Y", "10Y", "12Y", "14Y"],
    colors: ["Athletic Blue", "Sport Dark", "Performance Medium"],
    brand: "Athletic Denim",
    rating: 4.6,
    reviews: 123,
    features: ["Athletic Denim", "Performance", "Sport"],
    icon: "👖",
    itemCount: "Athletic",
  },
];

export function KidsBoys6To14YJeansPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-gray-50 to-green-50">
      <main className="flex-1">
        <ProductGrid 
          title="Boys 6-14Y Jeans Collection" 
          subtitle="Classic & Modern Jeans for Every Style"
          products={kidsBoys6To14YJeansProducts} 
        />
      </main>
    </div>
  );
}