import { ProductGrid } from "../ProductGrid";

const kidsGirls6M5YDressesJumpsuitsProducts = [
  {
    id: "kg6m5y-dj-001",
    name: "Princess Party Dress",
    price: "$28",
    image: "https://images.unsplash.com/photo-1725147874578-fc76e0d865e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWJ5JTIwYm95JTIwb3V0Zml0fGVufDF8fHx8MTc1NTE4OTQ5M3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Magical princess dress perfect for special occasions",
    category: "Dresses & Jumpsuits",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Purple", "Blue", "White"],
    brand: "Little Princess",
    rating: 4.9,
    reviews: 267,
    features: ["Tulle Skirt", "Sparkle Details", "Special Occasion"],
    icon: "👗",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6m5y-dj-002",
    name: "Floral Summer Dress",
    price: "$22",
    image: "https://images.unsplash.com/photo-1725147874578-fc76e0d865e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sweet floral dress perfect for sunny days",
    category: "Dresses & Jumpsuits",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink Floral", "Yellow Floral", "Blue Floral"],
    brand: "Garden Party",
    rating: 4.7,
    reviews: 189,
    features: ["Floral Print", "Lightweight", "Summer Ready"],
    icon: "👗",
    itemCount: "Summer",
  },
  {
    id: "kg6m5y-dj-003",
    name: "Denim Jumpsuit",
    price: "$26",
    image: "https://images.unsplash.com/photo-1725147874578-fc76e0d865e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Adorable denim jumpsuit for playful adventures",
    category: "Dresses & Jumpsuits",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Denim", "Medium Denim", "Dark Denim"],
    brand: "Little Explorer",
    rating: 4.6,
    reviews: 156,
    features: ["Denim Fabric", "Adjustable Straps", "Playful"],
    icon: "👗",
    itemCount: "Adventure",
  },
  {
    id: "kg6m5y-dj-004",
    name: "Rainbow Tutu Dress",
    price: "$24",
    image: "https://images.unsplash.com/photo-1725147874578-fc76e0d865e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Colorful rainbow tutu dress for magical moments",
    category: "Dresses & Jumpsuits",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Rainbow", "Pink Rainbow", "Purple Rainbow"],
    brand: "Rainbow Magic",
    rating: 4.8,
    reviews: 198,
    features: ["Rainbow Colors", "Tutu Style", "Magical"],
    icon: "👗",
    itemCount: "Magical",
  },
  {
    id: "kg6m5y-dj-005",
    name: "Polka Dot Dress",
    price: "$20",
    image: "https://images.unsplash.com/photo-1725147874578-fc76e0d865e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic polka dot dress with vintage charm",
    category: "Dresses & Jumpsuits",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy/White", "Red/White", "Pink/White"],
    brand: "Vintage Baby",
    rating: 4.5,
    reviews: 123,
    features: ["Polka Dots", "Vintage Style", "Classic"],
    icon: "👗",
    itemCount: "Classic",
  },
  {
    id: "kg6m5y-dj-006",
    name: "Butterfly Romper",
    price: "$18",
    image: "https://images.unsplash.com/photo-1725147874578-fc76e0d865e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cute butterfly-themed romper for active play",
    category: "Dresses & Jumpsuits",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pink", "Purple", "Yellow", "Green"],
    brand: "Flutter Kids",
    rating: 4.4,
    reviews: 87,
    features: ["Butterfly Theme", "Romper Style", "Comfortable"],
    icon: "👗",
    itemCount: "Nature",
  },
  {
    id: "kg6m5y-dj-007",
    name: "Unicorn Fantasy Dress",
    price: "$30",
    image: "https://images.unsplash.com/photo-1725147874578-fc76e0d865e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Enchanting unicorn dress with magical details",
    category: "Dresses & Jumpsuits",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Pastel Rainbow", "Pink", "Purple", "White"],
    brand: "Unicorn Dreams",
    rating: 4.9,
    reviews: 234,
    features: ["Unicorn Theme", "Glitter Details", "Fantasy"],
    icon: "👗",
    itemCount: "Fantasy",
  },
  {
    id: "kg6m5y-dj-008",
    name: "Striped Pinafore",
    price: "$25",
    image: "https://images.unsplash.com/photo-1725147874578-fc76e0d865e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic striped pinafore dress for school or play",
    category: "Dresses & Jumpsuits",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Navy/White", "Red/White", "Pink/White"],
    brand: "School Days",
    rating: 4.6,
    reviews: 145,
    features: ["Striped Pattern", "Pinafore Style", "School Ready"],
    icon: "👗",
    itemCount: "School",
  },
  {
    id: "kg6m5y-dj-009",
    name: "Mermaid Tail Dress",
    price: "$27",
    image: "https://images.unsplash.com/photo-1725147874578-fc76e0d865e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Shimmery mermaid-inspired dress for imaginative play",
    category: "Dresses & Jumpsuits",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Turquoise", "Purple", "Pink", "Green"],
    brand: "Ocean Dreams",
    rating: 4.7,
    reviews: 167,
    features: ["Mermaid Theme", "Shimmer Fabric", "Ocean Inspired"],
    icon: "👗",
    itemCount: "Ocean",
  },
  {
    id: "kg6m5y-dj-010",
    name: "Casual Play Jumpsuit",
    price: "$21",
    image: "https://images.unsplash.com/photo-1725147874578-fc76e0d865e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Comfortable jumpsuit perfect for everyday adventures",
    category: "Dresses & Jumpsuits",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Gray", "Navy", "Pink", "Yellow"],
    brand: "Play Time",
    rating: 4.3,
    reviews: 112,
    features: ["Casual Style", "Comfortable Fit", "Play Ready"],
    icon: "👗",
    itemCount: "Casual",
  }
];

export function KidsGirls6M5YDressesJumpsuitsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-pink-50 via-purple-50 to-blue-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6M-5Y Dresses & Jumpsuits Collection" 
          subtitle="Magical & Adorable Styles for Little Princesses"
          products={kidsGirls6M5YDressesJumpsuitsProducts} 
        />
      </main>
    </div>
  );
}