import { ProductGrid } from "../ProductGrid";

const kidsGirls6M5YJeansProducts = [
  {
    id: "kg6m5y-j-001",
    name: "Princess Pink Jeans",
    price: "$24",
    image: "https://images.unsplash.com/photo-1566513857792-9a52cd97e06d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b2RkbGVyJTIwZ2lybCUyMGplYW5zfGVufDF8fHx8MTc1NTE5MDc0MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Adorable pink-tinted jeans perfect for little princesses",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Princess Pink", "Light Pink", "Rose Pink"],
    brand: "Princess Denim",
    rating: 4.8,
    reviews: 245,
    features: ["Pink Wash", "Soft Denim", "Princess Style"],
    icon: "👖",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "kg6m5y-j-002",
    name: "Flower Embroidered Jeans",
    price: "$28",
    image: "https://images.unsplash.com/photo-1566513857792-9a52cd97e06d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sweet jeans with delicate flower embroidery details",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Blue", "White", "Pink"],
    brand: "Flower Power",
    rating: 4.7,
    reviews: 198,
    features: ["Flower Embroidery", "Delicate Details", "Sweet"],
    icon: "👖",
    itemCount: "Floral",
  },
  {
    id: "kg6m5y-j-003",
    name: "Stretch Comfort Jeans",
    price: "$26",
    image: "https://images.unsplash.com/photo-1566513857792-9a52cd97e06d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Super stretchy jeans for active little girls",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Medium Blue", "Dark Blue", "Light Blue"],
    brand: "Stretch Kids",
    rating: 4.6,
    reviews: 167,
    features: ["Stretch Fabric", "Active Wear", "Comfortable"],
    icon: "👖",
    itemCount: "Stretch",
  },
  {
    id: "kg6m5y-j-004",
    name: "Skinny Fit Jeans",
    price: "$25",
    image: "https://images.unsplash.com/photo-1566513857792-9a52cd97e06d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy skinny fit jeans for fashionable toddlers",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Dark Blue", "Black", "Light Blue"],
    brand: "Trendy Tots",
    rating: 4.5,
    reviews: 134,
    features: ["Skinny Fit", "Trendy", "Fashionable"],
    icon: "👖",
    itemCount: "Trendy",
  },
  {
    id: "kg6m5y-j-005",
    name: "Heart Pocket Jeans",
    price: "$27",
    image: "https://images.unsplash.com/photo-1566513857792-9a52cd97e06d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cute jeans with heart-shaped pocket details",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Medium Blue", "Pink Blue", "Light Blue"],
    brand: "Heart & Soul",
    rating: 4.7,
    reviews: 156,
    features: ["Heart Pockets", "Cute Details", "Adorable"],
    icon: "👖",
    itemCount: "Cute",
  },
  {
    id: "kg6m5y-j-006",
    name: "Distressed Play Jeans",
    price: "$23",
    image: "https://images.unsplash.com/photo-1566513857792-9a52cd97e06d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Cool distressed jeans perfect for playground adventures",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Wash", "Medium Wash", "Vintage Blue"],
    brand: "Play Time",
    rating: 4.4,
    reviews: 123,
    features: ["Distressed Style", "Playground Ready", "Cool"],
    icon: "👖",
    itemCount: "Cool",
  },
  {
    id: "kg6m5y-j-007",
    name: "Rainbow Stitching Jeans",
    price: "$29",
    image: "https://images.unsplash.com/photo-1566513857792-9a52cd97e06d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Fun jeans with colorful rainbow stitching details",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Blue Rainbow", "Pink Rainbow", "White Rainbow"],
    brand: "Rainbow Kids",
    rating: 4.6,
    reviews: 189,
    features: ["Rainbow Stitching", "Colorful", "Fun"],
    icon: "👖",
    itemCount: "Rainbow",
  },
  {
    id: "kg6m5y-j-008",
    name: "Bow Tie Jeans",
    price: "$26",
    image: "https://images.unsplash.com/photo-1566513857792-9a52cd97e06d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Charming jeans with decorative bow tie details",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Medium Blue", "Light Blue", "Pink Blue"],
    brand: "Bow Beauty",
    rating: 4.5,
    reviews: 145,
    features: ["Bow Tie Details", "Charming", "Decorative"],
    icon: "👖",
    itemCount: "Charming",
  },
  {
    id: "kg6m5y-j-009",
    name: "Pull-On Jeggings",
    price: "$22",
    image: "https://images.unsplash.com/photo-1566513857792-9a52cd97e06d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Easy pull-on jeggings that look like real jeans",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Dark Blue", "Medium Blue", "Black"],
    brand: "Easy Wear",
    rating: 4.8,
    reviews: 234,
    features: ["Pull-On Style", "Jeggings", "Easy Dressing"],
    icon: "👖",
    itemCount: "Easy",
  },
  {
    id: "kg6m5y-j-010",
    name: "Butterfly Patch Jeans",
    price: "$30",
    image: "https://images.unsplash.com/photo-1566513857792-9a52cd97e06d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Magical jeans with beautiful butterfly patches",
    category: "Jeans",
    sizes: ["6M", "12M", "18M", "2T", "3T", "4T", "5T"],
    colors: ["Light Blue", "White", "Pink"],
    brand: "Butterfly Dreams",
    rating: 4.9,
    reviews: 178,
    features: ["Butterfly Patches", "Magical", "Beautiful"],
    icon: "👖",
    itemCount: "Magical",
  }
];

export function KidsGirls6M5YJeansPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-pink-50 via-blue-50 to-purple-50">
      <main className="flex-1">
        <ProductGrid 
          title="Girls 6M-5Y Jeans Collection" 
          subtitle="Stylish & Comfortable Jeans for Little Fashionistas"
          products={kidsGirls6M5YJeansProducts} 
        />
      </main>
    </div>
  );
}