import { ProductGrid } from "../ProductGrid";

const menAccessoriesProducts = [
  {
    id: "ma-001",
    name: "Chronograph Steel Watch",
    price: "$245",
    image: "https://www.analogshift.com/cdn/shop/files/AS09205_40960209_OMEGA_SPEEDMASTERPROFESSIONAL_310.30.41.50.01.001-6.jpg?v=1699634934&width=1445",
    description: "Premium chronograph watch with stainless steel band",
    category: "Watches",
    sizes: ["One Size"],
    colors: ["Steel Silver", "Black Steel", "Rose Gold"],
    brand: "TimeKeeper Pro",
    rating: 4.9,
    reviews: 324,
    features: ["Water Resistant", "Chronograph", "Steel Band"],
    icon: "⌚",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "ma-002",
    name: "Aviator Sunglasses",
    price: "$98",
    image: "https://images.unsplash.com/photo-1740704407322-9cad53777a52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic aviator sunglasses with UV protection",
    category: "Sunglasses",
    sizes: ["One Size"],
    colors: ["Gold Frame", "Silver Frame", "Black Frame"],
    brand: "Vision Elite",
    rating: 4.7,
    reviews: 289,
    features: ["UV Protection", "Polarized", "Classic Design"],
    icon: "🕶️",
    itemCount: "Classic",
  },
  {
    id: "ma-003",
    name: "Leather Baseball Cap",
    price: "$65",
    image: "https://images.unsplash.com/photo-1740704407322-9cad53777a52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Premium leather baseball cap with adjustable strap",
    category: "Caps",
    sizes: ["One Size"],
    colors: ["Black Leather", "Brown Leather", "Navy Leather"],
    brand: "Cap Master",
    rating: 4.6,
    reviews: 198,
    features: ["Genuine Leather", "Adjustable", "Premium"],
    icon: "🧢",
    itemCount: "Premium",
  },
  {
    id: "ma-004",
    name: "Italian Leather Belt",
    price: "$89",
    image: "https://images.unsplash.com/photo-1740704407322-9cad53777a52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Handcrafted Italian leather belt with silver buckle",
    category: "Belts",
    sizes: ["32", "34", "36", "38", "40", "42"],
    colors: ["Black", "Brown", "Cognac"],
    brand: "Milano Leather",
    rating: 4.8,
    reviews: 234,
    features: ["Italian Leather", "Handcrafted", "Silver Buckle"],
    icon: "👔",
    itemCount: "Italian",
  },
  {
    id: "ma-005",
    name: "Wireless Earbuds Pro",
    price: "$159",
    image: "https://images.unsplash.com/photo-1740704407322-9cad53777a52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Premium wireless earbuds with noise cancellation",
    category: "Tech",
    sizes: ["One Size"],
    colors: ["Space Black", "Silver", "Gold"],
    brand: "Audio Elite",
    rating: 4.5,
    reviews: 167,
    features: ["Noise Cancellation", "Wireless", "Premium Audio"],
    icon: "🎧",
    itemCount: "Tech",
  },
  {
    id: "ma-006",
    name: "Silk Pocket Square",
    price: "$34",
    image: "https://images.unsplash.com/photo-1740704407322-9cad53777a52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant silk pocket square for formal occasions",
    category: "Formal",
    sizes: ["One Size"],
    colors: ["Navy Silk", "Burgundy Silk", "Silver Silk"],
    brand: "Gentleman's Choice",
    rating: 4.4,
    reviews: 145,
    features: ["100% Silk", "Formal", "Elegant"],
    icon: "🎩",
    itemCount: "Elegant",
  },
  {
    id: "ma-007",
    name: "Carbon Fiber Wallet",
    price: "$72",
    image: "https://images.unsplash.com/photo-1740704407322-9cad53777a52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Modern carbon fiber wallet with RFID protection",
    category: "Wallets",
    sizes: ["One Size"],
    colors: ["Carbon Black", "Carbon Gray", "Carbon Blue"],
    brand: "Modern Wallet Co",
    rating: 4.6,
    reviews: 198,
    features: ["Carbon Fiber", "RFID Protection", "Modern"],
    icon: "💳",
    itemCount: "Modern",
  },
  {
    id: "ma-008",
    name: "Luxury Cufflinks Set",
    price: "$125",
    image: "https://images.unsplash.com/photo-1740704407322-9cad53777a52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sterling silver cufflinks with elegant design",
    category: "Formal",
    sizes: ["One Size"],
    colors: ["Sterling Silver", "Gold Plated", "Black Onyx"],
    brand: "Sterling Luxury",
    rating: 4.7,
    reviews: 156,
    features: ["Sterling Silver", "Luxury", "Elegant Design"],
    icon: "💎",
    itemCount: "Luxury",
  },
  {
    id: "ma-009",
    name: "Titanium Bracelet",
    price: "$112",
    image: "https://images.unsplash.com/photo-1740704407322-9cad53777a52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Lightweight titanium bracelet with magnetic clasp",
    category: "Jewelry",
    sizes: ["S", "M", "L"],
    colors: ["Titanium Gray", "Black Titanium", "Brushed Silver"],
    brand: "Titanium Works",
    rating: 4.3,
    reviews: 123,
    features: ["Titanium Metal", "Magnetic Clasp", "Lightweight"],
    icon: "📿",
    itemCount: "Tech",
  },
  {
    id: "ma-010",
    name: "Cashmere Scarf",
    price: "$86",
    image: "https://images.unsplash.com/photo-1740704407322-9cad53777a52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Luxurious cashmere scarf for winter elegance",
    category: "Scarves",
    sizes: ["One Size"],
    colors: ["Charcoal Gray", "Navy Blue", "Camel Brown"],
    brand: "Cashmere Luxury",
    rating: 4.8,
    reviews: 178,
    features: ["100% Cashmere", "Winter Ready", "Luxurious"],
    icon: "🧣",
    itemCount: "Luxury",
  }
];

export function MenAccessoriesPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-gray-50 to-purple-50">
      <main className="flex-1">
        <ProductGrid 
          title="Men's Accessories Collection" 
          subtitle="Premium Accessories for the Modern Gentleman"
          products={menAccessoriesProducts} 
        />
      </main>
    </div>
  );
}
