import { ProductGrid } from "../ProductGrid";

const menAccessoriesProducts = [
  {
    id: "ma-001",
    name: "Chronograph Steel Watch",
    price: "$245",
    image: "https://www.analogshift.com/cdn/shop/files/AS09205_40960209_OMEGA_SPEEDMASTERPROFESSIONAL_310.30.41.50.01.001-6.jpg?v=1699634934&width=1445",
    description: "Premium chronograph watch with stainless steel band",
    category: "Watches",
    sizes: ["One Size"],
    colors: ["Steel Silver", "Black Steel", "Rose Gold"],
    brand: "TimeKeeper Pro",
    rating: 4.9,
    reviews: 324,
    features: ["Water Resistant", "Chronograph", "Steel Band"],
    icon: "⌚",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "ma-002",
    name: "Aviator Sunglasses",
    price: "$98",
    image: "https://www.themodestman.com/wp-content/uploads/2022/04/Best-Ray-Bans-For-Narrow-Faces.jpg",
    description: "Classic aviator sunglasses with UV protection",
    category: "Sunglasses",
    sizes: ["One Size"],
    colors: ["Gold Frame", "Silver Frame", "Black Frame"],
    brand: "Vision Elite",
    rating: 4.7,
    reviews: 289,
    features: ["UV Protection", "Polarized", "Classic Design"],
    icon: "🕶️",
    itemCount: "Classic",
  },
  {
    id: "ma-003",
    name: "Leather Baseball Cap",
    price: "$65",
    image: "https://media.neimanmarcus.com/f_auto,q_auto:low,ar_4:5,c_fill,dpr_2.0,w_270/01/nm_4714002_100106_m",
    description: "Premium leather baseball cap with adjustable strap",
    category: "Caps",
    sizes: ["One Size"],
    colors: ["Black Leather", "Brown Leather", "Navy Leather"],
    brand: "Cap Master",
    rating: 4.6,
    reviews: 198,
    features: ["Genuine Leather", "Adjustable", "Premium"],
    icon: "🧢",
    itemCount: "Premium",
  },
  {
    id: "ma-004",
    name: "Italian Leather Belt",
    price: "$89",
    image: "https://naiwear.com/cdn/shop/products/image_d81381f0-882b-4de8-bdc6-2b7bbf6bbf2b.jpg?v=1660159423",
    description: "Handcrafted Italian leather belt with silver buckle",
    category: "Belts",
    sizes: ["32", "34", "36", "38", "40", "42"],
    colors: ["Black", "Brown", "Cognac"],
    brand: "Milano Leather",
    rating: 4.8,
    reviews: 234,
    features: ["Italian Leather", "Handcrafted", "Silver Buckle"],
    icon: "👔",
    itemCount: "Italian",
  },
  {
    id: "ma-005",
    name: "Wireless Earbuds Pro",
    price: "$159",
    image: "https://helios-i.mashable.com/imagery/articles/03Pp9XQh1IlX1ewKhUCTZjP/hero-image.fill.size_1200x900.v1754907647.jpg",
    description: "Premium wireless earbuds with noise cancellation",
    category: "Tech",
    sizes: ["One Size"],
    colors: ["Space Black", "Silver", "Gold"],
    brand: "Audio Elite",
    rating: 4.5,
    reviews: 167,
    features: ["Noise Cancellation", "Wireless", "Premium Audio"],
    icon: "🎧",
    itemCount: "Tech",
  },
  {
    id: "ma-006",
    name: "Silk Pocket Square",
    price: "$34",
    image: "https://www.threaditionz.com/cdn/shop/products/E_23.jpg?v=1683886660",
    description: "Elegant silk pocket square for formal occasions",
    category: "Formal",
    sizes: ["One Size"],
    colors: ["Navy Silk", "Burgundy Silk", "Silver Silk"],
    brand: "Gentleman's Choice",
    rating: 4.4,
    reviews: 145,
    features: ["100% Silk", "Formal", "Elegant"],
    icon: "🎩",
    itemCount: "Elegant",
  },
  {
    id: "ma-007",
    name: "Carbon Fiber Wallet",
    price: "$72",
    image: "https://i.ebayimg.com/images/g/bZ4AAOSwy6Fj7yrn/s-l1200.jpg",
    description: "Modern carbon fiber wallet with RFID protection",
    category: "Wallets",
    sizes: ["One Size"],
    colors: ["Carbon Black", "Carbon Gray", "Carbon Blue"],
    brand: "Modern Wallet Co",
    rating: 4.6,
    reviews: 198,
    features: ["Carbon Fiber", "RFID Protection", "Modern"],
    icon: "💳",
    itemCount: "Modern",
  },
  {
    id: "ma-008",
    name: "Luxury Cufflinks Set",
    price: "$125",
    image: "https://i.ebayimg.com/images/g/xaIAAOSwJXhm4~i1/s-l1200.jpg",
    description: "Sterling silver cufflinks with elegant design",
    category: "Formal",
    sizes: ["One Size"],
    colors: ["Sterling Silver", "Gold Plated", "Black Onyx"],
    brand: "Sterling Luxury",
    rating: 4.7,
    reviews: 156,
    features: ["Sterling Silver", "Luxury", "Elegant Design"],
    icon: "💎",
    itemCount: "Luxury",
  },
  {
    id: "ma-009",
    name: "Titanium Bracelet",
    price: "$112",
    image: "https://www.h2o-watch.com/media/wysiwyg/titanium_bracelet_24mm_by_h2o/h2o_titanium_bracelet_24mm_001.jpg",
    description: "Lightweight titanium bracelet with magnetic clasp",
    category: "Jewelry",
    sizes: ["S", "M", "L"],
    colors: ["Titanium Gray", "Black Titanium", "Brushed Silver"],
    brand: "Titanium Works",
    rating: 4.3,
    reviews: 123,
    features: ["Titanium Metal", "Magnetic Clasp", "Lightweight"],
    icon: "📿",
    itemCount: "Tech",
  },
  {
    id: "ma-010",
    name: "Cashmere Scarf",
    price: "$86",
    image: "https://img4.dhresource.com/webp/m/0x0/f3/albu/jc/z/24/7f687354-624b-41b7-829a-c10918dfba65.jpg",
    description: "Luxurious cashmere scarf for winter elegance",
    category: "Scarves",
    sizes: ["One Size"],
    colors: ["Charcoal Gray", "Navy Blue", "Camel Brown"],
    brand: "Cashmere Luxury",
    rating: 4.8,
    reviews: 178,
    features: ["100% Cashmere", "Winter Ready", "Luxurious"],
    icon: "🧣",
    itemCount: "Luxury",
  }
];

export function MenAccessoriesPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-gray-50 to-purple-50">
      <main className="flex-1">
        <ProductGrid 
          title="Men's Accessories Collection" 
          subtitle="Premium Accessories for the Modern Gentleman"
          products={menAccessoriesProducts} 
        />
      </main>
    </div>
  );
}
