import { motion } from "framer-motion";
import { Crown, ArrowRight, Star } from "lucide-react";
import { Button } from "../ui/button";
import { AnimatedEmoji } from "../animations";
import { ProductGrid } from "../ProductGrid";

const womenDressesAndJumpsuitsProducts = [
  {
    id: "wdj-001",
    name: "Wrap Midi Dress",
    price: "$68",
    image: "https://images.unsplash.com/photo-1664151100543-831e51069d1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21lbiUyMGRyZXNzJTIwanVtcHN1aXR8ZW58MXx8fHwxNzU1MTg4ODk1fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Elegant wrap midi dress perfect for work or dinner",
    category: "Dresses & Jumpsuits",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy", "Black", "Burgundy", "Emerald"],
    brand: "Elegant Styles",
    rating: 4.8,
    reviews: 298,
    features: ["Wrap Design", "Midi Length", "Versatile"],
    icon: <Crown className="w-6 h-6" />,
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "wdj-002",
    name: "Wide-Leg Jumpsuit",
    price: "$85",
    image: "https://images.unsplash.com/photo-1664151100543-831e51069d1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sophisticated wide-leg jumpsuit with belt detail",
    category: "Dresses & Jumpsuits",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Olive", "Camel"],
    brand: "Modern Classic",
    rating: 4.7,
    reviews: 234,
    features: ["Wide-Leg", "Belt Detail", "Sophisticated"],
    icon: <Crown className="w-6 h-6" />,
    itemCount: "Sophisticated",
  },
  {
    id: "wdj-003",
    name: "Floral Maxi Dress",
    price: "$72",
    image: "https://images.unsplash.com/photo-1664151100543-831e51069d1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Romantic floral maxi dress with flowing silhouette",
    category: "Dresses & Jumpsuits",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Floral Print", "Paisley", "Tropical", "Garden"],
    brand: "Romantic Style",
    rating: 4.6,
    reviews: 189,
    features: ["Floral Print", "Maxi Length", "Flowing"],
    icon: <Crown className="w-6 h-6" />,
    itemCount: "Romantic",
  },
  {
    id: "wdj-004",
    name: "Little Black Dress",
    price: "$95",
    image: "https://images.unsplash.com/photo-1664151100543-831e51069d1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Timeless little black dress for every occasion",
    category: "Dresses & Jumpsuits",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black"],
    brand: "Timeless Elegance",
    rating: 4.9,
    reviews: 456,
    features: ["Classic Cut", "Versatile", "Timeless"],
    icon: <Crown className="w-6 h-6" />,
    itemCount: "Classic",
  },
  {
    id: "wdj-005",
    name: "Casual T-Shirt Dress",
    price: "$42",
    image: "https://images.unsplash.com/photo-1664151100543-831e51069d1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Comfortable t-shirt dress perfect for everyday wear",
    category: "Dresses & Jumpsuits",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Gray", "Navy", "White", "Sage"],
    brand: "Casual Comfort",
    rating: 4.5,
    reviews: 267,
    features: ["T-Shirt Style", "Comfortable", "Casual"],
    icon: <Crown className="w-6 h-6" />,
    itemCount: "Casual",
  },
  {
    id: "wdj-006",
    name: "Denim Jumpsuit",
    price: "$78",
    image: "https://images.unsplash.com/photo-1664151100543-831e51069d1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy denim jumpsuit with vintage-inspired styling",
    category: "Dresses & Jumpsuits",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Wash", "Medium Wash", "Dark Wash"],
    brand: "Denim Dreams",
    rating: 4.4,
    reviews: 178,
    features: ["Denim Fabric", "Vintage Style", "Trendy"],
    icon: <Crown className="w-6 h-6" />,
    itemCount: "Trendy",
  },
  {
    id: "wdj-007",
    name: "Cocktail Dress",
    price: "$125",
    image: "https://images.unsplash.com/photo-1664151100543-831e51069d1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Glamorous cocktail dress perfect for special events",
    category: "Dresses & Jumpsuits",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy", "Emerald"],
    brand: "Glamour Collection",
    rating: 4.8,
    reviews: 134,
    features: ["Cocktail Style", "Glamorous", "Special Occasion"],
    icon: <Crown className="w-6 h-6" />,
    itemCount: "Glamour",
  },
  {
    id: "wdj-008",
    name: "Off-Shoulder Romper",
    price: "$58",
    image: "https://images.unsplash.com/photo-1664151100543-831e51069d1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Playful off-shoulder romper perfect for summer",
    category: "Dresses & Jumpsuits",
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Coral", "Navy", "Floral"],
    brand: "Summer Romance",
    rating: 4.5,
    reviews: 198,
    features: ["Off-Shoulder", "Romper Style", "Summer"],
    icon: <Crown className="w-6 h-6" />,
    itemCount: "Summer",
  },
  {
    id: "wdj-009",
    name: "Shirt Dress",
    price: "$62",
    image: "https://images.unsplash.com/photo-1664151100543-831e51069d1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Professional shirt dress with button-front detail",
    category: "Dresses & Jumpsuits",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Navy", "Striped", "Khaki"],
    brand: "Professional Style",
    rating: 4.7,
    reviews: 223,
    features: ["Button-Front", "Professional", "Versatile"],
    icon: <Crown className="w-6 h-6" />,
    itemCount: "Professional",
  },
  {
    id: "wdj-010",
    name: "Halter Jumpsuit",
    price: "$89",
    image: "https://images.unsplash.com/photo-1664151100543-831e51069d1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Chic halter jumpsuit perfect for evening occasions",
    category: "Dresses & Jumpsuits",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy", "Forest"],
    brand: "Evening Chic",
    rating: 4.6,
    reviews: 156,
    features: ["Halter Style", "Evening Wear", "Chic"],
    icon: <Crown className="w-6 h-6" />,
    itemCount: "Evening",
  }
];

export function WomenDressesAndJumpsuitsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-purple-50 via-rose-50 to-amber-50">
      <main className="flex-1">
        <ProductGrid 
          title="Women's Dresses & Jumpsuits Collection" 
          subtitle="Elegant One-Piece Styles"
          products={womenDressesAndJumpsuitsProducts} 
        />
      </main>
    </div>
  );
}