import { ProductGrid } from "../ProductGrid";

const womenTrousersProducts = [
  {
    id: "wtr-001",
    name: "Wide-Leg Trousers",
    price: "$68",
    image: "https://images.unsplash.com/photo-1699205016746-8aa2e6e48453?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21lbiUyMHRyb3VzZXJzJTIwcGFudHN8ZW58MXx8fHwxNzU1MTg4OTA2fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Elegant wide-leg trousers perfect for professional wear",
    category: "Trousers",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Camel", "Gray"],
    brand: "Professional Elegance",
    rating: 4.8,
    reviews: 298,
    features: ["Wide-Leg", "Professional", "Elegant"],
    icon: "👖",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "wtr-002",
    name: "High-Waisted Straight Leg",
    price: "$58",
    image: "https://images.unsplash.com/photo-1699205016746-8aa2e6e48453?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic high-waisted straight leg trousers",
    category: "Trousers",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy", "Olive"],
    brand: "Classic Fit",
    rating: 4.7,
    reviews: 234,
    features: ["High-Waisted", "Straight Leg", "Classic"],
    icon: "👖",
    itemCount: "Classic",
  },
  {
    id: "wtr-003",
    name: "Cropped Ankle Pants",
    price: "$52",
    image: "https://images.unsplash.com/photo-1699205016746-8aa2e6e48453?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Modern cropped ankle pants with tapered fit",
    category: "Trousers",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Navy", "Beige"],
    brand: "Modern Cut",
    rating: 4.6,
    reviews: 189,
    features: ["Cropped", "Ankle Length", "Tapered"],
    icon: "👖",
    itemCount: "Modern",
  },
  {
    id: "wtr-004",
    name: "Palazzo Pants",
    price: "$48",
    image: "https://images.unsplash.com/photo-1699205016746-8aa2e6e48453?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Flowing palazzo pants perfect for casual elegance",
    category: "Trousers",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Floral", "Solid"],
    brand: "Bohemian Style",
    rating: 4.5,
    reviews: 167,
    features: ["Palazzo Style", "Flowing", "Casual Elegant"],
    icon: "👖",
    itemCount: "Bohemian",
  },
  {
    id: "wtr-005",
    name: "Tailored Dress Pants",
    price: "$72",
    image: "https://images.unsplash.com/photo-1699205016746-8aa2e6e48453?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Perfectly tailored dress pants for business wear",
    category: "Trousers",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Charcoal", "Pinstripe"],
    brand: "Executive Style",
    rating: 4.9,
    reviews: 312,
    features: ["Tailored", "Dress Pants", "Business"],
    icon: "👖",
    itemCount: "Executive",
  },
  {
    id: "wtr-006",
    name: "Linen Trousers",
    price: "$62",
    image: "https://images.unsplash.com/photo-1699205016746-8aa2e6e48453?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Breathable linen trousers for summer comfort",
    category: "Trousers",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Natural", "White", "Navy", "Sage"],
    brand: "Summer Comfort",
    rating: 4.4,
    reviews: 145,
    features: ["100% Linen", "Breathable", "Summer"],
    icon: "👖",
    itemCount: "Summer",
  },
  {
    id: "wtr-007",
    name: "Pleated Front Trousers",
    price: "$65",
    image: "https://images.unsplash.com/photo-1699205016746-8aa2e6e48453?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Vintage-inspired pleated front trousers",
    category: "Trousers",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Brown", "Gray"],
    brand: "Vintage Revival",
    rating: 4.6,
    reviews: 178,
    features: ["Pleated Front", "Vintage Inspired", "Classic"],
    icon: "👖",
    itemCount: "Vintage",
  },
  {
    id: "wtr-008",
    name: "Jogger Trousers",
    price: "$45",
    image: "https://images.unsplash.com/photo-1699205016746-8aa2e6e48453?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Comfortable jogger-style trousers for casual wear",
    category: "Trousers",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Gray", "Black", "Navy", "Olive"],
    brand: "Casual Comfort",
    rating: 4.3,
    reviews: 134,
    features: ["Jogger Style", "Comfortable", "Casual"],
    icon: "👖",
    itemCount: "Casual",
  },
  {
    id: "wtr-009",
    name: "Paperbag Waist Pants",
    price: "$55",
    image: "https://images.unsplash.com/photo-1699205016746-8aa2e6e48453?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy paperbag waist pants with tie belt",
    category: "Trousers",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Camel", "Black", "Navy", "Olive"],
    brand: "Trend Forward",
    rating: 4.5,
    reviews: 156,
    features: ["Paperbag Waist", "Tie Belt", "Trendy"],
    icon: "👖",
    itemCount: "Trendy",
  },
  {
    id: "wtr-010",
    name: "Cargo Pants",
    price: "$58",
    image: "https://images.unsplash.com/photo-1699205016746-8aa2e6e48453?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Utility-inspired cargo pants with multiple pockets",
    category: "Trousers",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Khaki", "Black", "Olive", "Navy"],
    brand: "Utility Chic",
    rating: 4.4,
    reviews: 123,
    features: ["Cargo Pockets", "Utility Style", "Functional"],
    icon: "👖",
    itemCount: "Utility",
  }
];

export function WomenTrousersPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-green-50 via-blue-50 to-purple-50">
      <main className="flex-1">
        <ProductGrid 
          title="Women's Trousers Collection" 
          subtitle="Professional & Casual Styles"
          products={womenTrousersProducts} 
        />
      </main>
    </div>
  );
}