import { ProductGrid } from "../ProductGrid";

const womenAccessoriesProducts = [
  {
    id: "wa-001",
    name: "Designer Leather Handbag",
    price: "$298",
    image: "https://shopick.co.ke/wp-content/uploads/2023/04/WhatsApp-Image-2023-03-02-at-8.17.02-AM-1.jpeg",
    description: "Elegant designer leather handbag with gold hardware",
    category: "Handbags",
    sizes: ["One Size"],
    colors: ["Classic Black", "Cognac Brown", "Cream White", "Burgundy"],
    brand: "Luxe Collection",
    rating: 4.9,
    reviews: 387,
    features: ["Genuine Leather", "Gold Hardware", "Designer"],
    icon: "👜",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "wa-002",
    name: "Pearl Statement Necklace",
    price: "$145",
    image: "https://m.media-amazon.com/images/I/71p8rwXA0nL._UY1000_.jpg",
    description: "Elegant pearl statement necklace for special occasions",
    category: "Jewelry",
    sizes: ["One Size"],
    colors: ["Classic White", "Cream Pearl", "Tahitian Black"],
    brand: "Pearl Elegance",
    rating: 4.8,
    reviews: 234,
    features: ["Genuine Pearls", "Statement Piece", "Elegant"],
    icon: "📿",
    itemCount: "Elegant",
  },
  {
    id: "wa-003",
    name: "Silk Designer Scarf",
    price: "$89",
    image: "https://nestasia.in/cdn/shop/files/GeometricDesignerScarf_2.jpg?v=1699534777",
    description: "Luxurious silk scarf with artistic print design",
    category: "Scarves",
    sizes: ["One Size"],
    colors: ["Floral Blue", "Abstract Pink", "Geometric Gold"],
    brand: "Silk Artistry",
    rating: 4.7,
    reviews: 198,
    features: ["100% Silk", "Artistic Print", "Luxurious"],
    icon: "🧣",
    itemCount: "Artistic",
  },
  {
    id: "wa-004",
    name: "Cat-Eye Sunglasses",
    price: "$112",
    image: "https://ae01.alicdn.com/kf/S425995e73a22445896602cfb726a3673Q.png",
    description: "Vintage-inspired cat-eye sunglasses with UV protection",
    category: "Sunglasses",
    sizes: ["One Size"],
    colors: ["Tortoise Shell", "Black Frame", "Rose Gold"],
    brand: "Vintage Vision",
    rating: 4.6,
    reviews: 167,
    features: ["Cat-Eye Design", "UV Protection", "Vintage Style"],
    icon: "🕶️",
    itemCount: "Vintage",
  },
  {
    id: "wa-005",
    name: "Diamond Tennis Bracelet",
    price: "$395",
    image: "https://reneedeparisjewelry.com/cdn/shop/files/7AA15DF0-492F-4318-ADC3-F57AA2049FDD.jpg?v=1720545335&width=3024",
    description: "Sparkling diamond tennis bracelet in white gold",
    category: "Jewelry",
    sizes: ["S", "M", "L"],
    colors: ["White Gold", "Yellow Gold", "Rose Gold"],
    brand: "Diamond Luxury",
    rating: 4.9,
    reviews: 289,
    features: ["Real Diamonds", "Tennis Style", "Gold Setting"],
    icon: "💎",
    itemCount: "Luxury",
  },
  {
    id: "wa-006",
    name: "Leather Crossbody Bag",
    price: "$156",
    image: "https://cdn.clothbase.com/uploads/34a69a1d-48ca-4929-96c4-fbe7028f131f/P01043643_d2.jpg",
    description: "Compact leather crossbody bag for everyday elegance",
    category: "Handbags",
    sizes: ["One Size"],
    colors: ["Black", "Tan", "Navy", "Pink"],
    brand: "Everyday Luxury",
    rating: 4.5,
    reviews: 145,
    features: ["Crossbody Style", "Compact Size", "Everyday"],
    icon: "👜",
    itemCount: "Everyday",
  },
  {
    id: "wa-007",
    name: "Hair Accessory Set",
    price: "$42",
    image: "https://img.drz.lazcdn.com/static/pk/p/04c64d7a6ef5ae6cd344c47621d90376.jpg_720x720q80.jpg",
    description: "Elegant hair accessory set with clips and bands",
    category: "Hair",
    sizes: ["One Size"],
    colors: ["Gold Set", "Silver Set", "Rose Gold Set"],
    brand: "Hair Couture",
    rating: 4.4,
    reviews: 123,
    features: ["Complete Set", "Multiple Pieces", "Elegant"],
    icon: "💇‍♀️",
    itemCount: "Complete",
  },
  {
    id: "wa-008",
    name: "Designer Watch",
    price: "$278",
    image: "https://rukminim2.flixcart.com/image/750/900/xif0q/watch/9/u/8/1-bracelet-flower-stone-rose-gold-new-daniel-jubile-women-original-imah96qjhgnbtzfp.jpeg?q=90&crop=false",
    description: "Elegant designer watch with mother-of-pearl dial",
    category: "Watches",
    sizes: ["One Size"],
    colors: ["Rose Gold", "Silver", "Two-Tone"],
    brand: "Timepiece Elegance",
    rating: 4.7,
    reviews: 178,
    features: ["Mother-of-Pearl", "Designer", "Elegant"],
    icon: "⌚",
    itemCount: "Designer",
  },
  {
    id: "wa-009",
    name: "Clutch Evening Bag",
    price: "$98",
    image: "https://m.media-amazon.com/images/I/61WXy5NGBTL._UF894,1000_QL80_.jpg",
    description: "Elegant clutch bag perfect for evening events",
    category: "Handbags",
    sizes: ["One Size"],
    colors: ["Black Satin", "Gold Metallic", "Silver Beaded"],
    brand: "Evening Elegance",
    rating: 4.3,
    reviews: 134,
    features: ["Evening Style", "Compact", "Elegant"],
    icon: "👛",
    itemCount: "Evening",
  },
  {
    id: "wa-010",
    name: "Statement Earrings",
    price: "$67",
    image: "https://i.etsystatic.com/9934099/r/il/1b5fda/6729089381/il_fullxfull.6729089381_7120.jpg",
    description: "Bold statement earrings with geometric design",
    category: "Jewelry",
    sizes: ["One Size"],
    colors: ["Gold Statement", "Silver Bold", "Rose Gold Geo"],
    brand: "Statement Jewelry",
    rating: 4.6,
    reviews: 156,
    features: ["Statement Design", "Geometric", "Bold"],
    icon: "👂",
    itemCount: "Statement",
  }
];

export function WomenAccessoriesPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-pink-50 via-purple-50 to-amber-50">
      <main className="flex-1">
        <ProductGrid 
          title="Women's Accessories Collection" 
          subtitle="Elegant Accessories for the Sophisticated Woman"
          products={womenAccessoriesProducts} 
        />
      </main>
    </div>
  );
}
