import { motion } from "framer-motion";
import { Sun, ArrowRight, Star } from "lucide-react";
import { Button } from "../ui/button";
import { AnimatedEmoji } from "../animations";
import { ProductGrid } from "../ProductGrid";

const womenSkirtsAndShortsProducts = [
  {
    id: "wss-001",
    name: "High-Waisted Denim Shorts",
    price: "$42",
    image: "https://images.unsplash.com/photo-1741943716275-2eaf11f4e918?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21lbiUyMGRlbmltJTIwc2hvcnRzfGVufDF8fHx8MTc1NTE4ODg1M3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Classic high-waisted denim shorts with vintage wash",
    category: "Skirts & Shorts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Wash", "Medium Wash", "Dark Wash", "Black"],
    brand: "Denim Dreams",
    rating: 4.8,
    reviews: 324,
    features: ["High-Waisted", "Vintage Wash", "Cotton Denim"],
    icon: <Sun className="w-6 h-6" />,
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "wss-002",
    name: "Midi Pleated Skirt",
    price: "$55",
    image: "https://images.unsplash.com/photo-1615898290907-0ad011905389?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21lbiUyMG1pZGklMjBza2lydHxlbnwxfHx8fDE3NTUxODg4NTd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Elegant midi pleated skirt perfect for office or dinner",
    category: "Skirts & Shorts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy", "Black", "Burgundy", "Camel"],
    brand: "Elegant Style",
    rating: 4.7,
    reviews: 198,
    features: ["Midi Length", "Pleated Design", "Professional"],
    icon: <Sun className="w-6 h-6" />,
    itemCount: "Elegant",
  },
  {
    id: "wss-003",
    name: "Linen Summer Shorts",
    price: "$38",
    image: "https://images.unsplash.com/photo-1741943716275-2eaf11f4e918?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Breezy linen shorts perfect for hot summer days",
    category: "Skirts & Shorts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Natural", "Sage", "Coral"],
    brand: "Summer Vibes",
    rating: 4.6,
    reviews: 167,
    features: ["100% Linen", "Breathable", "High-Waisted"],
    icon: <Sun className="w-6 h-6" />,
    itemCount: "Summer Essential",
  },
  {
    id: "wss-004",
    name: "A-Line Mini Skirt",
    price: "$32",
    image: "https://images.unsplash.com/photo-1615898290907-0ad011905389?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Flirty A-line mini skirt with playful silhouette",
    category: "Skirts & Shorts",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "White", "Pink", "Denim"],
    brand: "Flirty Fashion",
    rating: 4.5,
    reviews: 234,
    features: ["A-Line Cut", "Mini Length", "Versatile"],
    icon: <Sun className="w-6 h-6" />,
    itemCount: "Flirty",
  },
  {
    id: "wss-005",
    name: "Athletic Bike Shorts",
    price: "$28",
    image: "https://images.unsplash.com/photo-1741943716275-2eaf11f4e918?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "High-performance bike shorts for active lifestyles",
    category: "Skirts & Shorts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Gray", "Purple"],
    brand: "Active Wear",
    rating: 4.8,
    reviews: 289,
    features: ["Moisture-Wicking", "Compression", "Athletic"],
    icon: <Sun className="w-6 h-6" />,
    itemCount: "Athletic",
  },
  {
    id: "wss-006",
    name: "Wrap Maxi Skirt",
    price: "$68",
    image: "https://images.unsplash.com/photo-1615898290907-0ad011905389?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Flowing wrap maxi skirt with bohemian flair",
    category: "Skirts & Shorts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Floral", "Solid Navy", "Paisley", "Striped"],
    brand: "Bohemian Style",
    rating: 4.6,
    reviews: 145,
    features: ["Wrap Design", "Maxi Length", "Bohemian"],
    icon: <Sun className="w-6 h-6" />,
    itemCount: "Boho",
  },
  {
    id: "wss-007",
    name: "Tailored Bermuda Shorts",
    price: "$45",
    image: "https://images.unsplash.com/photo-1741943716275-2eaf11f4e918?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sophisticated bermuda shorts for professional wear",
    category: "Skirts & Shorts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy", "Black", "Khaki", "Gray"],
    brand: "Professional Line",
    rating: 4.7,
    reviews: 178,
    features: ["Tailored Fit", "Professional", "Bermuda Length"],
    icon: <Sun className="w-6 h-6" />,
    itemCount: "Professional",
  },
  {
    id: "wss-008",
    name: "Pencil Skirt",
    price: "$52",
    image: "https://images.unsplash.com/photo-1615898290907-0ad011905389?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic pencil skirt with flattering fitted silhouette",
    category: "Skirts & Shorts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Gray", "Burgundy"],
    brand: "Classic Elegance",
    rating: 4.8,
    reviews: 267,
    features: ["Pencil Cut", "Back Slit", "Professional"],
    icon: <Sun className="w-6 h-6" />,
    itemCount: "Classic",
  },
  {
    id: "wss-009",
    name: "Cargo Utility Shorts",
    price: "$39",
    image: "https://images.unsplash.com/photo-1741943716275-2eaf11f4e918?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy cargo shorts with functional pockets",
    category: "Skirts & Shorts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Olive", "Black", "Khaki", "Navy"],
    brand: "Utility Chic",
    rating: 4.5,
    reviews: 156,
    features: ["Cargo Pockets", "Utility Style", "Trendy"],
    icon: <Sun className="w-6 h-6" />,
    itemCount: "Utility",
  },
  {
    id: "wss-010",
    name: "Circle Skirt",
    price: "$48",
    image: "https://images.unsplash.com/photo-1615898290907-0ad011905389?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Playful circle skirt with vintage-inspired fullness",
    category: "Skirts & Shorts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Polka Dot", "Solid Red", "Floral", "Navy"],
    brand: "Vintage Revival",
    rating: 4.4,
    reviews: 134,
    features: ["Circle Cut", "Full Skirt", "Vintage Style"],
    icon: <Sun className="w-6 h-6" />,
    itemCount: "Vintage",
  }
];

export function WomenSkirtsAndShortsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-amber-50 via-rose-50 to-purple-50">
      <main className="flex-1">
        <ProductGrid 
          title="Women's Skirts & Shorts Collection" 
          subtitle="Versatile Styles for Every Occasion"
          products={womenSkirtsAndShortsProducts} 
        />
      </main>
    </div>
  );
}