import { ProductGrid } from "../ProductGrid";

const womenAccessoriesProducts = [
  {
    id: "wa-001",
    name: "Designer Leather Handbag",
    price: "$298",
    image: "https://images.unsplash.com/photo-1672411914700-7af0e7530999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21lbiUyMGFjY2Vzc29yaWVzJTIwaGFuZGJhZ3MlMjBqZXdlbHJ5fGVufDF8fHx8MTc1NTE5MjM5Nnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Elegant designer leather handbag with gold hardware",
    category: "Handbags",
    sizes: ["One Size"],
    colors: ["Classic Black", "Cognac Brown", "Cream White", "Burgundy"],
    brand: "Luxe Collection",
    rating: 4.9,
    reviews: 387,
    features: ["Genuine Leather", "Gold Hardware", "Designer"],
    icon: "👜",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "wa-002",
    name: "Pearl Statement Necklace",
    price: "$145",
    image: "https://images.unsplash.com/photo-1672411914700-7af0e7530999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant pearl statement necklace for special occasions",
    category: "Jewelry",
    sizes: ["One Size"],
    colors: ["Classic White", "Cream Pearl", "Tahitian Black"],
    brand: "Pearl Elegance",
    rating: 4.8,
    reviews: 234,
    features: ["Genuine Pearls", "Statement Piece", "Elegant"],
    icon: "📿",
    itemCount: "Elegant",
  },
  {
    id: "wa-003",
    name: "Silk Designer Scarf",
    price: "$89",
    image: "https://images.unsplash.com/photo-1672411914700-7af0e7530999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Luxurious silk scarf with artistic print design",
    category: "Scarves",
    sizes: ["One Size"],
    colors: ["Floral Blue", "Abstract Pink", "Geometric Gold"],
    brand: "Silk Artistry",
    rating: 4.7,
    reviews: 198,
    features: ["100% Silk", "Artistic Print", "Luxurious"],
    icon: "🧣",
    itemCount: "Artistic",
  },
  {
    id: "wa-004",
    name: "Cat-Eye Sunglasses",
    price: "$112",
    image: "https://images.unsplash.com/photo-1672411914700-7af0e7530999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Vintage-inspired cat-eye sunglasses with UV protection",
    category: "Sunglasses",
    sizes: ["One Size"],
    colors: ["Tortoise Shell", "Black Frame", "Rose Gold"],
    brand: "Vintage Vision",
    rating: 4.6,
    reviews: 167,
    features: ["Cat-Eye Design", "UV Protection", "Vintage Style"],
    icon: "🕶️",
    itemCount: "Vintage",
  },
  {
    id: "wa-005",
    name: "Diamond Tennis Bracelet",
    price: "$395",
    image: "https://images.unsplash.com/photo-1672411914700-7af0e7530999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Sparkling diamond tennis bracelet in white gold",
    category: "Jewelry",
    sizes: ["S", "M", "L"],
    colors: ["White Gold", "Yellow Gold", "Rose Gold"],
    brand: "Diamond Luxury",
    rating: 4.9,
    reviews: 289,
    features: ["Real Diamonds", "Tennis Style", "Gold Setting"],
    icon: "💎",
    itemCount: "Luxury",
  },
  {
    id: "wa-006",
    name: "Leather Crossbody Bag",
    price: "$156",
    image: "https://images.unsplash.com/photo-1672411914700-7af0e7530999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Compact leather crossbody bag for everyday elegance",
    category: "Handbags",
    sizes: ["One Size"],
    colors: ["Black", "Tan", "Navy", "Pink"],
    brand: "Everyday Luxury",
    rating: 4.5,
    reviews: 145,
    features: ["Crossbody Style", "Compact Size", "Everyday"],
    icon: "👜",
    itemCount: "Everyday",
  },
  {
    id: "wa-007",
    name: "Hair Accessory Set",
    price: "$42",
    image: "https://images.unsplash.com/photo-1672411914700-7af0e7530999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant hair accessory set with clips and bands",
    category: "Hair",
    sizes: ["One Size"],
    colors: ["Gold Set", "Silver Set", "Rose Gold Set"],
    brand: "Hair Couture",
    rating: 4.4,
    reviews: 123,
    features: ["Complete Set", "Multiple Pieces", "Elegant"],
    icon: "💇‍♀️",
    itemCount: "Complete",
  },
  {
    id: "wa-008",
    name: "Designer Watch",
    price: "$278",
    image: "https://images.unsplash.com/photo-1672411914700-7af0e7530999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant designer watch with mother-of-pearl dial",
    category: "Watches",
    sizes: ["One Size"],
    colors: ["Rose Gold", "Silver", "Two-Tone"],
    brand: "Timepiece Elegance",
    rating: 4.7,
    reviews: 178,
    features: ["Mother-of-Pearl", "Designer", "Elegant"],
    icon: "⌚",
    itemCount: "Designer",
  },
  {
    id: "wa-009",
    name: "Clutch Evening Bag",
    price: "$98",
    image: "https://images.unsplash.com/photo-1672411914700-7af0e7530999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Elegant clutch bag perfect for evening events",
    category: "Handbags",
    sizes: ["One Size"],
    colors: ["Black Satin", "Gold Metallic", "Silver Beaded"],
    brand: "Evening Elegance",
    rating: 4.3,
    reviews: 134,
    features: ["Evening Style", "Compact", "Elegant"],
    icon: "👛",
    itemCount: "Evening",
  },
  {
    id: "wa-010",
    name: "Statement Earrings",
    price: "$67",
    image: "https://images.unsplash.com/photo-1672411914700-7af0e7530999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Bold statement earrings with geometric design",
    category: "Jewelry",
    sizes: ["One Size"],
    colors: ["Gold Statement", "Silver Bold", "Rose Gold Geo"],
    brand: "Statement Jewelry",
    rating: 4.6,
    reviews: 156,
    features: ["Statement Design", "Geometric", "Bold"],
    icon: "👂",
    itemCount: "Statement",
  }
];

export function WomenAccessoriesPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-pink-50 via-purple-50 to-amber-50">
      <main className="flex-1">
        <ProductGrid 
          title="Women's Accessories Collection" 
          subtitle="Elegant Accessories for the Sophisticated Woman"
          products={womenAccessoriesProducts} 
        />
      </main>
    </div>
  );
}