import { motion } from "motion/react";
import { Shirt, ArrowRight, Star } from "lucide-react";
import { Button } from "../ui/button";
import { AnimatedEmoji } from "../animations";
import { ProductGrid } from "../ProductGrid";

// Women's Shirts Products Data
const womenShirtsProducts = [
  {
    id: "ws-001",
    name: "Classic White Button-Down",
    price: "$58",
    image: "https://images.unsplash.com/photo-1595272251257-1bbe120103d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21lbiUyMGJsb3VzZSUyMHNoaXJ0fGVufDF8fHx8MTc1NTEyMTA0N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Timeless white button-down shirt perfect for professional and casual wear",
    category: "Shirts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Light Blue", "Pink", "Cream"],
    brand: "Professional Line",
    rating: 4.9,
    reviews: 412,
    features: ["Button-Down Collar", "Classic Fit", "Wrinkle Resistant"],
    icon: <Shirt className="w-6 h-6" />,
    popular: true,
    itemCount: "Essential",
  },
  {
    id: "ws-002", 
    name: "Silk Blouse",
    price: "$85",
    image: "https://images.unsplash.com/photo-1541101767792-f9b2b1c4f127?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21lbiUyMGJ1c2luZXNzJTIwc2hpcnR8ZW58MXx8fHwxNzU1MTg4ODEwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Luxurious silk blouse with elegant drape and sophisticated style",
    category: "Shirts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Ivory", "Blush", "Navy", "Emerald"],
    brand: "Luxury Collection",
    rating: 4.8,
    reviews: 234,
    features: ["100% Silk", "Elegant Drape", "Luxury Feel"],
    icon: <Shirt className="w-6 h-6" />,
    itemCount: "Luxury",
  },
  {
    id: "ws-003",
    name: "Relaxed Linen Shirt", 
    price: "$52",
    image: "https://images.unsplash.com/photo-1595272251257-1bbe120103d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Breezy linen shirt with relaxed fit perfect for warm weather",
    category: "Shirts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Natural", "White", "Sage", "Coral"],
    brand: "Summer Breeze",
    rating: 4.6,
    reviews: 189,
    features: ["100% Linen", "Relaxed Fit", "Breathable"],
    icon: <Shirt className="w-6 h-6" />,
    itemCount: "Summer Essential",
  },
  {
    id: "ws-004",
    name: "Floral Print Blouse",
    price: "$48",
    image: "https://images.unsplash.com/photo-1541101767792-f9b2b1c4f127?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Feminine floral print blouse with flowing silhouette",
    category: "Shirts", 
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Pink Floral", "Blue Floral", "White Floral"],
    brand: "Feminine Touch",
    rating: 4.5,
    reviews: 167,
    features: ["Floral Print", "Flowing Fit", "Feminine Style"],
    icon: <Shirt className="w-6 h-6" />,
    itemCount: "Floral",
  },
  {
    id: "ws-005",
    name: "Chambray Work Shirt",
    price: "$44",
    image: "https://images.unsplash.com/photo-1595272251257-1bbe120103d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Casual chambray shirt with classic styling and comfort",
    category: "Shirts",
    sizes: ["XS", "S", "M", "L", "XL"], 
    colors: ["Light Denim", "Dark Denim", "White"],
    brand: "Casual Classics",
    rating: 4.4,
    reviews: 203,
    features: ["Chambray Fabric", "Classic Cut", "Versatile"],
    icon: <Shirt className="w-6 h-6" />,
    itemCount: "Casual",
  },
  {
    id: "ws-006",
    name: "Tie-Front Blouse",
    price: "$42",
    image: "https://images.unsplash.com/photo-1541101767792-f9b2b1c4f127?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Playful tie-front blouse with modern feminine details",
    category: "Shirts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Blush", "Navy", "Sage"],
    brand: "Modern Feminine",
    rating: 4.7,
    reviews: 156,
    features: ["Tie-Front Detail", "Modern Cut", "Feminine"],
    icon: <Shirt className="w-6 h-6" />,
    itemCount: "Trendy",
  },
  {
    id: "ws-007", 
    name: "Oversized Button Shirt",
    price: "$55",
    image: "https://images.unsplash.com/photo-1595272251257-1bbe120103d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Contemporary oversized shirt with boyfriend-inspired styling",
    category: "Shirts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Stripe", "Gingham", "Solid Navy"],
    brand: "Contemporary",
    rating: 4.6,
    reviews: 178,
    features: ["Oversized Fit", "Boyfriend Style", "Contemporary"],
    icon: <Shirt className="w-6 h-6" />,
    itemCount: "Oversized",
  },
  {
    id: "ws-008",
    name: "Peplum Work Blouse",
    price: "$62",
    image: "https://images.unsplash.com/photo-1541101767792-f9b2b1c4f127?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Professional peplum blouse with flattering waist detail",
    category: "Shirts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy", "Black", "Burgundy", "Emerald"],
    brand: "Executive Style",
    rating: 4.8,
    reviews: 134,
    features: ["Peplum Hem", "Professional", "Flattering Cut"],
    icon: <Shirt className="w-6 h-6" />,
    itemCount: "Professional",
  },
  {
    id: "ws-009",
    name: "Off-Shoulder Blouse", 
    price: "$46",
    image: "https://images.unsplash.com/photo-1595272251257-1bbe120103d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Romantic off-shoulder blouse perfect for date nights",
    category: "Shirts",
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Blush", "Black", "Coral"],
    brand: "Romantic Style",
    rating: 4.5,
    reviews: 145,
    features: ["Off-Shoulder", "Romantic Style", "Date Night"],
    icon: <Shirt className="w-6 h-6" />,
    itemCount: "Romantic",
  },
  {
    id: "ws-010",
    name: "Tunic Length Shirt",
    price: "$50",
    image: "https://images.unsplash.com/photo-1541101767792-f9b2b1c4f127?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Versatile tunic length shirt perfect for layering",
    category: "Shirts",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Navy", "Gray", "Sage"],
    brand: "Versatile Basics",
    rating: 4.4,
    reviews: 198,
    features: ["Tunic Length", "Versatile", "Layering"],
    icon: <Shirt className="w-6 h-6" />,
    itemCount: "Versatile",
  }
];

export function WomenShirtsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-purple-50 to-rose-50">
      <main className="flex-1">
        <ProductGrid 
          title="Women's Shirts Collection" 
          subtitle="Professional & Elegant Styles"
          products={womenShirtsProducts} 
        />
      </main>
    </div>
  );
}