import { ProductGrid } from "../ProductGrid";

const womenJeansProducts = [
  {
    id: "wj-001",
    name: "High-Rise Skinny Jeans",
    price: "$78",
    image: "https://images.unsplash.com/photo-1609831190577-04538764f438?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21lbiUyMGplYW5zJTIwZGVuaW18ZW58MXx8fHwxNzU1MTgzMDA5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Classic high-rise skinny jeans with stretch comfort",
    category: "Jeans",
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31", "32"],
    colors: ["Dark Wash", "Medium Wash", "Light Wash", "Black"],
    brand: "Denim Co",
    rating: 4.8,
    reviews: 456,
    features: ["High-Rise", "Skinny Fit", "Stretch"],
    icon: "👖",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "wj-002",
    name: "Mom Jeans",
    price: "$68",
    image: "https://images.unsplash.com/photo-1609831190577-04538764f438?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Vintage-inspired mom jeans with relaxed fit",
    category: "Jeans",
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31", "32"],
    colors: ["Vintage Wash", "Light Blue", "Medium Blue", "Dark Blue"],
    brand: "Vintage Denim",
    rating: 4.7,
    reviews: 298,
    features: ["Mom Fit", "High-Waisted", "Vintage Style"],
    icon: "👖",
    itemCount: "Vintage",
  },
  {
    id: "wj-003",
    name: "Wide-Leg Jeans",
    price: "$85",
    image: "https://images.unsplash.com/photo-1609831190577-04538764f438?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy wide-leg jeans with contemporary styling",
    category: "Jeans",
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31", "32"],
    colors: ["Medium Wash", "Dark Wash", "Light Wash"],
    brand: "Modern Denim",
    rating: 4.6,
    reviews: 234,
    features: ["Wide-Leg", "Contemporary", "High-Waisted"],
    icon: "👖",
    itemCount: "Trendy",
  },
  {
    id: "wj-004",
    name: "Boyfriend Jeans",
    price: "$72",
    image: "https://images.unsplash.com/photo-1609831190577-04538764f438?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Relaxed boyfriend jeans with distressed details",
    category: "Jeans",
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31", "32"],
    colors: ["Light Distressed", "Medium Distressed", "Dark Wash"],
    brand: "Casual Denim",
    rating: 4.5,
    reviews: 189,
    features: ["Boyfriend Fit", "Distressed", "Relaxed"],
    icon: "👖",
    itemCount: "Casual",
  },
  {
    id: "wj-005",
    name: "Straight Leg Jeans",
    price: "$65",
    image: "https://images.unsplash.com/photo-1609831190577-04538764f438?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Classic straight leg jeans for timeless style",
    category: "Jeans",
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31", "32"],
    colors: ["Dark Indigo", "Medium Blue", "Light Blue", "Black"],
    brand: "Classic Denim",
    rating: 4.7,
    reviews: 267,
    features: ["Straight Leg", "Classic Fit", "Timeless"],
    icon: "👖",
    itemCount: "Classic",
  },
  {
    id: "wj-006",
    name: "Flare Jeans",
    price: "$75",
    image: "https://images.unsplash.com/photo-1609831190577-04538764f438?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Retro-inspired flare jeans with 70s vibes",
    category: "Jeans",
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31", "32"],
    colors: ["Medium Wash", "Dark Wash", "Light Wash"],
    brand: "Retro Denim",
    rating: 4.4,
    reviews: 156,
    features: ["Flare Leg", "Retro Style", "70s Inspired"],
    icon: "👖",
    itemCount: "Retro",
  },
  {
    id: "wj-007",
    name: "Cropped Jeans",
    price: "$58",
    image: "https://images.unsplash.com/photo-1609831190577-04538764f438?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Modern cropped jeans perfect for showing ankles",
    category: "Jeans",
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31", "32"],
    colors: ["Medium Blue", "Dark Blue", "Light Blue"],
    brand: "Modern Cut",
    rating: 4.5,
    reviews: 178,
    features: ["Cropped Length", "Modern Fit", "Ankle Length"],
    icon: "👖",
    itemCount: "Modern",
  },
  {
    id: "wj-008",
    name: "Bootcut Jeans",
    price: "$69",
    image: "https://images.unsplash.com/photo-1609831190577-04538764f438?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Flattering bootcut jeans with slight flare",
    category: "Jeans",
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31", "32"],
    colors: ["Dark Wash", "Medium Wash", "Black"],
    brand: "Flattering Fit",
    rating: 4.6,
    reviews: 223,
    features: ["Bootcut", "Flattering", "Slight Flare"],
    icon: "👖",
    itemCount: "Flattering",
  },
  {
    id: "wj-009",
    name: "Jeggings",
    price: "$48",
    image: "https://images.unsplash.com/photo-1609831190577-04538764f438?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Ultra-comfortable jeggings with maximum stretch",
    category: "Jeans",
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31", "32"],
    colors: ["Dark Blue", "Black", "Medium Blue"],
    brand: "Comfort Plus",
    rating: 4.3,
    reviews: 134,
    features: ["Jegging Style", "Maximum Stretch", "Comfortable"],
    icon: "👖",
    itemCount: "Comfortable",
  },
  {
    id: "wj-010",
    name: "High-Rise Wide Leg",
    price: "$88",
    image: "https://images.unsplash.com/photo-1609831190577-04538764f438?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "High-rise wide leg jeans for statement styling",
    category: "Jeans",
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31", "32"],
    colors: ["Dark Wash", "Medium Wash", "Black"],
    brand: "Statement Denim",
    rating: 4.7,
    reviews: 198,
    features: ["High-Rise", "Wide Leg", "Statement"],
    icon: "👖",
    itemCount: "Statement",
  }
];

export function WomenJeansPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-indigo-50 via-blue-50 to-cyan-50">
      <main className="flex-1">
        <ProductGrid 
          title="Women's Jeans Collection" 
          subtitle="Denim for Every Style"
          products={womenJeansProducts} 
        />
      </main>
    </div>
  );
}