import { ProductGrid } from "../ProductGrid";

const womenActivewearProducts = [
  {
    id: "wa-001",
    name: "High-Waisted Leggings",
    price: "$48",
    image: "https://images.unsplash.com/photo-1546687307-88d0e10fe96f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21lbiUyMGFjdGl2ZXdlYXIlMjBzcG9ydHN8ZW58MXx8fHwxNzU1MTg4OTAxfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    description: "Compression leggings with moisture-wicking technology",
    category: "Activewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Gray", "Purple"],
    brand: "Active Pro",
    rating: 4.8,
    reviews: 456,
    features: ["High-Waisted", "Compression", "Moisture-Wicking"],
    icon: "🏃‍♀️",
    popular: true,
    itemCount: "Best Seller",
  },
  {
    id: "wa-002",
    name: "Sports Bra",
    price: "$32",
    image: "https://images.unsplash.com/photo-1546687307-88d0e10fe96f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Medium support sports bra with removable padding",
    category: "Activewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Pink", "Gray"],
    brand: "Support Plus",
    rating: 4.7,
    reviews: 234,
    features: ["Medium Support", "Removable Padding", "Breathable"],
    icon: "🏃‍♀️",
    itemCount: "Support",
  },
  // Adding 8 more products with similar structure...
  {
    id: "wa-003",
    name: "Workout Tank Top",
    price: "$28",
    image: "https://images.unsplash.com/photo-1546687307-88d0e10fe96f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Lightweight tank with built-in shelf bra",
    category: "Activewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Coral", "Mint"],
    brand: "Fit Life",
    rating: 4.6,
    reviews: 189,
    features: ["Built-in Bra", "Lightweight", "Quick-Dry"],
    icon: "🏃‍♀️",
    itemCount: "Lightweight",
  },
  {
    id: "wa-004",
    name: "Yoga Shorts",
    price: "$35",
    image: "https://images.unsplash.com/photo-1546687307-88d0e10fe96f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Buttery-soft yoga shorts with side pockets",
    category: "Activewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Sage", "Burgundy"],
    brand: "Zen Active",
    rating: 4.8,
    reviews: 298,
    features: ["Side Pockets", "Buttery-Soft", "Yoga"],
    icon: "🏃‍♀️",
    itemCount: "Yoga",
  },
  {
    id: "wa-005",
    name: "Running Jacket",
    price: "$68",
    image: "https://images.unsplash.com/photo-1546687307-88d0e10fe96f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Lightweight running jacket with reflective details",
    category: "Activewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Neon Pink", "Gray"],
    brand: "Run Fast",
    rating: 4.5,
    reviews: 167,
    features: ["Reflective", "Lightweight", "Wind-Resistant"],
    icon: "🏃‍♀️",
    itemCount: "Running",
  },
  {
    id: "wa-006",
    name: "Seamless Leggings",
    price: "$52",
    image: "https://images.unsplash.com/photo-1546687307-88d0e10fe96f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Seamless construction for ultimate comfort",
    category: "Activewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Nude", "Gray", "Navy"],
    brand: "Seamless Pro",
    rating: 4.7,
    reviews: 223,
    features: ["Seamless", "Comfortable", "Stretchy"],
    icon: "🏃‍♀️",
    itemCount: "Seamless",
  },
  {
    id: "wa-007",
    name: "Cropped Hoodie",
    price: "$45",
    image: "https://images.unsplash.com/photo-1546687307-88d0e10fe96f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Trendy cropped hoodie perfect for pre/post workout",
    category: "Activewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Gray", "Black", "Pink", "White"],
    brand: "Urban Fit",
    rating: 4.4,
    reviews: 145,
    features: ["Cropped", "Hoodie", "Casual"],
    icon: "🏃‍♀️",
    itemCount: "Trendy",
  },
  {
    id: "wa-008",
    name: "Performance Capris",
    price: "$42",
    image: "https://images.unsplash.com/photo-1546687307-88d0e10fe96f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Mid-length capris with four-way stretch",
    category: "Activewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Purple", "Teal"],
    brand: "Stretch Pro",
    rating: 4.6,
    reviews: 198,
    features: ["Four-Way Stretch", "Capri Length", "Performance"],
    icon: "🏃‍♀️",
    itemCount: "Performance",
  },
  {
    id: "wa-009",
    name: "Long Sleeve Top",
    price: "$38",
    image: "https://images.unsplash.com/photo-1546687307-88d0e10fe96f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Thumb-hole long sleeve with UPF protection",
    category: "Activewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Gray", "Navy"],
    brand: "Sun Safe",
    rating: 4.5,
    reviews: 156,
    features: ["Thumb Holes", "UPF Protection", "Long Sleeve"],
    icon: "🏃‍♀️",
    itemCount: "Sun Safe",
  },
  {
    id: "wa-010",
    name: "Track Pants",
    price: "$55",
    image: "https://images.unsplash.com/photo-1546687307-88d0e10fe96f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description: "Comfortable track pants with side stripe detail",
    category: "Activewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black/White", "Navy/Blue", "Gray/Pink"],
    brand: "Track Star",
    rating: 4.3,
    reviews: 134,
    features: ["Side Stripe", "Comfortable", "Track Style"],
    icon: "🏃‍♀️",
    itemCount: "Track",
  }
];

export function WomenActivewearPage() {
  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50">
      <main className="flex-1">
        <ProductGrid 
          title="Women's Activewear Collection" 
          subtitle="Performance Meets Style"
          products={womenActivewearProducts} 
        />
      </main>
    </div>
  );
}